### ISSUE TITLE
blockstack series a fund raise blog imagery

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#102]
Create Series A fund raise blog post imagery

**Requirements**
- Size: 1600x900
- Keep image generic

**Comment by guylepage3** [comment]
![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21651212/cd371e5c-d275-11e6-9360-f0e6295b11f4.png)

**Comment by guylepage3** [comment]
@shea256 @muneeb-ali what do you think about this image for the blog post? also, I am proposing a change to the position/size of all blog post imagery here... 

https://github.com/blockstack/blockstack.org/issues/180

**Comment by shea256** [comment]
Looks good to me.

Just one thing to keep in mind is we should have the ability to vary images enough across blog posts. I noticed the image for the Azure post is very similar to the image for the USENIX post.

**Comment by guylepage3** [comment]
Good point. I will take a look at the other images and update those today as well so we have consistency on our new blog.

**Comment by guylepage3** [comment]
![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21690687/49b6a98e-d343-11e6-9671-3fae9633694e.png)

**Comment by guylepage3** [comment]
cleaned up version..

![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21691660/87e55080-d347-11e6-8866-a080609a86d4.png)

**Comment by guylepage3** [comment]
Final imagery

![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21692569/77763832-d34b-11e6-8484-29604a7f872a.png)

**Comment by guylepage3** [comment]
Final imagery

![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21692601/9f0ef352-d34b-11e6-9ac5-be034ce477e8.png)

**Comment by guylepage3** [comment]
Final final imagery

**Comment by guylepage3** [comment]
Final final imagery

![blog-blockstack-raise](https://cloud.githubusercontent.com/assets/1711854/21693250/34bbbdca-d34e-11e6-9a58-36e20491ed15.png)

**Comment by guylepage3** [comment]
Complete. Closing out this issue.
