### ISSUE TITLE
blockstack explorer blog post imagery

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/designs#119]

**Comment by guylepage3** [comment]
Adding context...
Blog post for https://explorer.blockstack.org/

Also, @larrysalibra can i do a quick skim of the post? It may spring forth ideas
Thx.

**Comment by larrysalibra** [comment]
@guylepage3 Sure. I posted a draft here https://forum.blockstack.org/t/announcing-blockstack-explorer/491?u=larry (you'll need to be logged in to see it) 

It's also in the ghost as a draft (not sure if you can see it there)

Thank you for the help with the imagery!

**Comment by guylepage3** [comment]
Hey @larrysalibra here's what I'm thinking for your post. Let me know your thoughts. If you have any comments open the issue up again

![blog-explorer](https://cloud.githubusercontent.com/assets/1711854/22272764/23561e92-e26a-11e6-8ed8-c0dc11c127ef.png)
