### ISSUE TITLE
decentralize the web challenge eventbrite banner image

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#124]
@pstan26 created an eventbrite page for the up-coming **"Decentralized Web Challenge"** for the Blockstack Idea Hackathon.

As a result we should start building imagery around these events to build unique brand awareness for our hackathons.

https://www.eventbrite.com/e/decentralizetheweb-challenge-tickets-31190551780

**Comment by guylepage3** [comment]
![blockstack-decentralized-web-challenge](https://cloud.githubusercontent.com/assets/1711854/22125600/5a531bcc-de62-11e6-9404-b5e1810ba2bf.png)

**Comment by guylepage3** [comment]
@pstan26 I feel we should create a template for hackathons and most events using the twitter 4:2 ratio size. as it will allow us to control tweet imagery best. Thoughts?

**Comment by guylepage3** [comment]
@pstan26 I am also creating a brand standards guide for things like, logo placement, when and where to use the atlas grid illustration, colors, bug, etc.. here: https://github.com/blockstack/designs/issues/131

**Comment by pstan26** [comment]
Sounds good on twitter ratio size, I can follow that going forward. What type of template are you thinking?

**Comment by guylepage3** [comment]
I'll create a template in Sketch.. The logo should be kept to the left as much as possible. Our brand typography is left aligned and our logo is as well.

**Comment by guylepage3** [comment]
@pstan26 it looks as though there is an eventbrite standard size.

See: https://www.eventbrite.com/support/articles/en_US/Troubleshooting/how-to-choose-a-great-event-image?lg=en_US

I am creating a "marketing.sketch" file template for you, where we can create eventbrite imagery, blog imagery, and other templates

If you ever need a new template just create a new GitHub issue and we'll go from there. I'll post the new template here as soon as it's complete.

**Comment by pstan26** [comment]
Perfect! Thank you.

**Comment by guylepage3** [comment]
@pstan26 here's the image and the link to the template is here:

- https://github.com/blockstack/designs/tree/master/marketing

![blockstack-decentralize-web-challenge](https://cloud.githubusercontent.com/assets/1711854/22128975/639c4d98-de71-11e6-8f53-51cdb32b698b.png)

**Comment by guylepage3** [comment]
we may need to create a separate "twitter image" for this as well. please let me know if we do. thx.

**Comment by pstan26** [comment]
Updated event page: https://www.eventbrite.com/e/decentralizetheweb-challenge-tickets-31190551780

I would definitely use a 2:4 Twitter image as you prescribed.

**Comment by guylepage3** [comment]
@pstan26 can you give me access to the eventbrite page. For some reason the image for the page does not update when tweeting out the link

**Comment by pstan26** [comment]
Just made you a co-organizer, so there should be an Eventbrite email in your inbox.

**Comment by guylepage3** [comment]
Cool. Thank you sir.
