### ISSUE TITLE
blockstack t-shirts

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#126]
@guylepage3 commented on [Tue Nov 22 2016](https://github.com/blockstack/blockstack/issues/123)

Time to start thinking about ordering more blockstack t-shirts.

I will run inventory on what we have today.

Also, I wanted to get everyone's thoughts on trying to get the printer to create our new custom **blockstack purple 110** color t-shirts. I feel this would be super unique and we have had quite a few requests for it as well.

<img width="296" alt="screenshot 2016-11-22 10 29 40" src="https://cloud.githubusercontent.com/assets/1711854/20529633/d0cfce72-b09e-11e6-957f-0c79fedb6f6b.png">

Alternatively, we can stick with the light blue t-shirts as well as the dark gray.

Thoughts?

---

@pstan26 commented on [Thu Jan 19 2017](https://github.com/blockstack/blockstack/issues/123#issuecomment-273882944)

The logo will naturally "pop" with that background. It is a deep purple too which is nice. I would certainly wear it out. Love the fact that we kind of "own" this color too, so why not rep it fully.

---

@guylepage3 commented on [Thu Jan 19 2017](https://github.com/blockstack/blockstack/issues/123#issuecomment-273887104)

@pstan26 I am moving this issue to the https://github.com/blockstack/designs repo

**Comment by pstan26** [comment]
Loving the dark purple. Could we do a bulk order soon for them around time for the #DecentralizeTheWeb challenge? We'll be sending out ~20-40 to all participants in the US.

**Comment by pstan26** [comment]
@guylepage3 Do you think this is something we are ready to send off to the printers by next week? We'll need to get this and the sticker (https://github.com/blockstack/designs/issues/199) orders sent soon. If you have the t-shirt printer and the sizes from last time, I'm happy to put the order in. Thanks!

**Comment by guylepage3** [comment]
@pstan26 if you could take the coordination of the t-shirts with sizes and amounts with ryan off my hands that would be super helpful.

One thing that I'd LOVE to have is the ability to get our deep purple as a t-shirt color.. Amplifier might be able to do it if we ask but i have not got around to talking with Al.

Here's Al's info if you want to give him a call?

```
Al Almuelle
Amplifier Client Service
support.amplifier.com
512-469-0505 x202
```

**Comment by guylepage3** [comment]
Our previous orders were something like this:

```
Base SKU: Blockstack blue
Category: apparel
Type: T-Shirt
Style: American Apparel TR401
Color: Athletic Blue

SKU / Quantities:
blockstack blue (size xs): 5
blockstack blue (size s): 12
blockstack blue (size m): 14
blockstack blue (size l): 12
blockstack blue (size xl): 5
blockstack blue (size 2xl): 2
```

**Comment by guylepage3** [comment]
And our re-run quantities...
```
Quantities: 
blockstack blue (size xs): 9
blockstack blue (size s): 34
blockstack blue (size m): 57
blockstack blue (size l): 39
blockstack blue (size xl): 22
blockstack blue (size 2xl): 15

Total Quantity 176
```

**Comment by guylepage3** [comment]
Reference: https://my.amplifier.com/

**Comment by pstan26** [comment]
Happy to help with this. Will call this guy this week about the purple
color.
Do we need to update the logo image from the last order, or will they have
the right image size and placement?
When we order will store these in the office?

**Comment by guylepage3** [comment]
We have to order via their internal web app. @pstan26 if you coordinate the order details i can push out the design and order what's needed.

**Comment by guylepage3** [comment]
@pstan26 

>Happy to help with this. Will call this guy this week about the purple color.
If you can contact the Amplifier folks that would be awesome.

>Do we need to update the logo image from the last order, or will they have the right image size and placement?
I will need to design the logo placement

>When we order will store these in the office?
Yes

**Comment by guylepage3** [comment]
@pstan26 @larrysalibra @shea256 @muneeb-ali @jcnelson 

Here are the latest blockstack t-shirt designs - without stereoscopy
![tshirt-sans-stereoscopy-blue](https://cloud.githubusercontent.com/assets/1711854/23275764/c7558190-f9d5-11e6-8316-5ef098adfa09.png)
![tshirt-sans-stereoscopy-dark](https://cloud.githubusercontent.com/assets/1711854/23275765/c7598ccc-f9d5-11e6-9e60-e3cda016a524.png)


Here are the latest blockstack t-shirt designs - with stereoscopy
![tshirt-avec-stereoscopy-blue](https://cloud.githubusercontent.com/assets/1711854/23275744/b161c6b4-f9d5-11e6-9cbb-373556cc8261.png)
![tshirt-avec-stereoscopy-dark](https://cloud.githubusercontent.com/assets/1711854/23275745/b16da7e0-f9d5-11e6-8738-87b18edef01f.png)

Thoughts?

**Comment by guylepage3** [comment]
I don't think stereoscopy works well for the t-shirts. I prefer them without the stereoscopy.

**Comment by pstan26** [comment]
noted, will pursue w/o stereoscopy

**Comment by guylepage3** [comment]
I'll need to get you a logo for that.. we have not created one without yet. :)

**Comment by pstan26** [comment]
@guylepage3 Egglplant is the closest thing American Apparel has to Blockstack Purple, lmkwyt
![screen shot 2017-02-23 at 3 20 53 pm](https://cloud.githubusercontent.com/assets/5605552/23277423/cc8d557e-f9db-11e6-9dfc-210f1bc1434f.png)

**Comment by guylepage3** [comment]
Eeeee.... I think @shea256 would agree that that's not our brand color. we took a look at that color on the last run and decided against it. i prefer the dark grey. but the blue seemed to be a big hit. Also this blue is one of our brand colors...

https://projects.invisionapp.com/boards/HE2VVROFSGB27/#/4846740/147808417
<img width="607" alt="screenshot 2017-02-23 15 24 55" src="https://cloud.githubusercontent.com/assets/1711854/23277555/40e5159c-f9dc-11e6-9270-df501ab1cdd8.png">

**Comment by pstan26** [comment]
Ok, then there is nothing remotely close within American Apparel for purple :-)

Here are their options for blue:
![screen shot 2017-02-23 at 3 27 55 pm](https://cloud.githubusercontent.com/assets/5605552/23277664/b67210b2-f9dc-11e6-98f3-e5bf3367ded0.png)


Meanwhile I'm going to check out some other brands that have dark purple that Amplifier will allow for.

**Comment by guylepage3** [comment]
can we use the same color code from last time? may need to call Al about it.
```
Style: American Apparel TR401
Color: Athletic Blue
```

**Comment by guylepage3** [comment]
yeah. i feel like we're going to be shit out of luck using amplifier to get our blockstack purple. i think we would need to find another supplier who could offer dying of a white t-shirt or something.. if it's too tough lets go with the blue or dark gray

**Comment by pstan26** [comment]
@guylepage3 Yea I think we will have find time to look into t-shirt dying. Since the blue is readily available, I'm going to put the order in. 

I've uploaded the preview picture, and it now it seems like I'll need a non-stereoscopic logo to upload. Is that already in Github or could you provide?

 I'll have these t-shirts ordered once we have that.

**Comment by larrysalibra** [comment]
I like the dark gray too.

**Comment by pstan26** [comment]
reminder to self once I have logos to [get hoodies](https://github.com/blockstack/designs/issues/127) too

**Comment by guylepage3** [comment]
will shoot that over later tonight. can you send me a reminder?

**Comment by pstan26** [comment]
@guylepage3 I couldn't find a non-stereoscopy logo, so I simply downloaded this one https://github.com/blockstack/designs/blob/master/swag/blockstack-logo-landscape-rev.svg.zip and removed the stereoscopy. I put grey backrgound behind it so you can see the white lettering and let me know if this works, otherwise I'll need an logo image file. Will wait to hear from you before proceeding on logo upload

![screen shot 2017-02-23 at 5 52 43 pm](https://cloud.githubusercontent.com/assets/5605552/23282833/10363f10-f9f1-11e6-98d2-4c6ee2ff672f.png)

**Comment by pstan26** [comment]
@guylepage3 I've just sent you a cal invite instead, I'm going to an event tonight so won't be around a computer

**Comment by guylepage3** [comment]
Let's use this logo please.

https://github.com/blockstack/designs/issues/206#issuecomment-282149752

**Comment by pstan26** [comment]
@guylepage3 suggested dimensions (in inches) for front and back of the t-shirt logo?

For the t-shirts it looks like it is a large logo on the front and small on the back, whereas with past hoodie orders (the only dimensions I currently have) it is the reverse. Thanks in advance!

**Comment by guylepage3** [comment]
Hm.. I don't really know. the dimensions. let's go with...

Print Location: Front 
Width: 9.26 

Print Location: Back 
Width: 3.92 

Logo Placement 
- Use exact measurements from above and place exactly where located in the preview images attached to this email

Let's give that a try but we need to see a visual proof that I will need to sign-off on before they print the entire run please as the logo sizes above are a guess.

**Comment by pstan26** [comment]
cool I put in the request for both hoodies and tees. will keep you posted

**Comment by guylepage3** [comment]
Nice!! 😄

**Comment by guylepage3** [comment]
Waiting for pricing on black version of t-shirts. Also, waiting on explanation as to why Amplifier printed the backs of the blue t-shirts before we signed off on them.

**Comment by guylepage3** [comment]
complete. closing issue.
