### ISSUE TITLE
Order more blockstack hoodies

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#127]
@guylepage3 commented on [Mon Oct 03 2016](https://github.com/blockstack/blockstack/issues/95)

@guylepage3 commented on [Thu Sep 22 2016](https://github.com/blockstack/community/issues/27)

Order more blockstack hoodies.
- [ ] Ping connectors to see if they want a blockstack hoodie

List of members wanting a hoodie:
- Qasar Younis (M)
- Albert Wenger (size?)
- Naval Ravikant (size?)

---

@guylepage3 commented on [Tue Nov 22 2016](https://github.com/blockstack/blockstack/issues/95#issuecomment-262270096)

@shea256 should we just reorder the same quantity/sizes of hoodies as we did on the last run?

---

@shea256 commented on [Tue Nov 22 2016](https://github.com/blockstack/blockstack/issues/95#issuecomment-262270348)

Yeah that's simple, we can always order again.

**Comment by pstan26** [comment]
As a reminder, we will need hoodies for the winners of the #DecentralizeTheWeb event. Sounds like we are ordering in bulk here, so that works out nicely.

**Comment by guylepage3** [comment]
Previous order:

```
Item Name: Blockstack hoodies 
Base SKU: Blockstack hoodies 
Category: apparel 
Type: Hoodies 
Style: American Apparel F497 
Color: Black 

Comments: 
Logo Placement 
- Use exact measurements from above and place exactly where located in the preview images already supplied. Preview images link is below.

Number of Colors: 1 
Print Location: Front 
Width: 4.54 
Height: 0.62

Number of Colors: 1 
Print Location: Back 
Width: 9.26 
Height: 1.26

SKU / Quantities: 
blockstack hoodie (size xs): 0 
blockstack hoodie (size s): 4 
blockstack hoodie (size m): 8 
blockstack hoodie (size l): 5 
blockstack hoodie (size xl): 1 
blockstack hoodie (size 2xl): 3

```

**Comment by pstan26** [comment]
Guessing this is the same vendor that does our t-shirts, right?

**Comment by guylepage3** [comment]
correct

**Comment by pstan26** [comment]
@guylepage3 same design for hoodies as we are doing for t-shirt (https://github.com/blockstack/designs/issues/126#issuecomment-282097950)? and do we want prints on front _and_ back, or just front?

**Comment by pstan26** [comment]
Ah reading description and seeing just front*

**Comment by guylepage3** [comment]
both front and back on the hoodie

**Comment by guylepage3** [comment]
Resent hoodie info to Rory at Amplifier. Waiting for another proof as they did not change the back logo to the vertical version.

**Comment by guylepage3** [comment]
closing issue
