### ISSUE TITLE
CLI command video tutorial title slide template

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#135]
Hi @guylepage3, @jcnelson and I will be creating short 30sec-2 min videos going over CLI commands. ~98% of the video will just be Jude doing a screencast and explaining what he is doing. Each video will have a title that briefly displays the command Jude will be going over.

There will be a dozen initial videos like this (which could be fully edited, if we wanted, as soon as Monday) and then many of the same exact type produced after.

Could we create a template for this title slide?

**Comment by pstan26** [comment]
Found this: https://www.winxdvd.com/resource/best-youtube-size-for-uploading.htm

We'd be doing this in at least 1080p, so dimensions could be:
1080p: 1920x1080 || 1440p (2k): 2560x1440 || 2160p (4k): 3840 x 2160

**Comment by guylepage3** [comment]
Why not take the YC approach and create one long video and then split them up after the fact? 

https://www.youtube.com/channel/UCcefcZRL2oaA_uBNeo5UOWg

**Comment by pstan26** [comment]
Plan is to do both.

**Comment by guylepage3** [comment]
Sorry. What I meant to suggest is that it's quite a bit less work and more consistent if the long video is done first as it takes up less time for @jcnelson and myself as well as yours.

**Comment by pstan26** [comment]
Yep, thats exactly what we are doing.

**Comment by pstan26** [comment]
We went through a dry run on Wednedsay

**Comment by pstan26** [comment]
Hey @guylepage3 as a friendly reminder, I will be spending part of this weekend putting together this the CLI Tutorial Video (long form and then segmented versions). 

If we are able to have Title Screen templates completed by Saturday morning, we will be able to launch some really nice CLI command tutorials on Monday morning for people to start learning the CLI :-)

**Comment by guylepage3** [comment]
@pstan26 shall we make this interactive?

**Comment by pstan26** [comment]
Surely doesn't need to be. That said, if it is easy for you and looks better than static titles I would not protest.

**Comment by guylepage3** [comment]
yeah it's pretty simple. adds an hour or so onto the work. maybe you and i should think of a very short interactive brand mark for it?

**Comment by pstan26** [comment]
Well thats cool.

Happy to take this offline, but for posterity:
One of the things I noticed with the four stereoscopic dots is that if you squint a bit they really come "off" the screen (its a thing that very few brands have accomplished). Maybe we can play with that in a way like one of the following?:


- subtley wiggling each dot in some random order to show "activity"
- subtely wiggling all dots
- dots swoop in from four screen corners
- dots enlarge and become normal sized again
- dots fly past you (similar to twitter's logo that flys toward you in their mobile app)

-background: if we are using the "networked" (I don't know the name for it yet) purple background image have an electrical pulse run through it.
-background: "networked" purple background image translates behind the logo, giving it the effect of a planet being traversed by blockstack logo

**Comment by guylepage3** [comment]
Nice! this is a great start. i will think about it throughout the day. you need this by tomorrow morning or afternoon?

**Comment by pstan26** [comment]
tmrw afternoon works -- thanks!

**Comment by guylepage3** [comment]
@pstan26 we can set the thumbnail in youtube for the videos. Which means we can choose a custom thumbnail and create a title screen for each video that the user will not see once they've clicked on the video. See below:

<img width="1316" alt="screenshot 2017-01-30 10 47 07" src="https://cloud.githubusercontent.com/assets/1711854/22429705/79ccc1d6-e6d9-11e6-9749-487d7b9387f0.png">

**Comment by guylepage3** [comment]
So if you want to get me a list of the titles for each screen I can create one for each. It will allow us to keep the brand cover tight

**Comment by pstan26** [comment]
Oh great!

0:25 Balance

1:04 Deposit

1:24 Ping

2:36 Import

3:25 Lookup

5:21 Whois

6:52 Info

9:01 Configure

19:55 Names

20:21 Price

22:32 Set_Advanced_mode

23:48 Migrate

25:29 Revoke

27:07 Renew

29:32 Update

34:24 Transfer

**Comment by guylepage3** [comment]
@pstan26 here's the title intro movie
- https://github.com/blockstack/designs/blob/master/brand/v3.0.0/support/video-title.mov

**Comment by guylepage3** [comment]
Let me add in the title quickly.
**"CLI Tutorial"**

**Comment by guylepage3** [comment]
@pstan26 here's the updated movie
https://github.com/blockstack/designs/blob/master/brand/v3.0.0/support/video-title.mov

**Comment by guylepage3** [comment]
Update 2 - https://github.com/blockstack/designs/blob/master/brand/v3.0.0/support/video-title2.mov

**Comment by guylepage3** [comment]
FINAL Video – https://github.com/blockstack/designs/blob/master/brand/v3.0.0/support/video-title4.mov

Screens...

![video-title_balance_00089](https://cloud.githubusercontent.com/assets/1711854/22446044/96be9ece-e718-11e6-8f73-e311d7f4d86b.png)
![video-title_configure_00089](https://cloud.githubusercontent.com/assets/1711854/22446049/96c52988-e718-11e6-826c-49485e48e296.png)
![video-title_deposit_00089](https://cloud.githubusercontent.com/assets/1711854/22446045/96c1c48c-e718-11e6-85c0-98f1a7c4ac2c.png)
![video-title_import_00089](https://cloud.githubusercontent.com/assets/1711854/22446046/96c1b582-e718-11e6-9bb7-887f45cd55d3.png)
![video-title_info_00089](https://cloud.githubusercontent.com/assets/1711854/22446048/96c22dfa-e718-11e6-8a2c-c3d866cd7024.png)
![video-title_lookup_00089](https://cloud.githubusercontent.com/assets/1711854/22446047/96c22c6a-e718-11e6-90f6-90c5b3c1e582.png)
![video-title_migrate_00089](https://cloud.githubusercontent.com/assets/1711854/22446050/96c6a2d6-e718-11e6-8524-57f0a4103c11.png)
![video-title_names_00089](https://cloud.githubusercontent.com/assets/1711854/22446051/96ca2a32-e718-11e6-8352-11de42860496.png)
![video-title_ping_00089](https://cloud.githubusercontent.com/assets/1711854/22446056/96cfda04-e718-11e6-95c3-25c67b4d7260.png)
![video-title_price_00089](https://cloud.githubusercontent.com/assets/1711854/22446052/96cdcc64-e718-11e6-9bb2-f787e5590c48.png)
![video-title_renew_00089](https://cloud.githubusercontent.com/assets/1711854/22446054/96ceac74-e718-11e6-9d17-ce4d5658812d.png)
![video-title_revoke_00089](https://cloud.githubusercontent.com/assets/1711854/22446053/96ce86fe-e718-11e6-9790-c0dadc65b9a0.png)
![video-title_set_advanced_mode_00089](https://cloud.githubusercontent.com/assets/1711854/22446055/96cec010-e718-11e6-8d30-f32fd66f8b14.png)
![video-title_transfer_00089](https://cloud.githubusercontent.com/assets/1711854/22446057/96d32d12-e718-11e6-99d4-15d9080493a0.png)
![video-title_update_00089](https://cloud.githubusercontent.com/assets/1711854/22446059/96db4da8-e718-11e6-9461-dd35d3733e7c.png)
![video-title_whois_00089](https://cloud.githubusercontent.com/assets/1711854/22446058/96d74bfe-e718-11e6-9d08-e4a1547e7a9e.png)

**Comment by guylepage3** [comment]
Let me know if you need anything further @pstan26. Can't wait to see these videos. 😄

**Comment by pstan26** [comment]
Looks beautiful, thank you Guy

**Comment by guylepage3** [comment]
One thing I was thinking about late last night was... Should each screen say something like...
```
[Blockstack logo] CLI — $update
```
instead of our current...
```
[Blockstack logo — $update
```

**Comment by pstan26** [comment]
Could do, and would be easy on my end to change... right now the Youtube Title follows this naming convention: 

Blockstack CLI Tutorial: $ configure

**Comment by guylepage3** [comment]
Looks really good on YouTube @pstan26 . 😄  Can't wait for these to head out the door. Maybe we should publish them as they are complete and then do one big announcement once they're all up?

Thoughts? 

cc: @shea256 @muneeb-ali @jcnelson

**Comment by pstan26** [comment]
Agreed, I think these can all go public now. Plan was make a full announcement (Slack, twitter, forum, github) once "migrate" is finalized.

**Comment by guylepage3** [comment]
Should

**Comment by pstan26** [comment]
And also do a Tutorial Tuesday sort of thing where we tweet one CLI command vid each Tuesday? I've already got it in my calendar :-)

**Comment by guylepage3** [comment]
I feel we should organize the [**Blockstack CLI Tutorial Series**](https://www.youtube.com/playlist?list=PLXS8JJHIn4nGCU2uW85dHXpkQJ7QA5JkX) in the order they appear in the CLI

<img width="873" alt="screenshot 2017-02-01 15 12 27" src="https://cloud.githubusercontent.com/assets/1711854/22524350/db0c8c16-e890-11e6-9319-ef1d8cd50f86.png">

**Comment by guylepage3** [comment]
One other thing I noticed as well, is that I would have loved to see **$ lookup werner.id** or Sir Tim Berners-Lee or someone of high profile. It's an opportunity for us to garner legitimacy. Every opportunity adds up.

https://www.youtube.com/watch?v=GWjEGlb1aEs&index=3&list=PLXS8JJHIn4nGCU2uW85dHXpkQJ7QA5JkX

**Comment by pstan26** [comment]
Putting vids in new order now. Yes would have been good to do have high profile folks in there, looking forward to next ones where we will have another opp to do that

**Comment by guylepage3** [comment]
Also, I would like to control the UI of the terminal on the next one as well so that it would look something like this.. 


<img width="1500" alt="screenshot 2017-02-01 15 22 30" src="https://cloud.githubusercontent.com/assets/1711854/22524901/17d9963c-e893-11e6-9b94-beaee0aa1128.png">

**Comment by pstan26** [comment]
To make it blue? Very hard to read if you choose not to make fullscreen.  

Also, will I have to wait to reorder these vids until I get "migrate" command since you can only move videos to top or bottom -- don't want to over-rotate on this and have to do the same thing again in a couple days.

**Comment by pstan26** [comment]
hey @guylepage3 ah sry, I need one more command screen title for a YouTube thumbnail: "$ register"  

Thanks in advance

**Comment by guylepage3** [comment]
@pstan26 here you go.

Closing this issue out. If you require more, please create a new issue and I'll schedule it in. Thx.

![video-title_register00089](https://cloud.githubusercontent.com/assets/1711854/22569124/5b955d3a-e964-11e6-8f89-a0450073009d.png)

**Comment by pstan26** [comment]
You got it, thank you sir!
