### ISSUE TITLE
twitter image template for #DecentralizeTheWeb Demo Day

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#136]
On Feb 16 we will be announcing all the submissions for #DecentralizeTheWeb via twitter and slack. I plan on capturing each project's **title** and **100 words** describing the app into little cards that will be uploaded on twitter and slack.

Would like to create a basic template for that if we could.

**Comment by guylepage3** [comment]
Nice. Yes. I'll change the title to reflect the task. :)

**Comment by pstan26** [comment]
Thank you!

**Comment by guylepage3** [comment]
What is the timing like for this?

**Comment by pstan26** [comment]
We would want to have it ready by February 13ish, Feb 15th is the absolute deadline for the template. (These series of tweets is going to completely own the news cycle for the day when it launches and get tens of thousands of impressions).

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #135](https://github.com/blockstack/blockstack/issues/135) via [**ZenHub**](https://www.zenhub.com/)
