### ISSUE TITLE
update blockstack meetup banner design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#145]
Design a new blcokstack meetup banner for all meetups

**Comment by guylepage3** [comment]
![meetup-banner-v2](https://cloud.githubusercontent.com/assets/1711854/22220053/30b2f8c0-e17b-11e6-996d-08a268a543d2.png)

**Comment by guylepage3** [comment]
@pstan26 can you apply the image above to all the blockstack meetups when you have a moment? Thank you.

**Comment by pstan26** [comment]
Yes, doing this afternoon. Feel free to close this out if you'd like. Again
looks beautiful meetup + blockstack together

**Comment by pstan26** [comment]
I'll need to be added as a co-organizer (not just assistant-organizer) to the following meetups higlight in this doc (https://docs.google.com/spreadsheets/d/1B6GM0g72WOjBGHYcb1tZQHU0GbJ2XCWuikrtaoKMznY/edit#gid=0) in order to apply the banner to all of them. Organizer of all these is @shea256

**Comment by guylepage3** [comment]
@pstan26 @shea256 Creating a new issue for uploading to all meetup groups.

See here: https://github.com/blockstack/designs/issues/153

@pstan26 please move your comments over to new issue. thanks.
