### ISSUE TITLE
Create 2:4(?) ratio twitter image for #DecentralizeTheWeb tweets

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#150]
If we wish to not rely on the eventbrite image being perfectly displayed in all subsequent tweets about the #DecentralizeTheWeb challenge, we would need a Twitter-specific image. Hashtag pixel-perfect hashtag guyisaperfectionist

**Comment by guylepage3** [comment]
I'll work on this this morning and add it to my list

**Comment by pstan26** [comment]
Thank you

**Comment by guylepage3** [comment]
@pstan26 here's the twitter image

![twitter-image-decentralizetheweb](https://cloud.githubusercontent.com/assets/1711854/22315709/69cfb316-e336-11e6-9c8d-d0e2b6cf9106.png)
