### ISSUE TITLE
blog banner image for blockstack auth blog post

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#152]
Design a blog post image for the blockstack auth blog post by @shea256

**Comment by guylepage3** [comment]
@shea256 what are you thinking for the blog post imagery?

Some ideas could be:
- [ ] imagery supporting the blockstack auth button (login with blockstack)
- [ ] a generic blockstack image symbolizing security / not being tracked
- [ ] standard blockstack background image with new blockstack auth logo

Thoughts?

**Comment by shea256** [comment]
How about we go with the third one and then use the first one for the new post announcing "login with blockstack"?

**Comment by guylepage3** [comment]
sounds good. 😄

**Comment by guylepage3** [comment]
@shea256 what do you think of this image for the blockstack auth post?

![blog-auth](https://cloud.githubusercontent.com/assets/1711854/22270541/123197ce-e25e-11e6-989f-a58fac9599d8.png)

**Comment by shea256** [comment]
@guylepage3 looks good to me, thanks!

**Comment by guylepage3** [comment]
closing issue. if you need to find it please see [brand-v3.0.0 publish list](https://github.com/blockstack/designs/issues/74)
