### ISSUE TITLE
Uploading new meetup banner to all blockstack meetup groups

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#153]
Upload new meetup banner to all blockstack meetup groups

**Groups**
https://www.meetup.com/topics/blockstack/

Graphics are here: https://github.com/blockstack/designs/issues/145

**Comment by pstan26** [comment]
In order to apply the banner to all of them, I'll need to be added as a co-organizer (not just assistant-organizer) to the following meetups highlighted in this doc: https://docs.google.com/spreadsheets/d/1B6GM0g72WOjBGHYcb1tZQHU0GbJ2XCWuikrtaoKMznY/edit#gid=0 . Organizer of all these is @shea256

**Comment by pstan26** [comment]
Complete
