### ISSUE TITLE
new meetup icon for blockstack newsletter

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#160]
Create a new meetup icon for the blockstack newsletter

**Comment by guylepage3** [comment]
@shea256 here's the new meetup icon for the newsletter

https://media.githubusercontent.com/media/blockstack/designs/master/newsletter/images/icon-meetup%402x.png

**Comment by shea256** [comment]
Great thanks @guylepage3!

**Comment by guylepage3** [comment]
closing issue
