### ISSUE TITLE
Twitter image for CLI Tutorial video announcement

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#176]
@guylepage3 Do we want to use a resized, tweet-optimized image for announcing the CLI Tutorial vids?

**Comment by guylepage3** [comment]
we should create an image for it. what do you want it to say?

**Comment by pstan26** [comment]
"Blockstack Command Line Video Tutorial" sounds simple and easy to get.

alt: "Blockstack CLI Video Tutorial"
alt: "Video Tutorial for the Blockstack Command Line Interface"

**Comment by guylepage3** [comment]
@pstan26 can i get access to one of the video tutorials so that I may get an idea for this image? Thank you sir. 😄

**Comment by pstan26** [comment]
Here is the series: 
https://www.youtube.com/playlist?list=PLXS8JJHIn4nGCU2uW85dHXpkQJ7QA5JkX

**Comment by pstan26** [comment]
I'm still on the fence as to whether we should choose to do a series of tweets, on for each command. Plus side is that our twitter community sees progress and have the tutorials spoon fed to them, minus is it might be overwhelming. That said, I kind of like the idea of hooking someone in that way, and we can space these out on a schedule....it doesn't have to be all in one day.

**Comment by guylepage3** [comment]
Issue moved to [blockstack/blockstack #138](https://github.com/blockstack/blockstack/issues/138) via [**ZenHub**](https://www.zenhub.com/)

**Comment by guylepage3** [comment]
@pstan26 answered here: https://github.com/blockstack/designs/issues/135#issuecomment-276764001

**Comment by guylepage3** [comment]
@pstan26 here are two choices for the twitter image. Please let me know which one you like best. cc: @shea256, @muneeb-ali, @larrysalibra 

twitter-image-cli-tutorial-1

![twitter-image-cli-tutorial-1](https://cloud.githubusercontent.com/assets/1711854/22566860/9cd63ec6-e95b-11e6-9ec5-40ba222819ea.png)

twitter-image-cli-tutorial-2

![twitter-image-cli-tutorial-2](https://cloud.githubusercontent.com/assets/1711854/22566859/9cd59e44-e95b-11e6-80c2-efd85cff50f2.png)

**Comment by pstan26** [comment]
@guylepage3 really like the first one because it features timblee.id and you already start learning from just looking at it

**Comment by guylepage3** [comment]
@pstan26 feel free to use the one above. I'm closing out this issue.
