### ISSUE TITLE
Create "Hello World" title slide for video tutorial

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#187]
Hey @guylepage3 similar to how we made the CLI Tutorial video titles, we need one for an upcoming "Hello, World/Blockstack" video tutorial @shea256 will be recording 2/15.

Since this is special, perhaps we could use that nice animated video title.

Suggested Title copy: BLOCKSTACK    "Hello, World!" App Tutorial

**Comment by pstan26** [comment]
Happy Monday @guylepage3! Friendly reminder that @shea256 and I will be recording a video for this on Wednesday which I'd like to release on Thursday 2/16 this week. Perhaps a static slide is fine.

Suggested title slide:

**Blockstack: Hello World Tutorial**

**Comment by guylepage3** [comment]
@pstan26 working on this now...

**Comment by guylepage3** [comment]
Animation ideas:
- fade blockstack gradient in from black, atlas grid weaves into position as the "hello blockstack" icon drops down from the top of the screen and bounces into place.

**Comment by guylepage3** [comment]
Ok @pstan26 let me know what you think of this intro.. we may want to change the background.. I don't know. this was a quick and dirty animation.

https://github.com/blockstack/designs/blob/master/video/hello-world-tutorial/hello-blockstack-tutorial-video-title.mov

**Comment by pstan26** [comment]
@guylepage3 someday you'll have to teach me how you do this, this looks damn good! Excited to post it this week!

**Comment by guylepage3** [comment]
@pstan26 I spent 3 years in advertising and design building out intro's for documentaries, TV serires and TV commercials. Adobe After Effects has a learning curve but if you understand timelines and can do a bit of javascript magic, i could teach you over a weekend.

**Comment by pstan26** [comment]
Sweet, yea the animation really draws you in. I could be down for that if
you're in the office some weekend coming up! We can chat offline perhaps
about it.

**Comment by pstan26** [comment]
Hello @guylepage3 I'm now in editing the Hello Blockstack video, should be completed by this evening. Could you included an updated intro video animation that uses the new app design (attached)? For something "quick and dirty", what you submitted earlier was pretty good -- do you think we should include the word `tutorial` in the intro video or just leave it in the description?

![screen shot 2017-03-23 at 5 39 13 pm](https://cloud.githubusercontent.com/assets/5605552/24271515/cf5bcdba-0fef-11e7-98d0-db8d302e9f10.png)
?

**Comment by guylepage3** [comment]
@pstan26 for sure. when are you wanting to push this out the door?

**Comment by pstan26** [comment]
Good question, totally depends on when the "Hello Blockstack" Blog post goes up  -- feels like as soon as next tuesday or as late as the tuesday following next. Issue here: https://github.com/blockstack/blockstack/issues/249

**Comment by guylepage3** [comment]
Ahh yeah.. I see @pstan26. I'll update this now.. Thanks for letting me know about this one.

**Comment by guylepage3** [comment]
@pstan26 here's the new movie intro..

https://github.com/blockstack/designs/blob/master/video/hello-world-tutorial/hello-blockstack-tutorial-video-title-tilt.mov

**Comment by pstan26** [comment]
Looks fantastic -- thank you
