### ISSUE TITLE
Create CLI "install" video title slide 

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#194]
Hi @guylepage3, Jude and I just completed recording the CLI tutorial for "install". It is not a command function (no need for "$") so perhaps we create a title like:

       Install Blockstack CLI
       Installing the Blockstack CLI

**Comment by guylepage3** [comment]
actually it is a command..

```
$ pip install blockstack
```

unless this has changed. cc: @jcnelson

**Comment by pstan26** [comment]
Ok, what I'm saying it does it make sense, given the context, to have a "$" in front of it rather than a description? Doesn't matter to me as long as people don't get confused

**Comment by guylepage3** [comment]
![video-title_install_00089](https://cloud.githubusercontent.com/assets/1711854/23040682/327e5292-f460-11e6-9d2d-b5f99766b7b7.png)
