### ISSUE TITLE
Create 480x480 Blockstack logo for 21co

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#197]
Hi @guylepage3, 21 is nearly done creating our task and is now requesting a 480x480 Blockstack Logo.

They said anything in SVG or Illustrator would be great.

Thanks in advance

**Comment by guylepage3** [comment]
@pstan26 where will this logo be placed and how will it be used so that I can provide the proper logo. Thx

**Comment by pstan26** [comment]
It would be in the banner image of the task... unclear how that ends up being a square. this may be their first time adding a logo AFAIK so I don't know if there exist any example. LMK if you need more deets

![screen shot 2017-02-16 at 4 17 58 pm](https://cloud.githubusercontent.com/assets/5605552/23041635/8b2591be-f463-11e6-8122-984b177d5acf.png)

**Comment by pstan26** [comment]
Sending a screenshot momentarily

**Comment by pstan26** [comment]
Looks like there is also a banner image. They got confused.. so the 400x400 is the icon (THIS TASK), and I'll create a new task for the banner image here: https://github.com/blockstack/designs/issues/198

![screen shot 2017-02-16 at 4 23 51 pm](https://cloud.githubusercontent.com/assets/5605552/23041829/5c578120-f464-11e6-94a1-930f76ff24ac.png)

**Comment by guylepage3** [comment]
@pstan26 Here's the required logo for 21.co

![blockstack-bug-squared-480x480](https://cloud.githubusercontent.com/assets/1711854/23480432/deff33d0-fe95-11e6-9d75-834c059468a4.png)

**Comment by guylepage3** [comment]
closing issue
