### ISSUE TITLE
design new blockstack stickers

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#199]
design new blockstack stickers

**Comment by pstan26** [comment]
Imagine we could use these for the recent #DecentralizeTheWeb event correct?

**Comment by pstan26** [comment]
@guylepage3 we will need these designed by next Monday 5/1.

Per our convo, 2 designs: 1 large bug image, and one horizontal likely with the bug on left.

**Comment by guylepage3** [comment]
@pstan26 yeah. i think the bug and horizontal will work best. i'll create a custom dieline for it and upload it to our sticker mule account and provide you with access.

**Comment by pstan26** [comment]
beautiful thanks!

**Comment by pstan26** [comment]
I know this is top of mind, but we will need to put this order in this week @guylepage3

**Comment by guylepage3** [comment]
Yeah. Larry, Ryan and I determined that today is the day i finalize all the small design tasks. You'll have something for tomorrow morning. 😄

**Comment by guylepage3** [comment]
thank you for the reminder sir. 😉

**Comment by guylepage3** [comment]
working on this now

**Comment by pstan26** [comment]
Great! Thanks dude

**Comment by guylepage3** [comment]
![blockstack-sticker-comps](https://cloud.githubusercontent.com/assets/1711854/25760789/67dddc36-31a6-11e7-998e-74782bc2f4c9.png)

**Comment by guylepage3** [comment]
Ok.. so back to the stickers... here's an explanation for why i feel we should go with all three as it will only cost us an additional $200 for a whack load of brand loyalty value...

[5:52] 
New Blockstack Sticker designs. There are 3 new designs ranging in sizing and shape for various usage.

1. Is a small version of the Blockstack bug that allows for repetition on the brand even in the smallest places and allows us to visually identify who is loyal to the brand.

2. The Blockstack landscape logo is the traditional and most widely used logo allows for simple placement for those looking to place the logo in a vertically challenged area.

3. The vertical logo allows for simple placement in a square format.

![blockstack-sticker-comps](https://cloud.githubusercontent.com/assets/1711854/25765580/c2a45c0c-31bb-11e7-9bec-2893852ad81c.png)

**Comment by pstan26** [comment]
Agree with reasoning and design. Two thumbs up.

**Comment by shea256** [comment]
+1

**Comment by guylepage3** [comment]
Working on printer ready files now..

**Comment by guylepage3** [comment]
design complete. pinning print production issue [#257: print production for blockstack stickers](https://github.com/blockstack/designs/issues/257)
