### ISSUE TITLE
build html email template for feature posts

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#201]
Build html email template for feature posts

**Comment by guylepage3** [comment]
Reference: [html email for block explorer blog post](https://github.com/blockstack/blockstack/issues/217)

**Comment by pstan26** [comment]
Hey @guylepage3 did we previously decide to limit the body to 250 character count or is this a new thing?

Current copy is ~567 characters and looks like this:
![screen shot 2017-02-17 at 10 34 36 am](https://cloud.githubusercontent.com/assets/5605552/23071657/1a881a90-f4fd-11e6-8b13-28cb6dccfa4e.png)

Happy to work to cut it down, but want to explain what it is, too.

**Comment by guylepage3** [comment]
Yeah. As decided, there shouldn't be a character limit for the featured emails.

**Comment by guylepage3** [comment]
Here's a visual of the email template for reference

<img width="610" alt="screenshot 2017-02-17 10 58 55" src="https://cloud.githubusercontent.com/assets/1711854/23073031/13f19698-f502-11e6-9b1a-6005438a6302.png">

**Comment by guylepage3** [comment]
complete.
