### ISSUE TITLE
build new non-stereoscopy blockstack logo and bug

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#206]
Build new non-stereoscopy blockstack logo and bug

**Comment by guylepage3** [comment]
Pinning [blockstack t-shirts](https://github.com/blockstack/designs/issues/126) to this issue

**Comment by guylepage3** [comment]
complete.

Download here:
- https://github.com/blockstack/designs/blob/master/brand/v3.0.0/logo/blockstack-logo-landscape-wo-rev.svg.zip

**Comment by pstan26** [comment]
@guylepage3 I can't open the above link to grab the logo, can you make it active or send me it again? thanks!

**Comment by guylepage3** [comment]
https://github.com/blockstack/designs/blob/master/brand/v3.0.0/logo/blockstack-logo-landscape-rev.svg.zip
