### ISSUE TITLE
Blockstack Academy Logo

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#238]
Hey @guylepage3 just need a simple logo so I can add it to a sketch file for the Blockstack Academy Series. Will show you sketch file once done. Would love to begin launching a video per day starting Monday leading up to Consensus :-)

could be as simple as a grad cap or a simple crest

**Comment by pstan26** [comment]
@guylepage3 if you're able to send me a simple logo by Saturday I can launch Blockstack Academy on Monday and have content for every day of the next month. lmk if you need more time or if you think this is doable.

**Comment by guylepage3** [comment]
sure. do you need an video intro as well?

**Comment by pstan26** [comment]
You got it, @guylepage3 

I would like an intro video, especially if it was ~1-2 seconds since people are going to watch many of these in a row. 

Although it is not compulsory, priority is the logo/title screen -- I can do a quick fade in/out of that screen. 

I'll begin putting these videos together on Saturday at 2pm.

**Comment by guylepage3** [comment]
working on this now

**Comment by guylepage3** [comment]
created a video intro issue here: 
- [#240: blockstack academy video intro](https://github.com/blockstack/designs/issues/240)

**Comment by guylepage3** [comment]
![blockstack-academy-logo-rev 2x](https://cloud.githubusercontent.com/assets/1711854/25057577/21a04ff0-213f-11e7-928e-42727175105a.png)
