### ISSUE TITLE
blockstack cam cover design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#251]
Need to design work on the following custom Blockstack cam covers for before consensus 2017.

**Template**
https://www.webcamcover.com/copy-of-art-templates-1-0-webcam-co

**Comment by guylepage3** [comment]
@pstan26 waiting for Ella to get back to me on this. Need to know which of the four templates we are to use.

**Comment by pstan26** [comment]
@guylepage3 I think we use the first two templates to build on and can borrow design elements from the bottom "standard card". For example, we can pretty much use the exact same "Back 4x6 standard card" that they use, and perhaps just switch our logos on the "Front 4x6 standard card"  and switch "now they SEE you...after they won't" to something like "start building on the decentralized internet at blockstack.org"

For the Biz Card template I'm a little unclear why it also has an open and close window...I'll ping ella about with card the swivel cover will live on.

**Comment by pstan26** [comment]
Update: she responded.

_Hi Guy.
 
Pricing includes the 4 x 6 card which is the first on the left.
Please let me know if you need my help.
 
Best regards,
 
Ella Jorge
SolPals, LLC dba C-SLIDE
OF: (801)758-7255 ext. 108
DIRECT: (385)-352-3555
FX: (801)618-2696
1192 Draper Parkway Suite 202 Draper, UT 84020
PROFILES: facebook twitter youtbue
ella@webcamcover.com
www.webcamcover.com_

**Comment by guylepage3** [comment]
cool. on it.

**Comment by guylepage3** [comment]
From Slack:

@pstan26  are you aware that the cam cover size is huge?

Ahhh.. i see what this is

it's an ad in the size of a business card with a cam cover as a takeaway

got it

are we going with the square cam cover?

I really don't like it. probably won't use it myself. that's a bad sign

will wait for your response before moving forward

**Comment by guylepage3** [comment]
Also, what do you want to say on the ad area of the business card?

**Comment by pstan26** [comment]
@guylepage3  To be clear, pricing includes the 4 x 6 card (attached), not the Biz Card.

![screen shot 2017-04-27 at 5 19 54 pm](https://cloud.githubusercontent.com/assets/5605552/25504945/cf9b0d60-2b6d-11e7-8de1-67c6cd9a2ea2.png)

Can you point to me the ad area you are mentioning so I can help? Is it the "now they See you..." section or the "Anyone can watch or record you" section?

**Comment by guylepage3** [comment]
Here's the template she is providing which is a business card with a perforation where the cam cover is so the user can pop out the cam cover

<img width="708" alt="screenshot 2017-04-27 17 24 58" src="https://cloud.githubusercontent.com/assets/1711854/25505117/761cb742-2b6e-11e7-9f21-ccebefe5f5e1.png">

**Comment by pstan26** [comment]
Coming to you in person to discuss.

**Comment by pstan26** [comment]
Great, ok @guylepage3 it sounded like we are just going to do the front side and no backside.

_Front-Copy:_

Reclaim your privacy with a Blockstack Webcam Cover!

Installation:
1.  Remove Adhesive tab from magnet
2.  Place magnet next to camera lens and press firmly (reminder: the open hole is for you finger not the camera)
3. Place swivel on magnet
4. Swivel to open and close

Build on the decentralized internet by visiting blockstack.org

<<Blockstack Logo>>

**Comment by guylepage3** [comment]
![bsk-cam-cover-1](https://cloud.githubusercontent.com/assets/1711854/25507250/e164c6c0-2b78-11e7-9000-31e818c23978.png)
![bsk-cam-cover-2-dieline](https://cloud.githubusercontent.com/assets/1711854/25507251/e16542da-2b78-11e7-84b0-2ecc34a95f3b.png)

**Comment by guylepage3** [comment]
Complete.

[bsk-cam-cover.ai.zip](https://github.com/blockstack/designs/files/963080/bsk-cam-cover.ai.zip)

**Comment by guylepage3** [comment]
@pstan26 i updated the zipped file. please use the one called "bsk-cam-cover-final.ai.zip". Thanks

**Comment by pstan26** [comment]
ah was just msging thank!

**Comment by pstan26** [comment]
@guylepage3  it is looking like this, is that correct? Also they reccommend the area within the green dots to be white for whatever reason.
![screen shot 2017-04-27 at 6 50 38 pm](https://cloud.githubusercontent.com/assets/5605552/25507555/aebcfc5e-2b7a-11e7-9e9a-6150c0f2b92f.png)

**Comment by guylepage3** [comment]
The vector file is in the zip file.

**Comment by shea256** [comment]
A few quick things:

1. The period right before the > looks strange.
2. "A Blockstack cam cover" should only have Blockstack capitalized
3. "adhesive" shouldn't be capitalized

**Comment by shea256** [comment]
" the open hole is for you finger not the camera"

"you" should be "your"

Gotta double and triple check the copy 🙏🏻

**Comment by guylepage3** [comment]
@shea256 updating now.

**Comment by guylepage3** [comment]
>"A Blockstack cam cover" should only have Blockstack capitalized

It is capitalized.

**Comment by guylepage3** [comment]
Here's the new version and it's zip file @pstan26 

Zip - 
[bsk-cam-cover-final2.ai.zip](https://github.com/blockstack/designs/files/964805/bsk-cam-cover-final2.ai.zip)


![bsk-cam-cover-final2-1](https://cloud.githubusercontent.com/assets/1711854/25535770/42db0bac-2c06-11e7-95f3-3fb13b81fa15.png)
![bsk-cam-cover-final2-2-diecut](https://cloud.githubusercontent.com/assets/1711854/25535771/42e512b4-2c06-11e7-966f-ecdf66ea943b.png)

**Comment by larrysalibra** [comment]
@guylepage3 ryan's saying "webcam" and "cover" shouldn't be capitalized.

**Comment by guylepage3** [comment]
@pstan26 here's the final final for the promo card.

.zip – 
[bsk-cam-cover-final2-outlined.ai.zip](https://github.com/blockstack/designs/files/964810/bsk-cam-cover-final2-outlined.ai.zip)


![bsk-cam-cover-final2-1](https://cloud.githubusercontent.com/assets/1711854/25535978/f4915aa4-2c06-11e7-93b6-8a1e8f15b9d7.png)
![bsk-cam-cover-final2-2-diecut](https://cloud.githubusercontent.com/assets/1711854/25535979/f49348dc-2c06-11e7-8ee4-769dbce1d4a0.png)

**Comment by pstan26** [comment]
Great, I also just repinged Ella.

**Comment by guylepage3** [comment]
v3 version of the camcover promo card

![bsk-cam-cover-final3-1](https://cloud.githubusercontent.com/assets/1711854/25713498/e2e6fb04-30c2-11e7-8d50-01424842d0a6.png)
![bsk-cam-cover-final3-2](https://cloud.githubusercontent.com/assets/1711854/25713499/e382ddb2-30c2-11e7-9699-a1a082000772.png)

**Comment by guylepage3** [comment]
Waiting to see latest version of the cam cover logos (x2) as well as camcover promo card v3
