### ISSUE TITLE
update design of blockstack email template v

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#281]
Update design of blockstack email template. 

Based upon the blockstack academy being sent out.

**Comment by guylepage3** [comment]
![newsletter-v5 2x](https://cloud.githubusercontent.com/assets/1711854/26698563/7619dcb6-46e4-11e7-970c-ac5bb27849f7.png)

**Comment by guylepage3** [comment]
@pstan26 so, i'm thinking for simplicity. let's just use the blocsktack template. i've updated the design to be a bit cleaner.

Will apply build now

**Comment by pstan26** [comment]
Thinking it works! Will put together email  to be sent out as soon as your done! thanks

**Comment by guylepage3** [comment]
cool

**Comment by pstan26** [comment]
![screen shot 2017-06-01 at 6 00 21 pm](https://cloud.githubusercontent.com/assets/5605552/26702778/89db5eae-46f4-11e7-94e0-a91285d493ea.png)
![screen shot 2017-06-01 at 6 01 01 pm](https://cloud.githubusercontent.com/assets/5605552/26702777/89da511c-46f4-11e7-9a80-7b46e25e9313.png)

**Comment by guylepage3** [comment]
@pstan26 here's the template.

Process to change template;
- replace bitmap image. Layer name `Bitmap (to be replaced)`
- change name of artboard. Artboard name `blockstack-academy-newsletter-img01`
- click "Export blockstack-academy..." in the bottom right corner

[blockstack-academy-newsletter-template.sketch.zip](https://github.com/blockstack/designs/files/1046190/blockstack-academy-newsletter-template.sketch.zip)

**Comment by guylepage3** [comment]
Here's the first exported image
![blockstack-academy-newsletter-img01](https://cloud.githubusercontent.com/assets/1711854/26703405/77218fb0-46f7-11e7-9812-d6d563abadb7.png)
