### ISSUE TITLE
blockstack logo v3.1

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#287]
## Blockstack Logo v3.1
The new Blockstack 4 dot logo has been well received. But as we know, we can do better and make the brand/logo stronger.

There have been some issues with this light, airy but modern looking logo. The following is an overview of design issues, solutions and design definitions explaining why and how we came to the design conclusions we did for the introduction of the Blockstack logo v2.1. 

We have recently decided to change the brand fundamentals slightly when it comes to having the logo appear only in reverse over a dark background. This was a design challenge with the logo that we were going to solve down the road. That time has come as the non-reversed version of the logo does not pop when appearing on it's own. This is an issue when handing off the logo to third parties or utilizing a lighter background in the brand.

This became very evident when we were about to [#199: design new blockstack stickers](https://github.com/blockstack/designs/issues/199). There was a design challenge that needed to be overcome and that resulted in the introduction to of the rounded corner app icon bug. The introduction of the Bug to both the vertical and the horizontal logo when appearing over a light background resolved the design challenges/issues 1, 2 & 3.

**Logo design issues;**
1. The logo gets lost when appearing beside many other logos
2. The logo does not work in certain circumstances such as light backgrounds or when whitespace is scarce
3. The stereoscopy on the four dots does not work as well on a lighter background

**Logo design solutions**
1. When the Blockstack logo is to appear on lighter backgrounds next to other logos or for 3rd parties wanting to display the Blockstack logo, introduced the blockstack "bug" and adding more weight to the logo type we were able to provide more pop to the logo in a subtle manner. This allowed the Blockstack logo to not get lost amongst some of the gaudy bold logos that are so prevalent in our industry.
2. By adding the bug we were resolving issue no. 2 as well. We applied this design technique to both the vertical and the horizontal logo and it assisted with adding pop to the logo on lighter backgrounds.
3. In addition, the bug resolves issue no. 3 by allowing the four dots to always appear on the chosen Blockstack purple background.

Also, by executing the logo in this manner we were able to provide the feeling that Blockstack is for Apps. The bug is in a shape like an app icon.

**Comment by guylepage3** [comment]
Pinning old v3.0 logo [#53: revisit: blockstack bug/logo design v3.0](https://github.com/blockstack/designs/issues/53)

**Comment by guylepage3** [comment]
Applied the heavier weight to the logo type for the blockstack vertical logo

<img width="425" alt="screenshot 2017-06-20 16 10 27" src="https://user-images.githubusercontent.com/1711854/27353759-302dc58e-55d3-11e7-9d10-8ed36067b14d.png">

**Comment by guylepage3** [comment]
@shea256 so there is a bit of an issue with the logo that I have been working on in my mind and testing out here and there over the past 2 months or so with the logo.

As stated above there are some issues with the logo that we have recognized.

Here are some logo v3.1 solutions. Let me know your thoughts.

**Solution - 1**
<img width="425" alt="screenshot 2017-06-20 16 10 27" src="https://user-images.githubusercontent.com/1711854/27353759-302dc58e-55d3-11e7-9d10-8ed36067b14d.png">

**Solution - 2**
<img width="855" alt="screenshot 2017-06-26 15 57 14" src="https://user-images.githubusercontent.com/1711854/27557587-26cb1d2a-5a88-11e7-9dd7-43f28175f02c.png">

**Comment by shea256** [comment]
I actually really like solution 2.

**Comment by guylepage3** [comment]
@shea256 i just added comments.

**Comment by guylepage3** [comment]
## Full logo production

### RGB - External usage

#### Logo
- [ ] blockstack-logo-landscape-bug.png
- [ ] blockstack-logo-landscape-bug.svg
- [ ] blockstack-logo-landscape-rev.png
- [ ] blockstack-logo-landscape-rev.svg
- [ ] blockstack-logo-vertical-bug.png
- [ ] blockstack-logo-vertical-bug.svg
- [ ] blockstack-logo-vertical-rev.png
- [ ] blockstack-logo-vertical-rev.svg

#### Bug
- [ ] blockstack-bug-rounded.png
- [ ] blockstack-bug-rounded.svg

#### Flat
- [ ] blockstack-logo-landscape-flat-rev.png
- [ ] blockstack-logo-landscape-flat-rev.svg
- [ ] blockstack-logo-landscape-flat.png
- [ ] blockstack-logo-landscape-flat.svg
- [ ] blockstack-logo-vertical-flat-rev.png
- [ ] blockstack-logo-vertical-flat-rev.svg
- [ ] blockstack-logo-vertical-flat.png
- [ ] blockstack-logo-vertical-flat.svg


----

### RGB — Internal usage

#### Logo
- [ ] logo/RGB/logo/blockstack-logo-landscape-rev.png
- [ ] logo/RGB/logo/blockstack-logo-landscape-rev.svg
- [ ] logo/RGB/logo/blockstack-logo-landscape.png
- [ ] logo/RGB/logo/blockstack-logo-landscape.svg
- [ ] logo/RGB/logo/blockstack-logo-vertical-rev.png
- [ ] logo/RGB/logo/blockstack-logo-vertical-rev.svg
- [ ] logo/RGB/logo/blockstack-logo-vertical.png
- [ ] logo/RGB/logo/blockstack-logo-vertical.svg

#### Bug
- [ ] logo/RGB/bug/blockstack-bug-rounded.png
- [ ] logo/RGB/bug/blockstack-bug-rounded.svg
- [ ] logo/RGB/bug/blockstack-bug-squared.png
- [ ] logo/RGB/bug/blockstack-bug-squared.svg

#### Flat
- [ ] logo/RGB/flat/blockstack-logo-landscape-flat-rev.png
- [ ] logo/RGB/flat/blockstack-logo-landscape-flat-rev.svg
- [ ] logo/RGB/flat/blockstack-logo-landscape-flat.png
- [ ] logo/RGB/flat/blockstack-logo-landscape-flat.svg
- [ ] logo/RGB/flat/blockstack-logo-vertical-flat-rev.png
- [ ] logo/RGB/flat/blockstack-logo-vertical-flat-rev.svg
- [ ] logo/RGB/flat/blockstack-logo-vertical-flat.png
- [ ] logo/RGB/flat/blockstack-logo-vertical-flat.svg

#### Stickers
- [ ] logo/RGB/stickers/blockstack-sticker-landscape.png
- [ ] logo/RGB/stickers/blockstack-sticker-landscape.svg
- [ ] logo/RGB/stickers/blockstack-sticker-vertical.png
- [ ] logo/RGB/stickers/blockstack-sticker-vertical.svg
- [ ] logo/RGB/stickers/blockstack-sticker-bug-rounded.png
- [ ] logo/RGB/stickers/blockstack-sticker-bug-rounded.svg

### BW (Black & White / Grayscale) — Internal usage 

#### Logo
- [ ] logo/BW/logo/blockstack-logo-bw-landscape-rev.png
- [ ] logo/BW/logo/blockstack-logo-bw-landscape-rev.svg
- [ ] logo/BW/logo/blockstack-logo-bw-landscape.png
- [ ] logo/BW/logo/blockstack-logo-bw-landscape.svg
- [ ] logo/BW/logo/blockstack-logo-bw-vertical-rev.png
- [ ] logo/BW/logo/blockstack-logo-bw-vertical-rev.svg
- [ ] logo/BW/logo/blockstack-logo-bw-vertical.png
- [ ] logo/BW/logo/blockstack-logo-bw-vertical.svg

#### Bug
- [ ] logo/BW/bug/blockstack-bug-bw-rounded.png
- [ ] logo/BW/bug/blockstack-bug-bw-rounded.svg
- [ ] logo/BW/bug/blockstack-bug-bw-squared.png
- [ ] logo/BW/bug/blockstack-bug-bw-squared.svg

**Comment by guylepage3** [comment]
complete.
