### ISSUE TITLE
new context conference presentation deck (keynote)

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#29]
Update **New Context Conference** keynote presentation deck with latest branding, content and imagery.

**Presentation Title**
>Fostering Innovation and Economic Inclusion with Decentralized Applications

Tasks:
- [x] apply new blockstack atlas grid illustration
- [ ] remove font error
- [x] review all font sizes
- [x] review footer (if applicable)
- [x] ensure all social links are visible
- [x] ensure deck has a material date and description https://github.com/blockstack/designs/issues/10

ensure all browser pages have the following:
- [x] blockstack purple background as globe image becomes washed out in video recording
- [ ] browser is the blockstack browser

**Comment by guylepage3** [comment]
complete for this deck. 
* rethinking the browser header. will adjust in next iteration.
* still having an issue finding that font.

**Comment by guylepage3** [comment]
Current fonts
[Source_Code_Pro.zip](https://github.com/blockstack/designs/files/572473/Source_Code_Pro.zip)
[Lato.zip](https://github.com/blockstack/designs/files/572474/Lato.zip)

**Comment by guylepage3** [comment]
@shea256 when you have a moment can you copy and paste the code used in your last presentation? Then I'll update the final deck and upload it to talks. Thank you.

**Comment by shea256** [comment]
@guylepage3 sure thing, here it is:

```javascript
import blockstack from "blockstack"
let user = blockstack.loginUser()
user.get("photos")
user.put("photos", [photo])
```

To match the editor code highlighting rules here are some guidelines...

- The words "import", "from" and "user" should all be the same color.
- The words "blockstack" and both instances of "photos" should be another color.
- The other words can be the default color.

**Comment by guylepage3** [comment]
Closed with merge https://github.com/blockstack/designs/pull/39
