### ISSUE TITLE
Community contribution issues

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#293]
### Community contribution issues

1. No real definition of how to contribute
2. No design process
3. Undefined or not so strong Brand guide / Brand fundamentals definition

#### Community contribution issue solution
1. Create a “how to contribute” guide
  1. blockstack.org
  2. design
  3. browser
2. Having a design process will allow for the community to better contribute to the design repository and streamline the design lead’s role
3. Define brand fundamentals (100%) and brand elements 80% complete brand guide (20% to be iterated to completion)

The above was developed from
- https://paper.dropbox.com/doc/Brand-design-and-UI-issues-n4BwkOA0KDVqi3Mzx6HNZ

**Comment by estermer** [comment]
I am currently reviewing and putting together the guidelines for this repo and others.

A couple things that need to be different from the previous guidelines to the this one:

1. I need to know if there are any other maintainers for designs other than @guylepage3 

2. If there are then do we want to have open source contributors merge into base designs and allow for a double review process to be merged into master?

**Comment by guylepage3** [comment]
1. No. just myself so far

**Comment by estermer** [comment]
ok cool so they can just pr to master then.

**Comment by guylepage3** [comment]
no. they should do their pr's from the `design` branch.

**Comment by estermer** [comment]
@guylepage3 could you provide for me a list of maintainers for each repo that we are going to add contribution guidelines to?

**Comment by guylepage3** [comment]
@estermer here's the list

| Repository        | Maintainer  |
| ------------- |:-------------:|
| [designs](https://github.com/blockstack/designs/)      | @guylepage3 |
| [blockstack.org](https://github.com/blockstack/blockstack.org/)      | @guylepage3, @shea256       |
| [blockstack-app-generator](https://github.com/blockstack/blockstack-app-generator/) | @larrysalibra, @shea256   |
| [blockstack.js](https://github.com/blockstack/blockstack.js)      | @larrysalibra, @shea256  |
| [blockstack-core](https://github.com/blockstack/blockstack-core)      | @jcnelson, @kantai, @muneeb-ali  |
| [blockstack-browser](https://github.com/blockstack/blockstack)      | @guylepage3, @larrysalibra  |
| [blockstack-explorer](https://github.com/blockstack/blockstack)      | @larrysalibra, @guylepage3 |
| [blockstack](https://github.com/blockstack/blockstack)      | @muneeb-ali, @guylepage3  |

**Comment by guylepage3** [comment]
@estermer i'm closing out this issue and creating a new one as quite a few things have changed since we started working on the guidelines.

Moved here... https://github.com/blockstack/designs/issues/395
