### ISSUE TITLE
summit eventbrite speakers image design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#298]
Blockstack Summit 2017 eventbrite speakers image design

**Comment by guylepage3** [comment]
Naval image
![aug 2016 headshot](https://user-images.githubusercontent.com/1711854/27198785-a9b76298-51e1-11e7-8e8a-4d154b9c0122.jpg)

**Comment by guylepage3** [comment]
Albert image
![wenger](https://user-images.githubusercontent.com/1711854/27198799-be66152c-51e1-11e7-9f68-64b54940f8dd.png)

**Comment by guylepage3** [comment]
Balaji image
![balaji14](https://user-images.githubusercontent.com/1711854/27199079-bcf7e70a-51e2-11e7-8713-df1aa5a950a7.jpg)

**Comment by guylepage3** [comment]
Nick image
![szabo](https://user-images.githubusercontent.com/1711854/27199091-c9847d62-51e2-11e7-8ff4-6b71c5990946.jpg)

**Comment by guylepage3** [comment]
Garry image
![screen shot 2017-06-15 at 3 56 04 pm](https://user-images.githubusercontent.com/1711854/27199345-a8b4242e-51e3-11e7-91ad-4d2b8322fe75.png)

**Comment by guylepage3** [comment]
![eventbrite-speakers-01](https://user-images.githubusercontent.com/1711854/27204438-361ff10c-51f9-11e7-827a-911de848f64a.png)

**Comment by guylepage3** [comment]
![eventbrite-speakers-02](https://user-images.githubusercontent.com/1711854/27204527-b8f30a88-51f9-11e7-9793-e34e9ad7cc45.png)

**Comment by guylepage3** [comment]
@pstan26 here are the speaker images

**Comment by pstan26** [comment]
Looks great

**Comment by guylepage3** [comment]
hmm.. i could switch the order to be alphabetical by last name if you like. let me know.

**Comment by pstan26** [comment]
Would like to move Garry Tan all the way to the right, irrespective of alphabetical order please.

**Comment by guylepage3** [comment]
on it.

**Comment by guylepage3** [comment]
![eventbrite-speakers-01](https://user-images.githubusercontent.com/1711854/27204962-20ae4cd0-51fc-11e7-9fa6-636c5f2f2f00.png)
![eventbrite-speakers-02](https://user-images.githubusercontent.com/1711854/27204961-20aadae6-51fc-11e7-8b87-fdab361cbe94.png)

**Comment by guylepage3** [comment]
![eventbrite-speakers-01](https://user-images.githubusercontent.com/1711854/27205089-b2403dd4-51fc-11e7-93ec-5602f96d47aa.png)
![eventbrite-speakers-02](https://user-images.githubusercontent.com/1711854/27205088-b231a706-51fc-11e7-8380-e3a976d28968.png)

**Comment by guylepage3** [comment]
![eventbrite-speakers-03](https://user-images.githubusercontent.com/1711854/27206914-97f0f156-5208-11e7-810b-13221d73d63d.png)

**Comment by pstan26** [comment]
nice thank you @guylepage3

**Comment by guylepage3** [comment]
![eventbrite-speakers-04](https://user-images.githubusercontent.com/1711854/27209317-055eb34e-5219-11e7-873f-37b68e3bf431.png)

**Comment by guylepage3** [comment]
complete
