### ISSUE TITLE
blockstack 2017 summit logo

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#299]
Blockstack 2017 Summit logo

Something really quick. 

**Requirements**
Create a Blockstack 2017 Summit logo. Create two versions of logo that are diecut (to be used on Eventbrite, Facebook page, email signatures and promotional items). 
1) One color (white)
2) 4-color

**Comment by guylepage3** [comment]
<img width="401" alt="screenshot 2017-06-15 15 38 12" src="https://user-images.githubusercontent.com/1711854/27198549-aa1d3010-51e0-11e7-98c5-8214ba087cef.png">

**Comment by guylepage3** [comment]
<img width="255" alt="screenshot 2017-06-20 14 54 18" src="https://user-images.githubusercontent.com/1711854/27353563-72719a52-55d2-11e7-9547-599961b5d2a3.png">

**Comment by guylepage3** [comment]
will be working on this today

**Comment by guylepage3** [comment]
<img width="1109" alt="screenshot 2017-06-22 20 10 42" src="https://user-images.githubusercontent.com/1711854/27461357-f8162cee-5786-11e7-97e4-39a5d45b39be.png">

**Comment by pstan26** [comment]
Powerful B2. All hail B2.

**Comment by guylepage3** [comment]
👍 

All hail B2!

![image](https://user-images.githubusercontent.com/1711854/27489776-d268e580-5809-11e7-8adb-62f83ac802c2.png)

**Comment by pstan26** [comment]
The theme of the event is "Freedom to Innovate", harking back to Tim Berners-Lee's original vision of the internet (start at 14:45 [here](https://charlierose.com/videos/29038)):

> "the original dream was of this shared space, a place where we could basically be scribbling together. We should be able to make links when we think it is important -- not just bookmarks-- but actually things other people can see. I'd like it to be a creative space -- I think it will take it a long time until being creative on the web is as intuitive as browsing on the web is now."

> "The relationship between these databases should be exposed and programs can be written. It is a web for computer programs. I think it will be a second revolution"

We are attracting incredible speakers and attendees to the Summit because of this dream.

As per our previous offline discussion, if we were to eliminate the "B2", we would need to define what replaces it. Here are some logo requirements:

- * keep the magenta and white color scheme
- * include the words "Blockstack Summit" and "2017" in the final iteration
- * Remove "B2"

**Comment by pstan26** [comment]
Can meet you tmrw at office. The thing about it is we are trying to catch the spirit of creativity…thats what building apps on a decentralized internet is. I’m tempted to say take the magenta color scheme and design we have now and apply the same (or similar) sunburst effect that you used for the 2015 summit. Could look really cool.

**Comment by guylepage3** [comment]
Thank you for the comments @pstan26 this is better direction. The biggest focus for the branding is 

>Freedom to innovate

For the logo, we do not have a lot of time to build out a traditionally designed logo with 20-100 designs. So to streamline the time that we have we need to go with something "clean and simple." Also, let's keep in mind that the "Logo" will be used from today going forward. It's a brand that will continue to move forward and will not change as the only reason for building a separate brand for the summit is to build brand recognition so that it will be easier to reproduce and grow the event year-after-year.

So let's talk about what the logo will be like for the entire existence of all Blockstack Summits. That will put us in a better direction.

My initial thoughts are as follows;
- The logo should work with all future themes. This means it needs to be simple and clean.
- The logo should work with all colors as we do not know what colors will be in style in the years to come.

Questions;
1. Should the logo incorporate the word "Blockstack?" If so, why? and provide examples of the top 5 tech company conferences in the world to prove out why it is the best route to take.
2. Should the logo include the year? If so, why? and provide examples of the top 5 tech company conferences in the world to prove out why it is the best route to take.

**Comment by shanvoight** [comment]
I love what you did here with "B2" - very cool and sleek. We can use "B2" in most places, i.e. agenda, badges, tabletop signage - however, for poster signage, presentation starter slide and metal banners we will need to explain what "B2" is since people are entering the event not knowing about "B2" in advance. Can we create one other option where we use the "B2" logo and add the text underneath it "Blockstack 2017 Summit"?

**Comment by pstan26** [comment]
> Can we create one other option where we use the "B2" logo and add the text underneath it "Blockstack 2017 Summit"?

+1 to @shanvoight's comment here. Let's move forward with something like this that is simple that we can use and have no problem explaining. This is a bottleneck that we need to get past so other tasks can be completed with enough time left.

Will need what is produced as an EPS file for printing.

**Comment by shea256** [comment]
+1 to having a logo version that has the word Blockstack in it

**Comment by guylepage3** [comment]
Oh sorry. I did not realize @shanvoigt was commenting on design. Maybe we should chat about that.

**Comment by guylepage3** [comment]
cc:ing @shea256 @pstan26

**Comment by pstan26** [comment]
@guylepage3 What matters here is getting to a simple logo that can be explained without asking what it is. After this, we can finally execute the follow-on items in the queue inside the small window of time we have. If we need extra design help on this, I can outsource it in 2 seconds, just let me know.

**Comment by guylepage3** [comment]
@shanvoight @pstan26 @shea256 I would think of the logo as a stand alone brand that, yes. will always be accompanied by the wording of that particular event. For this year it would be "Blockstack Summit 2017." So for all material you'd see the "B2" logo accompanied by "Blockstack Summit 2017" in large lettering so that the audience would learn what the logo is. Much like Apple's "WWDC" and Facbook's "F8" conferences.

My hesitation is that it is to similar to Facebook's F8 however.

**Comment by guylepage3** [comment]
>Will need what is produced as an EPS file for printing.

We will create a vector graphic as always. Don't think I've ever produced a raster image for a logo before.

**Comment by shanvoight** [comment]
Hi Guy - would you mind sending me the current B2 logo designs as an InDesign file via dropbox? My email is svoight35@gmail.com. Thank you!

**Comment by guylepage3** [comment]
Hey @shanvoight we use Sketch here as our founders like the friendliness of the application. I can however export the file as an SVG vector graphic format for you. 

Logos are highly recommended to be produced in a vector graphics program such as Illustrator or Sketch.

**Comment by shanvoight** [comment]
Completely understand. The svg file will be great and understood about vectors. Thank you.

**Comment by shanvoight** [comment]
If it can be sent in illustrator that would be ideal. You can send this morning to katemeadowsdesign@gmail.com and cc: svoight35@gmail.com Thanks again Guy!

**Comment by guylepage3** [comment]
Hey @shanvoight will shoot it over in 20 mins

**Comment by shanvoight** [comment]
Thank you @guylepage3

**Comment by guylepage3** [comment]
Hey @shanvoight, here are the vector svg images. if you require them to be another vector format, they can simply be exported into whatever vector format you like. 😄 

Let me know if you need anything else.

[logos-outlined.zip](https://github.com/blockstack/designs/files/1116160/logos-outlined.zip)
[logos.zip](https://github.com/blockstack/designs/files/1116159/logos.zip)

**Comment by shanvoight** [comment]
Perfect, thanks @guylepage3

**Comment by guylepage3** [comment]
emailed as well. 👍

**Comment by shanvoight** [comment]
Awesome - appreciate it.

**Comment by shanvoight** [comment]
Hi! @guylepage3 We've seen multiple logo variations and thought this logo in particular would work great for the presentation and on-site summit branding. It appeals to both the male and female demographic. In addition, a single "B2" logo is almost finalized that I'll send to you as well. If you'd like to provide feedback, please respond by 7/5 afternoon. We could also have "2017" in the same font as "Blockstack" - let me know and I can resend quickly. Thank you! 
![screen shot 2017-07-04 at 12 01 06 pm](https://user-images.githubusercontent.com/29715942/27837483-8a8488a8-60b2-11e7-929b-1cded42e6ee8.png)

**Comment by shanvoight** [comment]
@guylepage3 ignore the "B2" logo comment above.

**Comment by guylepage3** [comment]
Hi @shanvoight, can we go with this logo? I can supply it to you in vector format.

<img width="1071" alt="screenshot 2017-07-06 07 52 28" src="https://user-images.githubusercontent.com/1711854/27916119-215a31a4-6236-11e7-962f-4d7ce3c3c906.png">

**Comment by shanvoight** [comment]
@guylepage3 I love the look of it but I'm worried that the shape around the "B.2017" is too similar to the Facebook event and that there will be copyright issues. I also feel like this is now going to change the look of all signage and the presentation which will take a few days to update and were against the wall on deadlines. We have to email the speakers with the presentation this week. Let me get back to you shortly to see if we have time to make this change at this point. @pstan26

**Comment by guylepage3** [comment]
>"B.2017" is too similar to the Facebook event and that there will be copyright issues.

@shanvoight, the shape is a custom shape that I created, there also needs to be 3 elements that are changed. Which we have. color, font, shape wording, etc.

I can provide one more with an even different shape as well.

**Comment by guylepage3** [comment]
Here's another shape.

<img width="1095" alt="screenshot 2017-07-06 11 00 07" src="https://user-images.githubusercontent.com/1711854/27917554-50d93bf6-623a-11e7-8f01-c71e5cb16b0d.png">

**Comment by guylepage3** [comment]
<img width="1090" alt="screenshot 2017-07-06 11 05 08" src="https://user-images.githubusercontent.com/1711854/27917771-0128a1ea-623b-11e7-8212-29df4e172b2d.png">

**Comment by guylepage3** [comment]
@shanvoight here are the logos outlined in .ai format.

[blockstack-summit-2017-logos-final.zip](https://github.com/blockstack/designs/files/1128286/blockstack-summit-2017-logos-final.zip)

**Comment by shanvoight** [comment]
@guylepage3 thank you for sending the .ai format and the explanation. I'm checking to see if we have time to make these edits.

**Comment by guylepage3** [comment]
hi @shanvoight here are the final final logos that are production ready.

[blockstack-summit-2017-logos-final-production-ready.zip](https://github.com/blockstack/designs/files/1128746/blockstack-summit-2017-logos-final-production-ready.zip)

**Comment by shanvoight** [comment]
thanks @guylepage3

**Comment by guylepage3** [comment]
complete. closing issue.
