### ISSUE TITLE
blockstack summit 2017 presentation template

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#307]
Create a standard presentation template with new Blockstack 2017 Summit logo with same fonts and layout for event speakers to use for their presentations. Only 3 slides needed that can be repurposed.

**Comment by guylepage3** [comment]
@pstan26. A couple of questions for you

1. What type of template would you like? Apple Keynote? Microsoft Powerpoint? – This is quite important as we will not be able to create one for every presentation format. In the past we've picked one and gone with it but we may need to have a couple. Keynote and MS Powerpoint.
2. What are the dimensions of the screen that the presentations be appearing on? – This is required to display the best, most forward thinking format to the audience.
3. What screen resolution will the presentations be appearing on? The color magenta does not play well with well lit projectors for example.
4. What 3 slides will be needed?

**Comment by guylepage3** [comment]
1. Templates are a 1/4 to a 1/2 day's worth of work
2. Yes. But we will need to come back around to it to finalize it
3. I'll build it out as a v1 in Keynote first then. Will wait to execute on MS powerpoint until this is confirmed.
4. Cool. thank you.

**Comment by shanvoight** [comment]
I'm waiting on screen dimensions for presentation but hoping to have by tomorrow afternoon at the very latest. I'll also confirm Keynote vs. MS Powerpoint. Thank you!

**Comment by guylepage3** [comment]
Awesome. thank you @shanvoight 😄

**Comment by shanvoight** [comment]
@guylepage3 here is the presentation template with the new logo. We can use a variety of the background slides or stick with one color. Patrick would love to send the presentation to the speakers today or tomorrow so your quick feedback is greatly appreciated. thanks again!
[Blockstack_Presentation_R3.pdf](https://github.com/blockstack/designs/files/1127874/Blockstack_Presentation_R3.pdf)

**Comment by shanvoight** [comment]
@guylepage3 attached is the updated presentation. We incorporated the Blockstack purple along with the dots you prefer. Please let us know which slide you like best and we'll include several other slides as options for presenters, one white, one magenta, etc. Need your feedback by 10:30am est, Friday as well. Thanks again. cc: @pstan26 
[Presentation_BGs_R3 (2).pdf](https://github.com/blockstack/designs/files/1129962/Presentation_BGs_R3.2.pdf)

**Comment by shanvoight** [comment]
@guylepage3 worth mentioning - logo will remain unchanged on all collateral. Will need your feedback here in addition to the banner you already approved. Thanks again!!

**Comment by shanvoight** [comment]
@guylepage3 good morning! just a friendly reminder that feedback is due on the presentation pdf above. Thank you!

**Comment by guylepage3** [comment]
@shanvoight, just copying and pasting from slack.

Guy Lepage [10:44 AM] 
@shannon.voight there is the brand that I'd go with. Super simple and clean.


[10:45] 
We must ensure that design fundamentals are used. things like guiding the eye across the screen with use of white space. Emphasis on priority items, etc.

[10:46] 
i would also like to see the blockstack logo placed on all the environmental material, etc.

[10:47] 
small and subtle of course as the blockstack logo is not the emphasis of the event

Shannon Voight [10:47 AM] 
Completely understand. Thanks for the update @guylepage3

Guy Lepage [10:47 AM] 
let me know if there's anything else you'd like me to look at

<img width="958" alt="screenshot 2017-07-07 10 42 14" src="https://user-images.githubusercontent.com/1711854/27964311-cf297d24-6305-11e7-8e09-f791ec0549e1.png">

<img width="956" alt="screenshot 2017-07-07 10 42 44" src="https://user-images.githubusercontent.com/1711854/27964312-cf2ba932-6305-11e7-9418-ff77117552ef.png">

[presentation-branding.ai.zip](https://github.com/blockstack/designs/files/1131392/presentation-branding.ai.zip)

**Comment by guylepage3** [comment]
closing out issue
