### ISSUE TITLE
Create name badge template

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#308]
Create name badge template with event logo in top corner or centered (digital)

**Comment by guylepage3** [comment]
@pstan26. A couple of initial questions; (there will be more i'm sure.)
1. What are the dimensions?
2. Will it be 4 color CMYK or RGB printing?
3. Want me to make printing suggestions? i.e. aqueous coating, etc.
4. Will the InDesign file template be used by the printer or by another party to finalize each badge?

**Comment by guylepage3** [comment]
To save time, let's use a printer that I am familiar with as using a new supplier can be extremely time consuming.

https://www.clubcardprinting.com/

**Comment by guylepage3** [comment]
What's the deliverable date for print production for the printer?

**Comment by guylepage3** [comment]
@pstan26 What's the deliverable date for print production for the printer?

**Comment by pstan26** [comment]
Let's make this super easy so you don't have to deal with print production. Would like to use a company called Conference Badge that already works with Eventbrite. It is the one Token Summit used. Conference Badge will pull from the eventbrite existing attendee list and print the card in the plastic sleeve. We can insert the Blockstack event logo (which you're pretty much done with) and for an extra .99 they will include the black lanyard. Here is a link so you know: https://www.conferencebadge.com/#pricing

We will just need logo I presume.

**Comment by guylepage3** [comment]
By not going with a printer that we've used in the past it's more work on my end unfortunately.

**Comment by shanvoight** [comment]
This request will not require any work from you. Eventbrite's company - Conference Badge, is going to print these off based on the names in the Eventbrite system, which will help save time since there will be 400 of them. Its a cost savings and a useful service. I will just need the logo file from you so I can insert it in the top left corner of the badge. Consider this task removed from your list please.

**Comment by guylepage3** [comment]
@shanvoight Is there a way we can control the look of the badge?

**Comment by shanvoight** [comment]
If we use ConferenceBadge.com via Eventbrite we can still use the custom logo you've created on the badge and its a quick 1,2,3 print of the list they have in their system. If you prefer to use your own printer contact instead just let me know how much it will be so I can have the amount reflected in the budget as well as timing.

**Comment by guylepage3** [comment]
Do you have a link to the badge that conferencebadge.com offers? Or the one chosen? It may just suffice.

**Comment by shanvoight** [comment]
Yes, click on the link - [https://www.conferencebadge.com/](url)

**Comment by guylepage3** [comment]
Oh awesome!! this was almost identical to what i had in mind! 😄 

Just the logo will be needed here. :)

**Comment by shanvoight** [comment]
Love that! Thank you.

**Comment by guylepage3** [comment]
closing this issue out.
