### ISSUE TITLE
blockstack summit 2017 poster

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#309]
Event branding poster template (to be printed)

- Event logo shown large with sponsor logos at the bottom (QUANTITY: 2)
22"x28" foam board. 
    - Example: http://www.vistaprint.com/foam-board-signs.aspx?txi=17512&xnid=TopNav_Foam+Boards+(linked+item)_Signs+%26+Posters&xnav=TopNav

Printing: 3-5 business days

**Comment by guylepage3** [comment]
@pstan26 A couple of questions: (there probably will be more)
1. What are the dimensions?
2. Will it be 4 color CMYK or RGB printing?
3. Want me to make printing suggestions? i.e. aqueous coating, etc.
4. Who's the printer? To save time, let's use a printer that I am familiar with as using a new supplier can be extremely time consuming. https://www.clubcardprinting.com/

**Comment by guylepage3** [comment]
What's the deliverable date?

**Comment by pstan26** [comment]
I've always used Vistaprint and like working with them. CMYK is always best for printing in general. Vistaprint pricing is competitive from what I've seen. I included the dimensions in the design request but here they are again and they are also super easy to work with:
22"x28" foam board. Example: http://www.vistaprint.com/foam-board-signs.aspx?txi=17512&xnid=TopNav_Foam+Boards+(linked+item)_Signs+%26+Posters&xnav=TopNav

**Comment by guylepage3** [comment]
>CMYK is always best for printing in general. 

Some printers are RGB digital printers. So we cannot ever make that assumption. Back in the day, before higher quality printers we could however.

Please provide color format.

> I included the dimensions in the design request but here they are again and they are also super easy to work with: 22"x28" foam board

No. We still need to know the following;
1. bleed
2. live area
3. color format

**Comment by shanvoight** [comment]
Hi Guy - nice to meet you! Thanks again for all your help on this project. Im going to respond to all your questions right now on github but if you need to reach out to me to discuss further - I can be reached at 917.621.6079.

**Comment by guylepage3** [comment]
Hey @shanvoight. Nice to meet you as well. That sounds awesome. Looking forward to working with you. 😄

**Comment by shanvoight** [comment]
Thanks - you too. I called printer to get bleed measurements - will update you on all items 
in just a few mins.

**Comment by guylepage3** [comment]
Thank you. :)

**Comment by shanvoight** [comment]
1-bleed - the full dimensions of the poster for this request are 22.50x28.50 (vertical). The bleed comes in at .5 on each side. The full area to be seen will be exactly 22"x28".
2-live area - The live area is 22"x28". 
3-color format - The color format is 4 color CMYK. 
4- print deliverables - We'd love to review a pdf of the sign this week. We need the order placed by 7/13 (at the latest) and have the sign in-house by 7/19. We can have the printed items arrive at Blockstack and then ship to the event venue OR have the items shipped directly to the venue. Im waiting to hear back that we can definitely ship to the venue instead of a FedEx office in Mountain View. Will know by tomorrow morning, which still works because we need to view signage this week anyway.

**Comment by guylepage3** [comment]
thank you so much @shanvoight. 👍 

>We'd love to review a pdf of the sign this week.

This probably won't happen this week as we have yet to finalize the brand for the event. But will keep you in the loop on timing.

Thanks again for getting this to me. 😄

**Comment by shanvoight** [comment]
Sure thing. I know that you have a lot going on at work so let me know if you have any other questions. Happy to help! I'm available at any point on here or cell.

**Comment by shanvoight** [comment]
One note on printing, I called Clubcard printing (https://www.clubcardprinting.com/) to double-check that their timing mirrors ours if we release files to print by 7/12. They mentioned that our items would need to ship from Vancouver, which may not be ideal as far as shipping costs/timing. The reason being - they closed their US store so these items would need to be shipped out of Vancouver. They also have pricier options for printing - for example - the retractable metal banners are $140 with Vistaprint and $215 with Clubcard, which isnt a huge expense more but not ideal. If youre not a fan of Vistaprint I'm happy to check out someone else. I have had good experiences with Vistaprint for numerous events but you let me know.

**Comment by guylepage3** [comment]
Oh no.. [sad face]. I know Nathan. I'll have to give a call. 

@pstan26 @shanvoight if you two have printer you'd prefer I trust your judgement.

**Comment by shanvoight** [comment]
No problem, he said it was a recent move. We've used Vistaprint numerous times - they're fast, easy to connect with for any questions and reliable.

**Comment by guylepage3** [comment]
>We've used Vistaprint numerous times - they're fast, easy to connect with for any questions and reliable.

My only reservation with Vistaprint is that they had bad quality. But the last time I used them was lik 6 years ago. 

How's the quality these days?

**Comment by shanvoight** [comment]
Ah good to know. I use them frequently and the quality has been great. They're also fast so should there be an issue - they can fix it quickly - however, hoping that all will work great.

**Comment by shanvoight** [comment]
one note - i've also thoroughly enjoyed working with [4over4.com](url)

**Comment by shanvoight** [comment]
@guylepage3 Here is all of the event signage with the new logo. We need to have all signage approved by tomorrow so we can send to printer and make print deadlines. 
[B2_Directional_22x28 (1).pdf](https://github.com/blockstack/designs/files/1127887/B2_Directional_22x28.1.pdf)
[B2_Podium_16x20 (1).pdf](https://github.com/blockstack/designs/files/1127891/B2_Podium_16x20.1.pdf)
[B2_Poster_22x28 (1).pdf](https://github.com/blockstack/designs/files/1127890/B2_Poster_22x28.1.pdf)
[B2_PullUpBanner (1).pdf](https://github.com/blockstack/designs/files/1127889/B2_PullUpBanner.1.pdf)
[B2_Tabletop_8.5x11 (1).pdf](https://github.com/blockstack/designs/files/1127888/B2_Tabletop_8.5x11.1.pdf)

**Comment by guylepage3** [comment]
Hi @shanvoight here is more of the direction that I'd like to see as it's lighter, simpler, etc.

<img width="289" alt="screenshot 2017-07-06 14 17 20" src="https://user-images.githubusercontent.com/1711854/27926284-db41b0b4-6255-11e7-91a1-6e1ed00d0e04.png">

[blockstack-summit-2017-banner Folder.zip](https://github.com/blockstack/designs/files/1128831/blockstack-summit-2017-banner.Folder.zip)

**Comment by shanvoight** [comment]
@guylepage3 we're on the same page. I was just chatting with her about a similar look to break up the magenta a little bit. Sending this to her now. Thank you.

**Comment by shanvoight** [comment]
only note @guylepage3 we'll need to make the logo much larger since its too small for the space. Is that cool with you?

**Comment by shanvoight** [comment]
lastly @guylepage3 do you want this background on most collateral?

**Comment by guylepage3** [comment]
Oh no. Let's be cognizant about filling spaces and utilize our design knowledge with white space.

**Comment by guylepage3** [comment]
@shanvoight can i see the final of the banner etc. let's use design fundamentals to execute solid pieces.

**Comment by shanvoight** [comment]
@guylepage3 Yes, you'll be able to view all files for review but note - we only have one round for edits, maybe two.

**Comment by shanvoight** [comment]
@guylepage3  mentioned in the #design slack "here's the direction that I would go in for the summit brand", which I translated as continuing the dots to other collateral since you mentioned "brand." In github it seems like you want it to just be the banner only. With that said, we'll use a similar look for the banner but then be cognizant as per usual with all other collateral - correct?

**Comment by guylepage3** [comment]
@shanvoight that was just one brand item showing simplicity that should be applied across the board to everything. For presentations, we should just stick with Lato font, keep type and logos not too large and use the blockstack purple with the dots. Hope this works out.

**Comment by shanvoight** [comment]
Yes, got it. Thanks @guylepage3

**Comment by shanvoight** [comment]
@guylepage3 attached are several options for the pull-up banner. One is even the same version that you originally mocked up (#4), however the logo is now on scale with the correct banner dimensions. Would you like to move forward with #4 or one of the other options instead? We need feedback by 11am est, Friday. Thank you! cc: @pstan26 
[B2_PullUpBanner_R2 (2).pdf](https://github.com/blockstack/designs/files/1129956/B2_PullUpBanner_R2.2.pdf)

**Comment by guylepage3** [comment]
Hi @shanvoight, please do not change the logo.

**Comment by guylepage3** [comment]
If we go with the logo presented and #4 we should be good. Thank you

**Comment by guylepage3** [comment]
If we go with the logo presented and layout no. 4 we should be good. Thank you

**Comment by shanvoight** [comment]
@guylepage3 awesome, thanks for the quick feedback. Confirming option #4 for banner. Logo unchanged. Thanks again. cc: @pstan26

**Comment by guylepage3** [comment]
@shanvoight, sorry what i meant by please do not change the logo from the ones I sent. The logo in this banner has been altered from what i had originally sent over.

**Comment by shanvoight** [comment]
@guylepage3 in option 4 of the banner? If the logo was altered it was to make it slightly larger due to the banner dimensions - we are still working with the same design. We also really need to move forward at this point.

**Comment by guylepage3** [comment]
Actually no @shanvoight. The logo has been altered on your end. See the image below. Please resolve this on ALL material.

<img width="396" alt="screenshot 2017-07-07 17 39 18" src="https://user-images.githubusercontent.com/1711854/27978010-506f0d24-633b-11e7-8b4a-09b25022a665.png">

**Comment by shanvoight** [comment]
@guylepage3 I'll ask Kate now to adjust dimensions. I have noted that logo is to remain unchanged.

**Comment by shanvoight** [comment]
Hi! @guylepage3 (cc: @pstan26) we have included the "B.2017" logo in all signage for the event. We have also included the "Blockstack" logo as you did in the presentation slide mock so that we're consistent throughout signage. I was able to get a print extension to release all print files by Tuesday at the very latest, which means I'd love to make any final edits on Monday (tmrw). With that said, if you have any questions or concerns, please call me Monday at 917.621.6079. Please note: the directional and tabletop signage offer 2 options for each sign. Let us know if you prefer "B.2017" logo on top or both on the bottom? Thank you!
[B2_PullUpBanner_F2.pdf](https://github.com/blockstack/designs/files/1134431/B2_PullUpBanner_F2.pdf)
[B2_Podium_16x20_R3 (1).pdf](https://github.com/blockstack/designs/files/1134433/B2_Podium_16x20_R3.1.pdf)
[B2_Poster_22x28_R3 (1).pdf](https://github.com/blockstack/designs/files/1134434/B2_Poster_22x28_R3.1.pdf)
[B2_Directional_22x28_R3 (2).pdf](https://github.com/blockstack/designs/files/1134435/B2_Directional_22x28_R3.2.pdf)
[B2_Tabletop_8.5x11_R3 (1).pdf](https://github.com/blockstack/designs/files/1134436/B2_Tabletop_8.5x11_R3.1.pdf)

**Comment by guylepage3** [comment]
Thanks @shanvoight, a couple of things.. 😄 

1. Can we make sure we use our Lato typeface as we are using that on the presentations.
2. Can we reduce the size of all B.2017 logos by 15%.
    1. Can we reduce the size of the logo's on the poster by 25% please. Also, @pstan26 should we not include some copy on the poster? Maybe the Tim Burners-Lee quote?
3. Can we reduce the size of all Blockstack logos by 10%.

Thank you.

**Comment by shanvoight** [comment]
Thanks @guylepage3. I'll make all edits and wait for confirmation on quote. Appreciate it!

**Comment by pstan26** [comment]
@guylepage3 @shanvoight 

re: poster, yes it would be cool to have: 

"We're going back to the original dream back in 1989. The original dream was a shared space. A place where we could be scribbling together.” - Tim Berners-Lee

Thumbs up?

**Comment by shanvoight** [comment]
Thanks for confirming @pstan26. @guylepage3 I will add to posters. Would you like on banner as well or just posters?

**Comment by guylepage3** [comment]
Where are the banners being placed? 

I feel it would be nice to have that quote on signage as well. But we should ensure that it does not over power the logo so the quote font size would need to be a little smaller.

**Comment by shanvoight** [comment]
Pull up banners are placed by stage. Posters are placed by registration and then also in room serving lunch and breakout sessions. Quote on posters is sufficient. It may be too much on banners in my opinion @guylepage3

**Comment by guylepage3** [comment]
Sounds good @shanvoight @pstan26 👍

**Comment by shanvoight** [comment]
@guylepage3 (cc: Patrick Stanley) Hi Guy! We resized logos based on your percentage specs, confirmed Lato typeface, included the quote on posters and adjusted the pink and blue on four dots. Hoping we can release files to print today. If you could kindly provide feedback by 4:30 that would be greatly appreciated. Apologies on the tight turnaround, however we have to release all files to print today. Its our final extension. Thanks again!
[B2_Directional_22x28_F.pdf](https://github.com/blockstack/designs/files/1140010/B2_Directional_22x28_F.pdf)
[B2_Podium_16x20_F (2).pdf](https://github.com/blockstack/designs/files/1140008/B2_Podium_16x20_F.2.pdf)
[B2_Poster_22x28_F.pdf](https://github.com/blockstack/designs/files/1140012/B2_Poster_22x28_F.pdf)
[B2_PullUpBanner_F (3).pdf](https://github.com/blockstack/designs/files/1140009/B2_PullUpBanner_F.3.pdf)
[B2_Tabletop_8.5x11_F.pdf](https://github.com/blockstack/designs/files/1140011/B2_Tabletop_8.5x11_F.pdf)

**Comment by guylepage3** [comment]
great @shanvoight.

Let's reduce the logo on the poster by 20% and then reduce the type by 15%. I don't focus on the logo nor the quote with the current layout.

Also, the dots are white on all these which makes it so hard to read. In the supplied versions there was a 50% opacity on the dots so that we can read type.

**Comment by shanvoight** [comment]
Sure thing. We will adjust. Thanks @guylepage3

**Comment by shanvoight** [comment]
@guylepage3 (cc: @pstan26) I included two versions of the poster, one making the changes exactly as you asked for, and one with a secondary recommendation to make the quote the focus of the poster. Let us know which you prefer Thursday morning. Thank you!
[B2_Poster_22x28_F (2).pdf](https://github.com/blockstack/designs/files/1144107/B2_Poster_22x28_F.2.pdf)

**Comment by pstan26** [comment]
@guylepage3 said he is going to post final version to use here within the
hour.

**Comment by guylepage3** [comment]
just packaging the file...

**Comment by shanvoight** [comment]
great, thank you @guylepage3

**Comment by guylepage3** [comment]
hey @shanvoight, please find the attached zip file.

_**Please note:**_ I did not do any print production on this file or it's support files so your team will need to do so.

[blockstack-summit-poster-22x28 Folder.zip](https://github.com/blockstack/designs/files/1145599/blockstack-summit-poster-22x28.Folder.zip)

<img width="806" alt="screenshot 2017-07-13 10 51 11" src="https://user-images.githubusercontent.com/1711854/28172580-f17256fe-67b9-11e7-82b6-63355354983d.png">

**Comment by guylepage3** [comment]
closing out issue
