### ISSUE TITLE
design standup - Fri, Jun 23, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#310]
**yesterday** i worked with @arisgk & @estermer on organizing a process for committing designs in sketch, worked on blockstack.org tutorials section and blockstack summit logo design and some other summit design items.

**today**, i will be focusing on the summit logo, poster and name tags as welll as the browser edit profile designs, onboarding designs and ui build of the onboarding screens

**Comment by arisgk** [comment]
**Yesterday** I studied our design process and moved existing Install view compositions to a new file to adapt with it.

**Today** I started working on our Install view mobile version and prepared some prototypes. I plan to iterate on them and dive into implementation if we make sure everything is fine.

**Comment by estermer** [comment]
***yesterday:*** took some time to look over any open issues on my PR’s, reviewed contributing guidlines from other repos to refine .org’s contrib guidelines.

***today:*** I plan to keep an eye on any further suggestions while I continue to refine the contributing guidelines
