### ISSUE TITLE
design standup - Mon, Jun 26, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#311]
**friday** i worked onboarding designs, hosted our first ever design standup with @arisgk & @estermer which, as expected, took longer than anticipated as it was the first standup, worked on was to streamline the process, worked on blockstack summit logo concept with patrick, moved the office furniture around with team, moved and organized design issues on blockstack-browser from v9 and v10 so that the two sprints can be archived.

**saturday**, worked on requirements for blockstack summit logo, started browser edit profile screen designs

**today**, summit logo, build out browser onboarding screens once ryan has signed off on design, browser edit profile screens, summit environmental branding.

**Comment by estermer** [comment]
***Friday*** I started reviewing adding contributing guidlines to designs. didn't get too far though.

***Weekend*** nothing

***Today*** I plan on getting the contributing guide ready for for review for blockstack/designs

**Comment by arisgk** [comment]
**Friday** I worked on blockstack.org install view designs for mobile screens.
**Weekend** Nothing
**Today** I plan to start implementing the install view design we chose.
