### ISSUE TITLE
design standup - Tue, Jun 27, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#316]
**yesterday**, summit logo, finalized browser onboarding screen design with ryan, browser edit profile screens designs, summit environmental branding.

**today**, build out the browser onboarding screens and browser edit profile screens designs

**Comment by arisgk** [comment]
**Yesterday**, familiarized myself with blockstack.org - https://github.com/blockstack/blockstack.org repository structure.
**Today**, I plan to design some light background versions of our install view.

**Comment by estermer** [comment]
***Yesterday:*** I tweeked the .org repo contribution guidelines and near finished the designs contrib guidelines.
***Today:*** I am going to walk through the contrib guidelines as a dev too see if the process is smooth.
