### ISSUE TITLE
blockstack.org/summit - needs updated?

### ISSUE THREAD

**Issue by cryptocracy** [blockstack/designs#318]
@guylepage3 

So I googled "Blockstack Summit" to get more details about the 2017 Summit. 
Top result was [blockstack.org/summit](https://blockstack.org/summit) 
However its content is just referencing 2015 Summit.
Since its already got good page rank for the Phrase to URL, this should be updated to the 2017 Summit details imo

**Comment by guylepage3** [comment]
@cryptocracy thanks for the heads up on this.

@pstan26 shall we include this in the requirements with Shannon and team?

**Comment by pstan26** [comment]
Would it work if we just archived the 2015 page somewhere else and
redirected summit toward the blog post? If that is possible, I'd highly
prefer that. We are about sold out so extra work here seems wasteful.

**Comment by cryptocracy** [comment]
@pstan26 ... Thats the most logical in my opinion
Selling out the Summit is awesome btw 👍

**Comment by guylepage3** [comment]
sounds good guys. @cryptocracy can you create a github issue in the [blockstack/blockstack.org repository](https://github.com/blockstack/blockstack.org) for this? Thank you sir. 👍
