### ISSUE TITLE
design standup - Wed, Jun 28, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#319]
***Yesterday:*** I did not get around to testing anything for contributing due to a busy work day.

***Today:*** I am going to find some time to end to end test of the contribution flow.

**Comment by guylepage3** [comment]
_**yesterday**_: designed browser edit profile screens designs, new profile design in profiles app, created live design prototype of browser from sketch in invision, designed some of the other on-boarding screens, caught a few errors on the home screen of the browser, worked on name registration part 2.

_**today**_: build out the browser on-boarding screens and browser edit profile screens designs

**Comment by arisgk** [comment]
**Yesterday** worked on alternative install view designs.

**Today** will not have time to contribute due to a busy day.
