### ISSUE TITLE
design standup - Thu, Jun 29, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#321]
_**yesterday**_: designed browser edit profile screens designs, designed some of the other on-boarding screens, profile log issue, pull request process (w/ @shea256 , @estermer, @jcnelson), contribution guidelines review, worked on name registration (Day 3). [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-311801083)

_**today**_: finalize design & build out the browser on-boarding screens and browser edit profile screens designs, start build

**Comment by arisgk** [comment]
**Yesterday** Nothing

**Today** I plan to continue working on alternative install view designs.

**Comment by estermer** [comment]
*Yesterday:* I was able to review the process of contributing and added a few additional steps and resources from suggestions from the maintainers and from other contributors, I made changes according to the most recent suggestions made from guy’s review.

*Today:* I plan to wait for another review and see if there is further explanation on the versioning suggestion to make those necessary changes if needed to the contribution guidelines

**Comment by guylepage3** [comment]
Update to my today...

_**today**_: 
- Create new browser sketch file version to be `browser-v0.11.sketch`
- Add on-boarding screens to `browser-v0.11.sketch` file
- Resolve symbols in sketch `browser-v0.11.sketch` file
- Fix SASS grid in `blockstack-bootstrap`
- Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- Add grid to `browser-v0.11.sketch` file
- Finalize designs for on-baording screens (get @shea256 to sign off)
- Add "edit profile" designs to `browser-v0.11.sketch`

**Comment by guylepage3** [comment]
adding 
- [ ] [blockstack.org/#294: FAQ page not loading](https://github.com/blockstack/blockstack.org/issues/294)
