### ISSUE TITLE
design standup - Fri, Jun 30, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#323]
_**yesterday**_:  attempted to catch up on design research, quick management of design team, caught up on emails, created new browser sketch version file v0.11, added "on-boarding" screens to browser version file, ran into a couple road blocks when going to finalize the on-boarding screens and began recording issues, worked on name registration (Day 4). [#557: full on-boarding/ register a name use case (comment)](https://github.com/blockstack/blockstack-browser/issues/557#issuecomment-312061936), also spent 3 hours on passport renewal forms for out of country passport renewal.

_**this morning**_: 
- [x] Respond to GitHub issue comments
- [x] Review and respond to [PR: Testing PR Process](https://github.com/blockstack/blockstack.org/pull/342)

_**today**_: finalize design & build out the browser on-boarding screens and browser edit profile screens designs, start build
- [ ] Review keychain restoration process
- [ ] Finalize recording UX of deletion of Blockstack ID and restoration of Blockstack ID.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/323

**Comment by estermer** [comment]
***Yesterday:*** kept up with ironing out the PR process in the contributing guidelines for the .org repo and translating those changes to the contrib guide in the designs repo. Ran a test PR to do an end to end test of the flow of the PR process. 

***Today:*** going to just keep an eye out for any changes or suggestions and ensure the contribution guide is merged successfully. Also peek around and add some input to the discussions on other tickets.

**Comment by arisgk** [comment]
**Yesterday** worked on alternative install view designs.

**Today** will not be able to contribute due to a busy schedule.
