### ISSUE TITLE
design standup - Mon, Jul 3, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#324]
_**friday**_:  responded to GitHub issue comments, reviewed and respond to [PR: Testing PR Process](https://github.com/blockstack/blockstack.org/pull/342), created full review of account backup process, worked on the full review of account restoration process. discovered that there were 3 user flows.

_**saturday**_:  finalized backup account process review, 3 user flows of restore account process review. As a result of all the on-boarding/name registration, account backup and account restoration process reviews some really big insight came out of it that seriously impacts the browser and the browser's UX/UI. @shea256 and I discovered the need to move the `Profiles`, `Storage`, `Wallet` & `Settings` into status bar as "Browser Utilities" allows for a more intuitive user experience that separates apps to utilities required by the browser.

And to also apply the same UI from the "Profiles" app to all other browser utilities.

_**sunday**_:  went through design research. had to take the day due to a family issue.

_**today**_:
- [x] UI build `Profiles` app into status bar to become a browser utility
- [ ] UI build `Storage` app into status bar to become a browser utility
- [x] UI build `Wallet` app into status bar to become a browser utility
- [ ] UI build `Settings` app into status bar to become a browser utility

_**ahead**_:
- [ ] [blockstack.org/#294: FAQ page not loading](https://github.com/blockstack/blockstack.org/issues/294)
- [ ] design to do list app icon for home screen
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

**Comment by arisgk** [comment]
**Friday and weekend** Nothing.
**Today** I plan to explore pending projects and issues in our repositories in order to discuss upcoming tasks.
