### ISSUE TITLE
design standup - Tue, Jul 4, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#325]
**Yesterday** Explored https://github.com/blockstack/blockstack.org/ for open issues. Worked on video padding and faq link issues.

**Today** I plan to search for other open issues (or new ones) and propose solutions.

**Comment by guylepage3** [comment]
_**yesterday**_:  worked on pulling profiles and wallet into the status bar as a browser utility, had weekly scrum call, was in transit for 4th of July holiday and worked with @shea256 @larrysalibra on game plan for browser pre-summit.

_**today**_: 4th of July holiday. work with front-end team on tasks and continue design of new status bar
- [ ] Design of new status bar

_**ahead**_:
- [ ] UI build `Storage` app into status bar to become a browser utility
- [ ] UI build `Settings` app into status bar to become a browser utility
- [ ] [blockstack.org/#294: FAQ page not loading](https://github.com/blockstack/blockstack.org/issues/294)
- [ ] design to do list app icon for home screen
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
