### ISSUE TITLE
design standup – Wed, Jul 5, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#326]
_**yesterday**_:  was 4th of July and I only managed to get done 2 hours of design community management.

_**today**_: I will continue design of new status bar and implementation as well as work on the summit logo and branding.

- [x] Design of new status bar
- [ ] UI build `Storage` app into status bar to become a browser utility
- [ ] UI build `Settings` app into status bar to become a browser utility
- [x] Blockstack Summit Logo

_**ahead**_:
- [ ] [blockstack.org/#294: FAQ page not loading](https://github.com/blockstack/blockstack.org/issues/294)
- [ ] design to do list app icon for home screen
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

**Comment by estermer** [comment]
***Yesterday:*** Nada. Enjoyed the vacation over the weekend, cookouts, and kayaking.

***Today:*** Gunna catch up to where I left off before the long weekend.

**Comment by arisgk** [comment]
**Yesterday** Worked on FAQ link and video padding issues, coordinated with @guylepage3 on future tasks and blockstack.org issues.

**Today** Will not be able to contribute.
