### ISSUE TITLE
design standup – Thu, Jul 6, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#327]
**Yesterday** Nothing

**Today** I plan to continue my work on video padding issue and, if I complete it, continue with `main.css` file restructuring.

**Comment by guylepage3** [comment]
_**yesterday**_:  I worked on the blockstack summit logo, design of the new status bar and managed design community.

_**today**_: manage pull requests, build out new status bar, pull in profile design into browser utilities, work on summit items, to do list app icon design, review browser on-boarding screens with @shea256.

- [ ] [blockstack.org/#294: FAQ page not loading](https://github.com/blockstack/blockstack.org/issues/294)
- [ ] UI build `Storage` app into status bar to become a browser utility
- [ ] UI build `Settings` app into status bar to become a browser utility
- [ ] design to do list app icon for home screen
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)

_**ahead**_:
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

**Comment by estermer** [comment]
***Yesterday:*** reviewed process for PR, and comments in issues to catch up
***Today:*** continue to review make adjustments and refine the process and see if we can get the contributing guide be merged.

**Comment by guylepage3** [comment]
Additions:
- [ ] Create storage icon for status bar
- [ ] Create wallet icon for status bar
- [ ] Create settings icon for status bar
- [ ] Add new icons to status bar design
- [ ] Work with Shannon on blockstack summit branding direction

**Comment by guylepage3** [comment]
- [ ] [Fixing flexbox orientation](https://github.com/blockstack/blockstack-browser/pull/590)
