### ISSUE TITLE
design standup – Fri, Jul 7, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#329]
**Yesterday** I iterated on video padding issue.

**Today** I will not be able to contribute.

**Comment by guylepage3** [comment]
_**yesterday**_:  finalized the blockstack summit logo, designed the Blockstack Summit banner for brand hand-off, finalized design of the new status bar including 4 new icons, built out new status bar, handled a couple of pull requests and managed design community.

_**today**_: design to do list app icon, work on Apollo website design.

- [ ] design to do list app icon for home screen
- [ ] Start on project Apollo website design

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)


Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/329

**Comment by estermer** [comment]
***Yesterday:*** I reviewed further the discussed PR process, worked a little on writing it out in a easy to follow format.

***Today:*** continuing to work on writing out the PR flow.
