### ISSUE TITLE
design standup – Mon, Jul 10, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#332]
***Friday:*** Went through . and reviewed the comments on the PR process from Larry and others and reviewed the git-flow process. Began writing out the process.

***Today:*** Going to get the PR process written out and ready for review.

**Comment by arisgk** [comment]
**Friday & Weekend** Nothing.

**Today** I plan to continue with the video padding issue and start working on the blockstack.org `main.css` issue if I complete it.

**Comment by guylepage3** [comment]
_**friday, saturday**_:  worked on  design of to do list app icon, worked on 2 layouts of project Apollo website design.

_**sunday**_: took the day off as i was getting burnt out.

_**today**_: finalize design to do list app icon, finalize 2 layouts of project Apollo website design.

- [ ] finalize design to do list app icon for home screen
- [ ] finalize 2 layouts of project Apollo website design

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Storage` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Build UI for on-boarding screens
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)


Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/329

**Comment by guylepage3** [comment]
Addition:
_**friday**_: I also worked with Shannon on the Blockstack Summit presentation, brand and logo

**Comment by matheusml** [comment]
**_friday_**: added QR code to wallets

**_today_**: work is going to be busy this week, so my plan is to be more reactive and just check the opened issues
