### ISSUE TITLE
design standup – Tue, Jul 11, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#333]
_**yesterday**_: worked on 2 layouts of project Apollo website design, meetings then errands, with more work on 2 layouts of project Apollo website design in the evening and update to browser home screen layout and pulling in storage into settings.

_**today**_: finalize design to do list app icon, finalize 2 layouts of project Apollo website design.

- [x] resolve ui issues with pulling in storage app into settings
- [ ] finalize design to do list app icon for home screen
- [x] finalize 2 layouts of project Apollo website design
- [ ] Build UI for on-boarding screens
- [ ] Finalize designs for on-boarding screens (get @shea256 to sign off)

_**ahead**_:
- [ ] UI build of project Apollo website design
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/333

**Comment by arisgk** [comment]
**Yesterday** Iterated on video padding issue.

**Today** I plan to continue with video padding and move on to `main.css` organization issue.

**Comment by estermer** [comment]
**Yesterday:** Discussed further details about PR process and maybe a TL;DR to go along with it. Edited the current PR process for contributors to follow the usage of git-flow.

**Today:** continue to discuss TL;DR requirements or if needed and discuss a full PR process document. Test the current PR process as a contributor using git-flow.

**Comment by guylepage3** [comment]
Addition:
- [x] resolve ui issues with pulling in storage app into settings

**Comment by matheusml** [comment]
**Yesterday**: nothing relevant

**Today**: try to develop these features: https://github.com/blockstack/blockstack-browser/issues/606, https://github.com/blockstack/blockstack-browser/issues/605, https://github.com/blockstack/blockstack-browser/issues/604
