### ISSUE TITLE
design standup - Thu, Jul 13, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#337]
_**yesterday**_: 
- Worked on to do list app icon
- Worked on getting design system planning started for @arisgk
- Worked on meetup banners
- Worked on start of sketch shared assets for design team - ran into issue with InVision Craft asset libraries. contacted support and spent time troubleshooting.
- Worked on creating new profile in browser - ran into issues with bitcoin wallet
- Worked on troubleshooting home screen icon issue in browser

_**today**_:
- [x] [#309: Designed quick summit poster](https://github.com/blockstack/designs/issues/309#issuecomment-315103234)
- [ ] Create Sketch/InVision Craft shared logo asset library for design team
- [ ] Create Sketch/InVision Craft shared app icon asset library for design team
- [ ] Finalize design to do list app icon for home screen
- [ ] Design guild app icon for home screen
- [ ] UI build of project Apollo website design
- [ ] Finalize designs for on-boarding screens
- [ ] Review pull request process for @estermer
- [ ] Build UI for on-boarding screens (if @larrysalibra is complete on his end)

_**ahead**_:
- [ ] Build UI for on-boarding screens
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/337

**Comment by matheusml** [comment]
**Yesterday**: [this pull request](https://github.com/blockstack/blockstack-browser/pull/615)
**Today**: probably nothing, but if I have time, I'll check some bugs

**Comment by estermer** [comment]
**Yesterday:** Tested PR process and submitted a PR.
**Today:** Taking the day off getting after it tomorrow.
