### ISSUE TITLE
design standup – Fri, Jul 14, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#341]
_**yesterday**_: 
- [x] [#309: Designed quick summit poster](https://github.com/blockstack/designs/issues/309#issuecomment-315103234)
- Worked on logo production, outlined graphics, thickened font, made all logos consistent,built our new component based logo asset library
- worked on guild app icon
- worked on 

_**today**_:
- [x] Create Sketch/InVision Craft shared logo asset library for design team
- [ ] Create Sketch/InVision Craft shared app icon asset library for design team
- [x] Finalize design to do list app icon for home screen
- [x] Design guild app icon for home screen
- [ ] UI build of project Apollo website design
- [ ] Finalize designs for on-boarding screens
- [ ] Review pull request process for @estermer
- [ ] Build UI for on-boarding screens (if @larrysalibra is complete on his end)

_**ahead**_:
- [ ] Build UI for on-boarding screens
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/341

**Comment by arisgk** [comment]
**Yesterday and until Monday** On holiday

**Comment by matheusml** [comment]
**Yesterday**: nothing

**Today**: probably won't have time as well, but if I do, I'll check some bugs
