### ISSUE TITLE
design standup - Mon, Jul 17, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#344]
**Friday:** did some dev env set up for the blockstack browser. didn't do anything over the weekend.

**Today:** Will continue to set up dev env whats left and get started on the flex box issue for browser in safari.

**Comment by guylepage3** [comment]
_**friday**_: 
- [x] Finalized Sketch/InVision Craft shared logo asset library for design team
- [x] Finalized design of to do list app icon for home screen
- [x] Finalized design guild app icon for home screen
- Worked on Sketch/InVision Craft shared app icon asset library for design team

_**today**_:
- [ ] Finalize Sketch/InVision Craft shared app icon asset library for design team
- [ ] UI build of project Apollo website design
- [ ] Finalize designs for on-boarding screens
- [ ] Review pull request process for @estermer
- [ ] Build UI for on-boarding screens (if @larrysalibra is complete on his end)

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/344
