### ISSUE TITLE
design standup - Tue, Jul 18, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#346]
**Yesterday:** I was able to get the flex-box working for the blockstack browser in Safari for issue #616.

**Today:** Waiting for the review on the PR process from @guylepage3 and if it is good to go, I can start working on getting the contribution guidelines for other repos (designs, browser, storage-js, etc).

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Finalized Sketch/InVision Craft shared app icon asset library for design team
- Worked on reviewing pull request process for @estermer
- Researched and installed `git flow`
- Had a lot of personal errands to run

_**today**_:
- [ ] Review pull request process for @estermer
- [ ] Review @arisgk pull request on blockstack.org
- [ ] Finalize designs for on-boarding screens
- [ ] UI build of project Apollo website design
- [ ] Build UI for on-boarding screens (if @larrysalibra is complete on his end)

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/344

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** I will not be able to contribute
