### ISSUE TITLE
Tutorial Intro Slide for Video and Blog post

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#349]
From Blockstack Slack DM

Patrick Stanley [2:01 PM] 
**Tutorial Intro Slide for Video and Blog post**
We can use static sketch file here, same one we used for CLI.
**Due Today**

**Comment by guylepage3** [comment]
@pstan26 can you provide me with the link to the video please sir. 😄

**Comment by pstan26** [comment]
yes, sign in with your Youtube Blockstack account to view:
https://youtu.be/vyTWJ5BUetM

**Comment by guylepage3** [comment]
@pstan26 here's the sketch file for the "Decentralized To Do List app with Sign in & Storage" video title..

https://github.com/blockstack/designs/blob/master/video/video-titles.sketch

And here's the PNG image:
https://github.com/blockstack/designs/blob/master/video/assets/Decentralized%20To%20Do%20List%20app%20with%20Sign%20in%20%26%20Storage%402x.png

**Comment by guylepage3** [comment]
closing issue
