### ISSUE TITLE
blockstack summit video bumper animation

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#350]
From Blockstack Slack DM

Patrick Stanley [2:01 PM] @pstan26 
**Video Bumper**

I imagine this to be the current pink/purple Summit background with Summit logo and Blockstack logo centered.
For video filming at event and post even videos:
**Due Monday, July 24**
Please send mp4 file in FullHD (1920x1080px) for both intro and outro. Once slides live has it, they can start with editing asap.
Thank you!

**Comment by guylepage3** [comment]
@pstan26 this was the task from yesterday. correct?

**Comment by pstan26** [comment]
This is for the videos that our video professionals are going to create for
the summit. Still need this!

**Comment by guylepage3** [comment]
@pstan26 can we get the original file, non-compressed nor exported, of the blockstack animation from the declaration video? I can edit it and export it. Let the know we have adobe after effects. also could just get them to export the logo animation as a clipped movie. either or works.

**Comment by guylepage3** [comment]
working on this now.

**Comment by guylepage3** [comment]
complete with 2 seconds outro within animation movie.

https://github.com/blockstack/designs/blob/master/events/07-17-blockstack-summit-2017/designs-by-blockstack/video-bumper/blockstack-summit-bumper.mov
