### ISSUE TITLE
design standup - Wed, Jul 26, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#363]
**Yesterday** Nothing
**Today** Nothing

**Comment by estermer** [comment]
**Yesterday:** Submitted a [PR](https://github.com/blockstack/blockstack-browser/pull/656) for the issue 640 for the browser and cleaned up this [PR](https://github.com/blockstack/blockstack-browser/pull/626) to get merged in. reviewed some of the PR process and contrib guidelines.

**Today:** Going to add the open bazaar and casa icons to the browsers homepage.

**Comment by guylepage3** [comment]
Focus was on project Apollo site and browser and all tasks for Summit. Full heads down
