### ISSUE TITLE
Send @vsund (that's me) the vector files of the Beacon logo

### ISSUE THREAD

**Issue by vsund** [blockstack/designs#364]

**Comment by guylepage3** [comment]
Hey @vsund, you can find the latest version of your Beacon logo/app icon here. 😄 

https://github.com/blockstack/designs/blob/master/browser/designs/browser-app-icons.sketch

**Comment by guylepage3** [comment]
closing this issue.

**Comment by guylepage3** [comment]
here's the svg image @vsund 

https://github.com/blockstack/designs/blob/master/browser/assets/app-icon-beacon.svg
