### ISSUE TITLE
design standup - Thu, Jul 27, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#366]
**Yesterday** Nothing
**Today** I plan to finish my first iteration on blockstack.org `main.css` restructuring.

**Comment by estermer** [comment]
**Yesterday:** I added the Casa and OpenBazaar Icons to the homepage of the browser with this [PR](https://github.com/blockstack/blockstack-browser/pull/658)

**Today:** Nothing

**Comment by guylepage3** [comment]
Focus was on project Apollo site and browser and all tasks for Summit. Full heads down
