### ISSUE TITLE
design standup - Fri, July 28, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#368]
**Yesterday:** Nothing, Retweeted a ton from Blockstack Summit since I couldn't be there haha.

**Today:** I am actually looking at fixing the bugs in my [React Blockstack Generator PR](https://github.com/blockstack/blockstack-app-generator/pull/6) So that can finally get merged sometime soon. PS I am racing a 10 miler today! Woot! 🏃

**Comment by arisgk** [comment]
**Yesterday** Worked on blockstack.org `main.css` issue.
**Today** Nothing.
