### ISSUE TITLE
Ongaku Ryoho design

### ISSUE THREAD

**Issue by icidasset** [blockstack/designs#384]
Hey folks,

I just refined the design and onboarding experience for ~http://ongakuryoho.com~ http://isotach.io

I was wondering what everyone thought and what could possibly be improved? Even if it's something super small or stupid, let me know!

Stuff like:
- What do you think of the onboarding experience? Did everything make sense?
- Do all the icons match the actual subject?
- What do you think about the font colors? Is everything readable enough?

Or even:
- Please redesign this whole section ...
- Please remove this entirely, this doesn't make sense ...

PS. It looks best in Chrome and Safari. Firefox does something really weird with the font line-height.

**Comment by icidasset** [comment]
Just added a new about page: http://ongakuryoho.com/about/

**Comment by pstan26** [comment]
Have to say this looks pretty great -- will be awesome when it supports
gaia storage for a seamless experience for Blockstack users.

Jude is about to follow up with you on that in a second.

**Comment by icidasset** [comment]
@pstan26 Thanks Patrick! 😄 Looking forward to that as well.

**Comment by pstan26** [comment]
https://github.com/blockstack/blockstack-core/issues/500#
issuecomment-320769526            <----  here it is :-)

Do you feel you are in a position to integrate yet or is there anything
else we can do for you?

**Comment by icidasset** [comment]
@pstan26 `blockstack.js` or `blockstack-storage-js` will need to be updated as well before I can start implementing it. And the blockstack-browser will need to be updated as well I presume, because that uses blockstack-core underneath right?

**Comment by pstan26** [comment]
Ah, hmm let me ask @larrysalibra -- he should know :-)

**Comment by larrysalibra** [comment]
I'll make a note to bring this up at tonight's storage meeting.

**Comment by pstan26** [comment]
bless you larry

**Comment by guylepage3** [comment]
taking a look at this today @icidasset. have been sick for the past few days. 😄

**Comment by icidasset** [comment]
Thanks @guylepage3 ! I hope you are feeling better today 😊

**Comment by icidasset** [comment]
Updated to: http://isotach.io
