### ISSUE TITLE
design standup – Tue, Aug 8, 2017

### ISSUE THREAD

**Issue by arisgk** [blockstack/designs#387]
**Yesterday** Researched on testing solutions, specifically [Jest](https://facebook.github.io/jest/) and [Enzyme](http://airbnb.io/enzyme/)

**Today** Nothing

**Comment by estermer** [comment]
**Yesterday:** Did not get around to the review of contrib guide.

**Today:** well get on anything needed to be updated for guide.

**Comment by guylepage3** [comment]
Was under the weather..
