### ISSUE TITLE
Create custom icon set 

### ISSUE THREAD

**Issue by field2** [blockstack/designs#419]
We should have a set of custom icons made specifically for blockstack
It would be helpful to start with a list of icons that we could get started with.

**Comment by guylepage3** [comment]
Hey @field2 let's figure out scope before we start thinking about the icons..

What are you comfortable with executing?

**Comment by field2** [comment]
Good idea. I'm open for anything-maybe I should start by reviewing design mockups completed to this point and compiling a list of any icons that appear? Then as each icon is designed, it can replace the old one until a new mockup can be posted showing the new icons in context.

**Comment by guylepage3** [comment]
That sounds like a great plan. 😄  Want to throw the list in here?

**Comment by field2** [comment]
![blokstack_ui](https://user-images.githubusercontent.com/1656980/30507316-4298ba9a-9a51-11e7-9972-3ba8549dc510.png)
first shot at an outline icon style

**Comment by guylepage3** [comment]
Nice! @field2.. 😄 

I don't know if you saw this.. but..

https://github.com/blockstack/blockstack-browser/issues/757

One thing that we are looking for is a clean, rounded edges, fun and easy to view icon set that is similar to the examples provided in the issue above.

It is important that the icons be very simple. less is more. And that they have appropriate whitespace between objects so that the viewer can easily identify with the icon(s) at the quickest of glances. Lines should not come close to one another.

I would like to see more of the rounded nature that we see in the examples as well as try adding more space between objects inside each icon.

**Comment by guylepage3** [comment]
From issue https://github.com/blockstack/blockstack-browser/issues/757

This is awesome @field2. I'm really liking the cleanliness of the instagram and facebook iOS mobile app navbar icon designs...

We need to keep in mind that the icons need to be both outline as well as solid.

<img width="400" alt="ios-navbar-facebook" src="https://user-images.githubusercontent.com/1711854/30395866-a89ab252-9895-11e7-9530-5fdf4bb9e1e1.jpg">

<img width="400" alt="ios-navbar-instagram" src="https://user-images.githubusercontent.com/1711854/30395867-a8a09eba-9895-11e7-8249-798c70c3e3f7.jpg">

**Comment by guylepage3** [comment]
@field2 let's make our comments here. 👍

**Comment by field2** [comment]
![image](https://user-images.githubusercontent.com/1656980/30703156-e60da554-9ebc-11e7-9031-9e8895209d31.png)
Here's my first take. These are based on a 9px grid, so at 9x9 they're 1px thick, 18x18 the edges are 2px and 27x27 they're 3px

**Comment by guylepage3** [comment]
So, one thing we should try to avoid is contour line art in icons as they become quite difficult to view the details when the icons are reduced in size.

We should also follow an icon wireframe for consistency with the overall shape and size of each icon. See this graph below...

**Comment by guylepage3** [comment]
<img width="1038" alt="screenshot 2017-09-21 11 47 13" src="https://user-images.githubusercontent.com/1711854/30705136-a1f213e0-9ec2-11e7-89f2-ea832784cb4f.png">

**Comment by guylepage3** [comment]
So let's examine the two logo sets..

Notice how the facebook logo set makes use of the available space within the inner circle of the icon wireframe? By doing this they are able to offer the user a consistent look of icon without the need to go bold and detract from the main focal content.

Also, take a look at the edges of their icons.. Very round, friendly and inviting. As mentioned, we want to ensure our corners and edges stay as round as we possibly can make them.

**Comment by field2** [comment]
I wish I could get the actual icons facebook uses in svg or font format to get a handle on how they're made. I googled a bit and couldn't find them...

**Comment by guylepage3** [comment]
Oh. Well this is how I was taught to build an icon set. by using a wireframe grid and setting rules for the icons. By following this design process we should be able to execute icons to match our desired effect. 

Icons are not easy at all. They are very difficult because they require less detail but still communicate the message to the user. Also, the designer needs to communicate the concept at the bat of an eye. So they do take quite a bit of time and iterating to get right.

**Comment by field2** [comment]
We definitly need rules, but I think the rules should be concerned with technical issues first and we can concentrate on stylistic ones later. Unlike facebook, we don't know what contexts they need to appear in, although I'm nowhere near as familiar with the design work done to this point as you are. As I see it, since such a wide range of apps and context could potentially use them, they should be as flexible as possible, and be able to be displayed crisply on the widest possible range of resolutions and point sizes. This starts with setting a minimal viewbox size, which I'm targeting as 9x9. The facebook icons are based on a minimum 17x17 size, which yields only 4 pixel-perfect options: 68x68, 51x51, 34x34 and 17x17. A 9 pixel base gives them crisp edges at 9x9, 18, 27, 36 etc. 
Facebook seems to use a base 17 pixel grid:
![fbicons_grid](https://user-images.githubusercontent.com/1656980/30709168-48007a40-9ecf-11e7-8d85-5981de16616a.png)
![facebook_icons](https://user-images.githubusercontent.com/1656980/30709167-47fd241c-9ecf-11e7-86c3-a5e87d353c94.png)

A 9 pixel based grid lets enables more sizes:
![blockstack_icons_grid](https://user-images.githubusercontent.com/1656980/30709307-c52a473a-9ecf-11e7-9ba4-af76b71a829e.png)
![blockstack_icons](https://user-images.githubusercontent.com/1656980/30709308-c52da1c8-9ecf-11e7-947b-a40465a1790c.png)

**Comment by guylepage3** [comment]
This is great @field2 however, we have a great icon set that we currently use;
- Nucleoapp
- Fontawesome

Having said that, we do want to design our own custom set of icons.

So we need to ensure that the quality of icons are that of the icon sets that we currently use first and foremost. Secondly we need to ensure usability. Users need to be able to look at the icons and instantly know what it represents from 16px and up.

Style comes first. Then the details / representation of each icon.

We can start out with the 4 icons that we see in the browser and see how they turn out.

How does that sound? 😄

**Comment by guylepage3** [comment]
I really do like the 7 pixel grid as it focus' the designer to make "less" decisions on the design itself. It's much more difficult to design with the 7 pixel grid but i feel a much stronger outcome in the end.

**Comment by field2** [comment]
Just to clarify on the 7px grid; do you mean the 17 pixel base grid that facebook icons use?

**Comment by guylepage3** [comment]
sorry.. was in a rush.. Yes. 👍

**Comment by field2** [comment]
Sorry for the lag on this....I just came across https://github.com/blockstack/designs/issues/87 and don't know why I didn't see it before. We should probably close this issue and return to that one...or vice versa?

**Comment by guylepage3** [comment]
NIce find @field2. that's a good idea. Closing this one out.
