### ISSUE TITLE
Signature Berlin tasks

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#421]
- [x] ~~reformat "Blockstack Signature Fund" logo to read "Signature Berlin". Great to have by 9/7/17~~
- [x] ~~Use opaque Berlin city background with newly created logo in foreground to create eventbrite image. [photos here](https://www.dropbox.com/sh/ayzek48mjedoxeo/AAA1AFxIxoFDupvf1mxi3jW7a?dl=0). Great to have by 9/13/17~~

See.. https://github.com/blockstack/designs/issues/421#issuecomment-329630227

**Comment by guylepage3** [comment]
@pstan26 let's set some hard dates on these when you get a moment. Thank you sir. 👍

**Comment by pstan26** [comment]
Let's set both tasks hard dates for 9/14. Thanks and I'll get back to you on logo name.

**Comment by pstan26** [comment]
"BLOCKSTACK NEXT" is what it looks like we may go with. Will confirm in a couple days. But I love this font for the word "NEXT" https://www.behance.net/gallery/33704618/ANURATI-Free-font

**Comment by pstan26** [comment]
Liking this font too with a combination of lowercase and capital letters at the same size to fit needs: https://www.behance.net/gallery/54789127/YKAR-Sans-Serif-Font

**Comment by guylepage3** [comment]
>"BLOCKSTACK NEXT" is what it looks like we may go with. Will confirm in a couple days. But I like this type of (but not this exact) font for the word "NEXT" https://www.behance.net/gallery/33704618/ANURATI-Free-font

YES! Perfect broken type. This is something similar to what I was talking about. But we should make it a bit cleaner and more legible.

**Comment by guylepage3** [comment]
@pstan26 do you need this today?

**Comment by pstan26** [comment]
We can push back to this friday. thanks @guylepage3

**Comment by guylepage3** [comment]
will do @pstan26 👍

**Comment by guylepage3** [comment]
>Use opaque Berlin city background with newly created logo in foreground to create eventbrite image. [photos here](https://www.dropbox.com/sh/ayzek48mjedoxeo/AAA1AFxIxoFDupvf1mxi3jW7a?dl=0)

@pstan26 those images are low resolution and not usable.

I'm going with the following image that is royalty free..

![artem-sapegin-337727-altered](https://user-images.githubusercontent.com/1711854/30459239-74ccfa46-997d-11e7-98c7-88ade8ed3a94.jpg)

**Comment by guylepage3** [comment]
@pstan26 please confirm the following tasks...

Tasks:
- [ ] Print production on the chosen "Signature Berlin" logo that that the designer provided.
- [ ] Use opaque Berlin city background with newly created logo in foreground to create eventbrite image. Image above.

**Comment by guylepage3** [comment]
<img width="1186" alt="screenshot 2017-09-14 19 43 33" src="https://user-images.githubusercontent.com/1711854/30460445-0766fb5c-9985-11e7-9b64-4f1524b174d8.png">

**Comment by guylepage3** [comment]
Some fine tuning on the typography etc. on the logo.

<img width="1186" alt="screenshot 2017-09-14 19 43 33" src="https://user-images.githubusercontent.com/1711854/30460477-245af056-9985-11e7-82f0-49c09670bd99.png">

**Comment by guylepage3** [comment]
![signature-berlin-eventbrite 1x](https://user-images.githubusercontent.com/1711854/30460581-b24a4740-9985-11e7-9426-d327b335c186.jpg)

**Comment by guylepage3** [comment]
hey @pstan26 let me know how this looks..

**Comment by pstan26** [comment]
very sexy

**Comment by guylepage3** [comment]
Definitely.. Nice work by Kelly.. Please thank her for us.

**Comment by shanvoight** [comment]
Hi @guylepage3 - can you send the InDesign (or whichever design platform) files of the Signature Berlin logos with the white/black background and the final file for the Berlin cityscape logo (as seen above)? Will also need link to royalty free image and font names. (just a friendly reminder, we'll always send final files to you for review before pushing live). Thank you!! (cc: @pstan26 )

**Comment by guylepage3** [comment]
Hi @shanvoight all the files are in the link below. 😄 

https://github.com/blockstack/designs/tree/master/events/09-17-berlin

**Comment by shanvoight** [comment]
Thank you @guylepage3 :)
