### ISSUE TITLE
design standup - Wed, Sept 13, 2017

### ISSUE THREAD

**Issue by estermer** [blockstack/designs#428]
**Yesterday:** did a quick fix of the footer logo resize issue and submitted a [PR](https://github.com/blockstack/blockstack.org/pull/389). Then I worked a little on the FAQ page layout and submitted some snapshots to the ticket to get a general Idea if it is going in the right direction.

**Today:** Need to catch up with @guylepage3 to understand a little better about using the designs page for the FAQ page. This will also help with adding any necessary language to the contributing guidelines.

**Comment by yknl** [comment]
**Yesterday**
- Set up bitcore node on an azure machine with @jackzampolin's help and started indexing
- Add flow static type checking and API documentation to social verification updates in blockstack.js 
- Fixed invisible alert/error messages in browser redesign

**Today**
- Finish up API changes for `validateProofs` in blockstack.js
- Finish setting up blockstack Explorer and familiarize with the code base
- Start on Explorer updates

**Comment by arisgk** [comment]
**Yesterday** Nothing
**Today** Nothing
