### ISSUE TITLE
berlin video

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#434]
@Zachvalenti,

Wanting to replace the last image in the video (where it currently shows a daytime aerial) with this: https://user-images.githubusercontent.com/1711854/30460581-b24a4740-9985-11e7-9426-d327b335c186.jpg  [original image here](https://user-images.githubusercontent.com/1711854/30459239-74ccfa46-997d-11e7-98c7-88ade8ed3a94.jpg)

Guy suggested we make the text logo (sans outline at first) to simultaneously fade-in and expand by 15%. Then the outline around the logo appear in like it would if you were to draw it in from bottom left all the way around to bottom right. 

While that line is being drawn in (at about the 3/4 mark), have the following logos appear in the bottom corners:

[Blockstack Logo](https://projects.invisionapp.com/boards/6R2VVROUGP5XE/)
[Signature Fund Logo](https://github.com/blockstack/designs/blob/master/funding/logo/blockstack-signature-fund-logo.svg0)

After it fades to black would love to get the words: 
"Tickets on Sale at
 signatureberlin.eventbrite.com"

link to closed design task related to this: https://github.com/blockstack/designs/issues/421

**Comment by pstan26** [comment]
@guylepage3 could you help Zach with sending over final main logo?

**Comment by guylepage3** [comment]
@pstan26 you bet..

**Comment by pstan26** [comment]
thank you sire, also the signature fund logo is giving us a 404 at the moment

**Comment by guylepage3** [comment]
Yeah.. I will supply the vector formats with layers for Zach

**Comment by pstan26** [comment]
Thank you @guylepage3 ! bless bless bless you

**Comment by guylepage3** [comment]
Hola mr. @zachvalenti.. I'll send over all final files in a few minutes sir. thank you for your patience. 👍

**Comment by guylepage3** [comment]
Ok. So to be safe @zachvalenti, here are the raster and vector (layered) assets.

Background image (HR, raster, JPG) – https://media.githubusercontent.com/media/blockstack/designs/master/events/09-17-berlin/video-assets/artem-sapegin-337727-video-file.jpg
Signature Berlin graphics (vector, layered, AI) – https://github.com/blockstack/designs/blob/master/events/09-17-berlin/logo/signature-berlin-logo-rev.ai
Blockstack Logo (vector, AI) – https://github.com/blockstack/designs/blob/master/logo/RGB/logo/blockstack-logo-landscape-rev.ai
Signature Fund Logo (vector, AI) – https://github.com/blockstack/designs/blob/master/funding/logo/blockstack-signature-fund-logo-rev.ai

Let me know if you have any issues

**Comment by pstan26** [comment]
Awesome @guylepage3 thank you! @zachvalenti let 'er rip!

**Comment by guylepage3** [comment]
Closing issue
