### ISSUE TITLE
token portfolio manager bounty

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#437]

**Comment by pstan26** [comment]
@guylepage3 using the following as a template... Would like to request an eventbrite image (2160 x 1080px) and an email image for mailchimp by Sunday 9/24 at 3pm.


![signature-bounties](https://user-images.githubusercontent.com/5605552/30650691-908f103e-9df1-11e7-97fd-0457fb2a09c4.png)

- Change the title of the bounty to "Build a Private Token Portfolio Manager"
- Switch Naval's face with the [Compound logo](https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAl8AAAAJGVhM2FmM2E2LWFkNmYtNGM4MC05ZTJmLTUzMmRmMWI0ZjFkOA.png)
- Switch Naval's name with "Compound VC"
- Switch the app displayed on the iPhone with one that looks like a token portfolio app:
![token portfolio app](https://user-images.githubusercontent.com/5605552/30651083-a86c5b48-9df2-11e7-84b4-015585028566.png)

**Comment by guylepage3** [comment]
This is great @pstan26. Can you remind me about this on **Sat, Sep 23, 2017**?

**Comment by guylepage3** [comment]
working on this now

**Comment by guylepage3** [comment]
Hey @pstan26, here are the two images for the app bounty

**Email** - https://github.com/blockstack/designs/blob/master/funding/bounty-token-portfolio-manager/bounty-token-portfolio-manager-1600x900.png
**Eventbrite** - https://github.com/blockstack/designs/blob/master/funding/bounty-token-portfolio-manager/bounty-token-portfolio-manager-2160x1080.png
