### ISSUE TITLE
Resize token portfolio bounty graphic

### ISSUE THREAD

**Issue by xanbots** [blockstack/designs#454]
Recommended dimensions are 2260px wide by 482px tall @guylepage3  Thanks!
![bounty-token-portfolio-manager-1600x900](https://user-images.githubusercontent.com/31934541/31134882-65acf954-a831-11e7-955c-7adbb6ceb7a8.png)

**Comment by guylepage3** [comment]
Thanks @xanbots when do you need this by ideally?

**Comment by xanbots** [comment]
@guylepage3 before Friday would be ideal.  Message promoting the page doesn't go out until either end of this week or Monday. Is that doable?

**Comment by guylepage3** [comment]
Best timing for me on this would be Saturday if that's ok? I'm super swamped.

**Comment by xanbots** [comment]
That works, we can just make sure promotion doesn't go out until Monday. Thanks!

**Comment by guylepage3** [comment]
If that works for you then cool. If not just let me know and I'll find a way to fit it in.

Also, if you could send me a reminder on Saturday morning that would be very helpful. Thank you sir.

**Comment by xanbots** [comment]
Sounds great. Thank you and will do.

**Comment by guylepage3** [comment]
hey @xanbots was this handled?

**Comment by xanbots** [comment]
Yep all handled. Thanks!
