### ISSUE TITLE
Create quick brand banner

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#456]
Create a quick brand banner for team and community to use in various instances.

**Comment by guylepage3** [comment]
###Medium Banner
![blockstack-brand-banner](https://user-images.githubusercontent.com/1711854/31183905-f7deaca4-a8f5-11e7-98fb-6306e351f4c4.png)

### Large Banner
![blockstack-brand-banner 2x](https://user-images.githubusercontent.com/1711854/31183906-f7f9b94a-a8f5-11e7-80e8-0c1f4e11473b.png)

**Comment by guylepage3** [comment]
complete

**Comment by guylepage3** [comment]
@GinaAbrams I've created a new "Brand Banner" for you for all future branding you may need to use. 😄

**Comment by GinaAbrams** [comment]
Awesome, thank you @guylepage3!
