### ISSUE TITLE
Design hard fork blog post image

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#463]
Design hard fork blog post image.

Can just use the "fork" icon with the blockstack logo. Possibly include the version number?

**Comment by guylepage3** [comment]
![blog-blockstack-fork-2017](https://user-images.githubusercontent.com/1711854/31298242-45bb0be4-aab7-11e7-84bc-e03277d32706.png)

**Comment by guylepage3** [comment]
@shea256 @jcnelson here's the blog post image for the hard fork announcement

**Comment by jcnelson** [comment]
love it!
