### ISSUE TITLE
New browser profile design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#468]
New browser profile design from frontend meeting

Reference.. https://paper.dropbox.com/doc/Frontend-Meeting-Notes-YQeBNauljmDPvglKz6FiU

**Comment by guylepage3** [comment]
<img width="467" alt="screenshot 2017-10-10 12 14 51" src="https://user-images.githubusercontent.com/1711854/31397967-78c20d20-adb5-11e7-923c-24aad731b5a1.png">
<img width="467" alt="screenshot 2017-10-10 12 15 53" src="https://user-images.githubusercontent.com/1711854/31397968-78ccdbb0-adb5-11e7-9970-1464e1ac0b2e.png">

**Comment by shea256** [comment]
I would say "Increase your trust level" if we're using "trust level" in the profile as well.

Also still unclear what the best color is here. An "informational" color like a light blue might be best. Versus a green which indicates success or a red which indicates danger. Unless of course you were thinking the color would change from one level to the next.

**Comment by guylepage3** [comment]
>I would say "Increase your trust level" if we're using "trust level" in the profile as well.

👍 

>Also still unclear what the best color is here. An "informational" color like a light blue might be best. Versus a green which indicates success or a red which indicates danger. Unless of course you were thinking the color would change from one level to the next.

What ever the color is it needs to say "Attention."

Here's our color palette
<img width="217" alt="screenshot 2017-10-10 13 29 32" src="https://user-images.githubusercontent.com/1711854/31400886-1a76a582-adbf-11e7-81ac-d94eb5944717.png">

I would maybe lean towards the red (from above) or `amber` (column 1, row 7) color.
