### ISSUE TITLE
Type & other important components are not highly visible

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#473]
Lately I have been thinking a lot about our UI interface design and how that should dictate the overall brand more. I have also been spending time thinking about the actual UI style and how we can iterate the UI in increments and apply it to the overall brand slowly.

A good starting point is to address type and to solve some of the low hanging fruit on the design side. One of things that has been bothering me with the v0.16 redesign is that type does not stand out.

### Issues
- Type and other important components, ie. Navbar, do not jump out at the user.
  - [ ] Item 1 - Navigation is to light and does not stand out. 
  - [ ] Item 2 - As a result of Item 1, there will be a need to take a look at adjusting the weight of all colors in the Blockstack color palette.
  - [ ] Item 3 - As a result of Items 2 & 3, we may now want to revisit the dark gray and possibly consider black for highest contrast.

![typography-review-designs473 2x](https://user-images.githubusercontent.com/1711854/31558613-a6de4b66-b01b-11e7-853e-5d74fdc4599e.png)

### Solutions
- Try increasing contrast on type. But as we can see in the diagram above, doing so will introduce a host of other issues.
  - [ ] Item 1 - Solution - Increase the contrast of the gray being used, currently `#949494`, in the primary Navbar.
  - [ ] Item 2 - Solution - Increase the contrast of the gray being used, currently `#AEAEAE`, in the secondary Navbar.
  - [ ] Item 3 - Solution - As a result of increased tone across the board, consider increasing the contrast of the dark gray being used, currently `#2E2E2E`, possibly consider black for highest contrast.

**Comment by guylepage3** [comment]
@yknl when is the next build going out?

**Comment by yknl** [comment]
We're most likely pushing out a build tomorrow.

**Comment by guylepage3** [comment]
Ok. We need to have this go with the build after that. v0.19. Can we create a calendar invite for this so that we ensure this gets done?

**Comment by shea256** [comment]
Yes we've got to get a build out by tomorrow at 9am regardless of what is in there. Then we can do another build later in the week.

**Comment by amintorres** [comment]
@guylepage3 some thoughts on this. 
I understand what you are trying to do and agreed that small incremental improvements are a good approach. 

1 thing not to lose sight of:
As you consider these tweaks, do so in a way that you also consider how they might improve (or not) the design in other pages, not just based this one.

1 thing to consider:
I think defining what you want the user to do first, second and third on this page is actually the issue with the current design. 
Making the nav stand out I think is a non issue, what you are not getting from the contrast you see as lacking, you are nicely doing by how you are using the spacing for the main 4 navigation items. (plus the faintness in the unselected items is what makes it so clear which of them is sellected)

The  EDIT  VIEW and MORE can use a different treatment. 
I will almost hide those to a vertical 3 dots / filter icon an give that some more structure. (They feel floaty right now)
You can also lose the VIEW and just use a back arrow or an X when people are in edit view or in the more view. (not sure what those screens look like tho)

Question:
Is Thomas Middleditch looking at his own profile right now in this view?
Or is this what someone else sees when they visit his profile?

Are people allowed to follow each other within the app? message each other?

**Comment by guylepage3** [comment]
@yknl can you place your design in here so we may continue this discussion? Also, if you could provide everyone with the link to your Sketch file so that we may all work off it. Thank you sir.

**Comment by guylepage3** [comment]
modifications made. will revisit in next major UI overhaul.
