### ISSUE TITLE
Design legal docs section on blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#482]
Design legal docs section on blockstack.com

**Comment by guylepage3** [comment]
@shea256 will this be links to pages? links to PDF's? External links?

**Comment by shea256** [comment]
@guylepage3 The design you have right now for the whitepaper should be used for the legal docs section.

The whitepaper section we have on blockstack.org should be used for the whitepaper section.

**Comment by guylepage3** [comment]
gotcha.. 👍

**Comment by guylepage3** [comment]
![legal-docs 2x](https://user-images.githubusercontent.com/1711854/31630293-2fa02d88-b284-11e7-9ce8-8a460e05c2b6.png)

**Comment by guylepage3** [comment]
![desktop hd](https://user-images.githubusercontent.com/1711854/31630880-f7671baa-b285-11e7-9031-2c4543d0bc6c.png)

**Comment by shea256** [comment]
@guylepage3 Nice coming along!
