### ISSUE TITLE
Design team & investors section on blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#484]
Design team & investors section on blockstack.com

**Comment by guylepage3** [comment]
![team 2x](https://user-images.githubusercontent.com/1711854/31638968-604ac46e-b2a4-11e7-9dd3-e1deb95b0e03.png)

**Comment by guylepage3** [comment]
![desktop hd](https://user-images.githubusercontent.com/1711854/31638974-664bafae-b2a4-11e7-8ea2-017ba34ae412.png)

**Comment by guylepage3** [comment]
Need to add container element

**Comment by guylepage3** [comment]
![team-item 2x](https://user-images.githubusercontent.com/1711854/31694239-1d0c8eee-b371-11e7-9d31-36e84320fb6c.png)

**Comment by guylepage3** [comment]
New team item and possibly new Blockstack ID.
![team-item 2x](https://user-images.githubusercontent.com/1711854/31694946-44cc6a54-b375-11e7-9d51-65a0dbc62880.png)

**Comment by shea256** [comment]
@guylepage3 Don't think we should add this in there. This wasn't in our product requirements and we're on a pretty tight timeline.

**Comment by guylepage3** [comment]
Aghhh.. I didn't see your comment in slack until it was too late. Thought we decided to go down this route. Finishing up everything now.

**Comment by guylepage3** [comment]
![team 2x](https://user-images.githubusercontent.com/1711854/31697694-3a147072-b387-11e7-8bdc-c0e24b618f4a.png)

**Comment by guylepage3** [comment]
![desktop hd](https://user-images.githubusercontent.com/1711854/31697706-448dd782-b387-11e7-9818-44b43c3464a8.png)
