### ISSUE TITLE
Update to blockstack.com hero section

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#507]
Update to blockstack.com hero section to include;

- [x] Welcome banner
    - [x] ~~New subhead content~~
    - [ ] Updated content from @shea256 - https://github.com/blockstack/designs/issues/507#issuecomment-338207477
- [x] Video
- [x] Countdown timer
- [x] Sign up form

**Comment by guylepage3** [comment]
@shea256 here's the latest hero visual for blockstack.com. Maybe we should 

![blockstack-v2 18 1-hero 2x](https://user-images.githubusercontent.com/1711854/31821015-90411a90-b571-11e7-9092-7470764f0a27.png)

![blockstack-v2 18 1-home 2x](https://user-images.githubusercontent.com/1711854/31821016-904c7ad4-b571-11e7-897e-67326516721a.png)

**Comment by guylepage3** [comment]
New content from @shea256 

![image](https://user-images.githubusercontent.com/1711854/31823258-8713aa02-b579-11e7-9dd3-5ea1a0af80db.png)

**Comment by guylepage3** [comment]
@shea256 updated the content. 

@tracedwax.. we should be good to go for sign off on this content. once @shea256 gives us the thumbsup.

@smoliver, I'll update the video assets once the sign off happens as well.

![blockstack-v2 18 2-hero 2x](https://user-images.githubusercontent.com/1711854/31823686-dfc4231a-b57a-11e7-9f6d-6da329a36ea3.png)
![blockstack-v2 18 2-home 2x](https://user-images.githubusercontent.com/1711854/31823687-dfd1f33c-b57a-11e7-8652-f20e1416c545.png)

**Comment by guylepage3** [comment]
closing issue.

**Comment by guylepage3** [comment]
@shea256 check this out for the hero / sign up..

<img width="1437" alt="screenshot 2017-10-20 15 55 53" src="https://user-images.githubusercontent.com/1711854/31839476-3d5220ca-b5af-11e7-9fb4-ea2b73548492.png">

**Comment by shea256** [comment]
@guylepage3 OK nice, and can we see this with the timer?

**Comment by shea256** [comment]
Just want to see all the sections stacked.

**Comment by guylepage3** [comment]
I thought we were placing the timer below with the timeline?

**Comment by guylepage3** [comment]
gotcha

**Comment by guylepage3** [comment]
@shea256 can we get sign off on the hero for the Barefoot team?
