### ISSUE TITLE
Design new countdown timer for blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#510]
Design new countdown timer for blockstack.com

Token sale ends in...

**Comment by shea256** [comment]
@guylepage3 Note that the text should be what I put in my screenshot.

It should not be "token sale ends in..."

**Comment by guylepage3** [comment]
@shea256 Can you provide me with the screen shot? I can't seem to find it in Slack. Thank you.

**Comment by shea256** [comment]
![hero-03](https://user-images.githubusercontent.com/994646/31840090-c80ef90c-b5b1-11e7-8f80-9169494b2578.png)

**Comment by guylepage3** [comment]
@shea256...

![blockstack-v2 20 0-countdown 2x](https://user-images.githubusercontent.com/1711854/31840420-5743b4f4-b5b3-11e7-83d3-3406c2bd53dd.png)
![Uploading blockstack-v2.20.0-home@2x.png…]()

**Comment by shea256** [comment]
OK nice.

But is it just me or does the purple / white / purple / white / purple look weird?

The white / gray / white looks really nice.

**Comment by guylepage3** [comment]
We can give that a try. Let me lay that out.

**Comment by guylepage3** [comment]
![blockstack-v2 20 1-countdown 2x](https://user-images.githubusercontent.com/1711854/31841266-bfdbfa28-b5b6-11e7-8cf9-14caab5ec9a7.png)
![blockstack-v2 20 1-home 2x](https://user-images.githubusercontent.com/1711854/31841267-bfe6f090-b5b6-11e7-8451-28c4277774ef.png)

**Comment by shea256** [comment]
@guylepage3 Much better. The purple background of the stats section still looks weird though.

**Comment by guylepage3** [comment]
Let me change that back then..

**Comment by guylepage3** [comment]
![blockstack-v2 20 2-home 2x](https://user-images.githubusercontent.com/1711854/31841878-7cf5858c-b5b9-11e7-8014-796cd7c74f7d.png)
![blockstack-v2 20 2-stats 2x](https://user-images.githubusercontent.com/1711854/31841879-7d233f18-b5b9-11e7-9f0c-7ec6ad557d3b.png)

**Comment by shea256** [comment]
ok looks good, although there's an extra stats section at the end for some reason
