### ISSUE TITLE
Design image for timeline on blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#517]
Design image for timeline on blockstack.com

![blockstack-v2 23 1-timeline 2x](https://user-images.githubusercontent.com/1711854/31855353-4c8391be-b677-11e7-9809-3e16e43f0f9c.png)

**Comment by guylepage3** [comment]
Pinning.. https://github.com/blockstackinc/blockstack-dot-com/issues/14

**Comment by guylepage3** [comment]
![blockstack-v2 27 1-timeline 2x](https://user-images.githubusercontent.com/1711854/32030064-7eb5547c-b9c6-11e7-8483-21caf40f9b52.png)

**Comment by guylepage3** [comment]
![blockstack-v2 27 1-timeline 2x](https://user-images.githubusercontent.com/1711854/32030825-9d57e232-b9cb-11e7-90a8-a4b22a58ee6b.png)

**Comment by shea256** [comment]
Also remember we updated this timeline. There are only 4 periods now and they have different text.

**Comment by guylepage3** [comment]
>Also remember we updated this timeline. There are only 4 periods now and they have different text.

Yeah. we signed off on the design. content on the UI build has been approved. This is strictly for the image placement.
