### ISSUE TITLE
Design confirmation upon sign up for blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#520]
Design confirmation upon sign up for blockstack.com

**Comment by guylepage3** [comment]
@shea256 here's my proposed content for Token distribution newsletter.

1. New Hero content under the sign up form. We probably need some form of terms and conditions here for the newsletter sign up.
2. Popup email confirmation "Sent" – This messaging appears after the user successfully enters their email address and clicks the sign up button.
3. Popup email confirmation "Verified Email" – This messaging appears after the user has clicked the  "Verify email address" button in the email verification email.

1.
![blockstack-v2 26 0-hero 2x](https://user-images.githubusercontent.com/1711854/31908310-669b3136-b804-11e7-84fa-cbbcc4c34351.png)

2.
![blockstack-v2 26 0-email-confirmation-verified 2x](https://user-images.githubusercontent.com/1711854/31908309-6690f5e0-b804-11e7-8f39-68cb5b47dd8c.png)

3.
![blockstack-v2 26 0-email-confirmation-sent 2x](https://user-images.githubusercontent.com/1711854/31908308-6685e510-b804-11e7-8f1d-a52f94fd46c4.png)

Home Page View
![blockstack-v2 26 0-home 2x](https://user-images.githubusercontent.com/1711854/31908311-66a5cae2-b804-11e7-95f5-3bcd5082de21.png)

**Comment by tracedwax** [comment]
@guylepage3 all we're doing for emails thus far is capturing them, per previous discussions. Can we add the email sending and verification once the core site is ready for launch? cc @shea256

**Comment by guylepage3** [comment]
@tracedwax sounds good sir. Thank you.

**Comment by guylepage3** [comment]
closing issue
