### ISSUE TITLE
Add four more investors to investor section blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#527]
Add four more investors to investor section blockstack.com

**Comment by guylepage3** [comment]
![blockstack-v2 27 0-investors 2x](https://user-images.githubusercontent.com/1711854/32012224-2c0e9fe4-b985-11e7-8776-59652ed92a02.png)

![blockstack-v2 27 0-home 2x](https://user-images.githubusercontent.com/1711854/32012223-2bb1b93c-b985-11e7-98bb-35657c056aaf.png)

**Comment by guylepage3** [comment]
complete.

**Comment by shea256** [comment]
Let's move Lux to the top row. Also the name and logo for "Rising Tide Fund" are wrong (it's not "Rising Tide Ventures").

**Comment by guylepage3** [comment]
resloved.
