### ISSUE TITLE
revisit: blockstack bug/logo design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#53]
Design a new blockstack bug and logo.

**Design goals**
To create a cool, futuristic bug/logo that will be representative of blockstack and what blockstack is/does.

**Comment by guylepage3** [comment]
@larrysalibra @shea256 @jcnelson @muneeb-ali @itsProf @john-light 

We have a new blockstack logo that I'd like to present to the team.

1. **Blockstack "slant" logo and bug** - This logo is quite a bit edgier and definitely more aggressive than the current logo we have. We have been going through a discovery period with our branding. From illustrations, to background graphics, etc.. I feel this logo cohesively aligns with all of our other design and branding. 

This is a take on a simple box shape that hints at decentralization through multiple dots. It's clean, simple and modern. This version is also extremely neutral. This would allow for a wide variety of uses and would allow for easier distribution and usage amongst 3rd parties. We would also be able to apply almost any color we want in the future.

<img width="219" alt="screenshot 2016-12-08 11 30 14" src="https://cloud.githubusercontent.com/assets/1711854/21018135/c4e6868a-bd39-11e6-878e-d59c4cb65e32.png">

2. **Blockstack "box" logo and bug** - This logo is slightly more edgier and aggressive than the current logo we have but not as edgy and aggressive as the "slant" version. Again, I feel this logo cohesively aligns with all of our other design and branding. 

This is a take on a simple box shape that hints at decentralization through multiple dots. It's clean, simple and modern. This version is not as neutral as the "slant" version. But, having said that, the chosen brand color that is introduced in the top left dot is very subtle.

<img width="215" alt="screenshot 2016-12-08 11 30 19" src="https://cloud.githubusercontent.com/assets/1711854/21018596/695a5d94-bd3b-11e6-8075-e0745dc1541e.png">

It would appreciate as many comments on this issue over the coming days as this would be a major change in our brand positioning going forward. Thank you.

**Comment by shea256** [comment]
I like the one with the four dots. Both look great though. Unbelievable direction.

**Comment by guylepage3** [comment]
I just did a google search and we have more than 3 elements that are different than blockstack.io in the logo above. I really do like the idea of staying as neutral as possible as we are a platform where our brand will under and around many other brands and colors. In fact the more I think about it, it's probably one of the main reasons Apple backed away from colors.

**Comment by shea256** [comment]
+1

That said, I do like the 4 dot one better.

**Comment by guylepage3** [comment]
Two other options...

<img width="246" alt="screenshot 2016-12-08 18 45 38" src="https://cloud.githubusercontent.com/assets/1711854/21032288/933bf09c-bd76-11e6-8ba1-1078a1d35073.png">
<img width="274" alt="screenshot 2016-12-08 18 45 46" src="https://cloud.githubusercontent.com/assets/1711854/21032289/933e93c4-bd76-11e6-81f0-afcb37d87b40.png">

**Comment by shea256** [comment]
I like both of the first two, each with 4 dots. Not as much of a fan of the one with 9 dots.

**Comment by guylepage3** [comment]
<img width="428" alt="screenshot 2016-12-08 18 57 52" src="https://cloud.githubusercontent.com/assets/1711854/21032564/433bc5ac-bd78-11e6-8775-7684f8470fc0.png">

**Comment by guylepage3** [comment]
i'm liking the ovals over the rectangles. thoughts?

**Comment by larrysalibra** [comment]
+1 for 4 dots. The 9 dots look unbalanced. Looking good @guylepage3!

**Comment by muneeb-ali** [comment]
I love the old bug. It's been on my laptop for a year and feels so familiar. It has been featured in so many presentations (even by people outside of core developers). When people see the bug they think Blockstack (and in a good way!). I don't see a reason to change something that is not broken. We've already done a bunch of logo/brand changes that created confusion in the past and my vote is to stick with the bug and push any changes further down the road. Most successful projects/companies that I've seen would change/update the logo after 3-5 years. Our rate of change is currently in *months* and not even years.

**Comment by guylepage3** [comment]
@muneeb-ali 

One of the main reasons for a change in the branding and why it's so important at this stage is that we have discovered that...

we actually have a major design problem at the moment and that is that the brand does not work well in promoting other brands. we have discovered that this is our top design priority. communication of brand neutrality and openness is vital for our success. I look at a neutral brand like Apple and see white, black, grey, simplicity. it's very hard to argue that Apple is not one of the premier brands at marketing/design/communications. I feel this path is a path that will be the fastest route to success.

our current branding does not work well with other brands. it was created to be it's own stand alone brand. having said that we now are a platform. neutrality and simplicity is something that should be at the top of our minds when we think of the brand. color, complexity, etc.. that is something that, I feel, we should start to move away from.

**Comment by muneeb-ali** [comment]
Question: if we make this change, for how long are we going to stick to it before we discover something else and have another reason to change?

**Comment by guylepage3** [comment]
We should make our design decisions based upon the companies needs. Not a matter of timing. A logo is part of a communications toolkit. If we need to change a headline to execute better communications we should do so. Logo's are slightly different in that they are the face of the company. But we have been down this path for quite some time now. A lot of work has gone into this process. Here are just a few logo's we've played with.

<img width="1437" alt="screenshot 2016-12-09 11 13 39" src="https://cloud.githubusercontent.com/assets/1711854/21055706/8d141c0a-be00-11e6-8081-6f873b8f319c.png">

**Comment by shea256** [comment]
Correct me if I'm wrong but the original logo was a quick and dirty 2 hour thing that was meant to be temporary. We never got around to doing a real logo and ended up getting stuck with this.

I see this new logo as the first real attempt at one and something we should definitely stick with as Muneeb said.

I see the old purple logo as JV and this logo as the big leagues.

We should have something that's professional and clean and able to work with other brands.

Just my perspective.

Definitely appreciate that we shouldn't be shifting too often and we should stick with something we put a good amount of energy into, like this one.

**Comment by guylepage3** [comment]
>Correct me if I'm wrong but the original logo was a quick and dirty 2 hour thing that was meant to be temporary. We never got around to doing a real logo and ended up getting stuck with this.

100% correct.

**Comment by muneeb-ali** [comment]
My concern is that it's not just the bug, we seem to be dropping the purple color as well. Once you drop that then other content will start looking odd. For example, look at https://blockstack.org/talks. We cannot go back in time and change the talks now. This exact thing happened with a Microsoft Research talk. We stopped using it because the branding/name/logo in that talk was so outdated (it was blue and said Onename). 

Consistency is very important, in my view. Otherwise, I feel like a headless chicken running in a circle with no sense of direction. If this really is the moment we're entering the "big leagues" then I'd like to see a discussion about the timeline over which we're going to stick with this brand/logo/colors. In my view, it should be at least 2 years. We can then take the time to spend as much time as is needed to create the new brand.

**Comment by muneeb-ali** [comment]
Posting two examples here.

First example:
![image](https://cloud.githubusercontent.com/assets/669932/21056644/7b229c98-be04-11e6-92a2-8241f715d66d.png)

![image](https://cloud.githubusercontent.com/assets/669932/21056664/9981ea68-be04-11e6-904a-93ef52e6ab1f.png)

![image](https://cloud.githubusercontent.com/assets/669932/21056680/aabb707e-be04-11e6-9a0f-7fb57038e3cf.png)

Second example: 

YC when it launched in 2005:
![image](https://cloud.githubusercontent.com/assets/669932/21056741/e9f49a5e-be04-11e6-902e-9ae2c33f38bd.png)

YC now in 2016: 
![image](https://cloud.githubusercontent.com/assets/669932/21056814/34169902-be05-11e6-91f7-3974d8b8a4f0.png)

My point here is that the initial logos were clearly thrown together quickly and colors were just picked but then the colors became a part of the culture and brand. The companies/projects were successful regardless of someone spending too much time worrying about updating branding/logos and they made minimal changes later on when they were much much bigger. 

Changing the logo/color also changes the culture, the association people have with Blockstack, and all the previous brand awareness that we've built so far. It's a big big change and should be made only if extremely necessary.

**Comment by guylepage3** [comment]
I feel these are weaker examples of brands that are not necessarily platforms. Here's an example of the where we are coming from for our branding..

First Apple logo (April 1, 1976)
![image](https://cloud.githubusercontent.com/assets/1711854/21057439/b81e4252-be07-11e6-8879-1ad0752683c9.png)

Apple logo used from April 1977 to 1998.
![image](https://cloud.githubusercontent.com/assets/1711854/21057468/cce8538a-be07-11e6-8112-21798e0ef5ec.png)

Current Apple logo since 1998
![image](https://cloud.githubusercontent.com/assets/1711854/21057487/e2174bf8-be07-11e6-81a3-0549d8c68003.png)

Apple is a better example to work from.

Apple started out with a "quickie" logo. It was something that was non-representational of the company. We too started with a quickie logo that it's main purpose was to be different from our other brands. I feel we are at a stage in our history where we can execute the rebrand and move to a more neutral, modern, simpler, cleaner logo that will allow for the promotion of other brands on our platform.

As you can see with Apple's brand evolution, they moved to neutral colors the second they started realizing they needed to work under many different colors. Could you work with color and still have other colors/brands on top of yours. Yes. But it bumps up the design challenges 100x and it would increase our execution timing exponentially.

**Comment by larrysalibra** [comment]
I share @muneeb-ali 's concern about the rate of change of brand/naming. 

Apple changed their logo 3 times in 4 decades,  only changed the shape once and that was decades ago in 1977.
 
Blockstack owns purple and black right now and owns the bug now. We wouldn't own black and black because too many other companise have the same color combination. We wouldn't own 4 squares...microsoft beat us to that:

![microsoft-gray](https://cloud.githubusercontent.com/assets/597182/21089460/31e68816-c073-11e6-8277-f48927a15967.png)
<img width="329" alt="433bc5ac-bd78-11e6-8775-7684f8470fc0" src="https://cloud.githubusercontent.com/assets/597182/21089487/61187a40-c073-11e6-842b-1d2682f566e0.png">

Our software has strong opinions about how the world should be: to me that calls for a bold opinionated color. 

We can use the name in black on white or white on black without the bug when we need to avoid upstaging other people's brands. Or a white/black version of the bug.

<img width="105" alt="screen shot 2016-12-12 at 1 44 30 pm" src="https://cloud.githubusercontent.com/assets/597182/21089272/97eac192-c071-11e6-9db6-490037840ac7.png">

**Comment by guylepage3** [comment]
>We wouldn't own 4 squares...microsoft beat us to that:

Yeah. I have been revisiting the 4 squares and they should be 4 dots. Dots can represent blocks and nodes. I am not a firm believer in literal logo's as when a company changes, pivots, and/or grows they can become outdated and irrelevant. So I definitely feel that blocks do not work.

>Apple changed their logo 3 times in 4 decades, only changed the shape once and that was decades ago in 1977.

As stated above, Apple made a massive change to their logo after 1 year. We too are proposing to change the logo after one year. And I do agree that we should not make a habit of this.

**Comment by larrysalibra** [comment]
> As stated above, Apple made a massive change to their logo after 1 year. We too are proposing to change the logo after one year. And I do agree that we should not make a habit of this.

Ahh...I was looking at this in the brand context of: onename -> openname -> passcard -> blockstore -> blockstack...which feels a bit like a habit to me.  

If you look at it as just a one time Blockstack logo, that makes more sense.

**Comment by guylepage3** [comment]
@larrysalibra yeah. those were brands trying to find product market fit. blockstack is something that took off and the community liked quite a bit.

**Comment by muneeb-ali** [comment]
Another thing to keep in mind is that the bug and purple color are pretty different from Blockstream. With the black/grey, we become more similar to Blockstream https://blockstream.com, and it becomes easier to confuse us. 

Agreed with Larry on the rate of change. Apple changed things over decades. We've already done a bunch of iterations in 2015/2016. The changing things "out of habit" part is what I'm concerned about as well. Even if "habit" is not the reason, to the outside world we're building up a reputation of just changing name/logo/brand all the time, and that's not a good thing.

I know that we talked about this offline over lunch, but my gut feeling is still that this is a case of changing something that is clearly not broken and there is a good chance that we'd end up worse off after the modification.

**Comment by guylepage3** [comment]
>Another thing to keep in mind is that the bug and purple color are pretty different from Blockstream. With the black/grey, we become more similar to Blockstream https://blockstream.com, and it becomes easier to confuse us.

I personally do not see a correlation between blockstack (current brand) nor blockstack (proposed brand) to blockstream. Can you explain how they are related in your eyes?

>Agreed with Larry on the rate of change. Apple changed things over decades. We've already done a bunch of iterations in 2015/2016. The changing things "out of habit" part is what I'm concerned about as well. Even if "habit" is not the reason, to the outside world we're building up a reputation of just changing name/logo/brand all the time, and that's not a good thing.

Our product market fit doesn't really have anything to do with blockstack. we have always agreed that the brand will go through a proper round of branding since it originally was created to be a "dumb" brand that was going to be pushed out by a stronger brand such as "chord".

Also, Apple made a massively drastic change in their first year with their branding as seen in the example above. blockstack is something completely separate from all the other products.

**Comment by shea256** [comment]
In the case of Blockstack, we haven't actually yet changed our logo. I understand the aversion to this change because we've had name changes in the past, but I consider the start of Blockstack a different chapter, especially since the vast majority of people who know Blockstack were introduced to Blockstack and are not familiar with previous brands/names, other than Onename which is a product many people sign up for to this day and still has it's place in the ecosystem.

There is naturally going to be an aversion to a change of any kind. Then the change happens and people see the benefits of the big improvement in quality. I see this case as the one important change that we need to make to the brand. This is not a pattern or a habit. The name is not changing. The color is not changing.

A year ago we originally created a "quick and dirty" 2 hour logo (one that looks silly in my opinion). Then we made an actual attempt at a real logo, which we've seen here. This is one that looks extremely professional and unlocks a whole new world of design potential. See here:

<img width="1853" alt="e5036142-be27-11e6-8c11-3169ddf73948" src="https://cloud.githubusercontent.com/assets/994646/21106284/8f79f53e-c05b-11e6-837f-4c2fc49298a8.png">

Keep in mind there are many visuals and patterns we want to work with and the logo and the brand and the patterns and the layouts all work together and impose restrictions upon each other. They're like interlocking parts.

My view is we should make this one change to the logo, work in the new patterns and visuals and layouts, and keep the colors the same. This logo and brand can and should be the one we stick with.

**Comment by muneeb-ali** [comment]
I'm trying to reach a conclusion for this discussion. I see the point that the previous name/logo/brand changes make the aversion to this change stronger. But the fact remains that those changes happened and that reduces the flexibility to change now.

I don't agree with the change, but I won't object to it as long as we sign off of this: 

> This logo and brand can and should be the one we stick with. 

I.e., if we have a commitment to not change the logo at least for the next two years then we can go ahead and make this change. Also, the commitment includes potential product changes i.e., we can end up discarding the current product and building something else -- the logo will remain the same.

We'll have this Github thread to refer to in the future ;-)

**Comment by shea256** [comment]
I can agree to that :)

**Comment by muneeb-ali** [comment]
Hash it and put it in the blockchain!

**Comment by guylepage3** [comment]
One last item that @larrysalibra had a very good point on...

>We wouldn't own 4 squares...microsoft beat us to that:

With designs you sometimes need days even weeks to let the eye settle. My eye actually hurts when i see the 4 blocks. The more and more that I look at the 4 dots the easier it is on my eyes. The 4 dots can represent blocks and nodes. I am not a firm believer in literal logo's as when a company changes, pivots, and/or grows they can become outdated and irrelevant. The four dots also add a more inclusive more feminine feel than the hard edged squares which are more masculine. I strongly feel that the 4 blocks do not work and my design recommendation is to go with the 4 dots.

@larrysalibra @shea256 @muneeb-ali @jcnelson - Please let me know your thoughts and we'll close this issue out.

**Comment by shea256** [comment]
+1 for the 4 dots

**Comment by larrysalibra** [comment]
Sounds good to me. Let's ship it!

**Comment by muneeb-ali** [comment]
Looking forward to seeing the final version with 4 dots!

**Comment by guylepage3** [comment]
Final version...

<img width="422" alt="screenshot 2016-12-12 15 09 32" src="https://cloud.githubusercontent.com/assets/1711854/21114945/05aa8a22-c07d-11e6-90d2-7352b6214394.png">

**Comment by shea256** [comment]
Me too!

**Comment by shea256** [comment]
Nice work everyone. Look forward to seeing this incorporated into our products.

**Comment by guylepage3** [comment]
Finalized Blockstack Logo w/stereocopy styling

<img width="859" alt="screenshot 2017-01-03 15 32 27" src="https://cloud.githubusercontent.com/assets/1711854/21622102/e2babdb2-d1c9-11e6-9d0e-5643f24c0e9c.png">

**Comment by guylepage3** [comment]
Closing this issue
