### ISSUE TITLE
Blog post image for release

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#532]
Blog post image for release

Reference
https://github.com/blockstackinc/tokensale/issues/147

**Comment by guylepage3** [comment]
@shea256 know you're busy but can you provide a quick theme for this post?

**Comment by shea256** [comment]
@guylepage3 The theme is the Blockstack token sale.

We are distributing tokens and announcing a timeline and additional details for people to get ready to participate.

No action will be taken other than signing up for our email list and reviewing our documents.

It's a "get ready, here's the sale that's coming up" kind of moment.

**Comment by guylepage3** [comment]
working on this now..

**Comment by guylepage3** [comment]
really working on this now..

**Comment by guylepage3** [comment]
![blog-stacks](https://user-images.githubusercontent.com/1711854/32040586-5ae93566-b9ff-11e7-9c9a-359ac036f74a.png)

**Comment by guylepage3** [comment]
![blog-stacks3](https://user-images.githubusercontent.com/1711854/32057496-73cc37f0-ba35-11e7-83d4-b364183d243e.png)
