### ISSUE TITLE
Add logo to new vimeo page

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#533]
Hey @GinaAbrams can we please add the following logo to the the new vimeo site? 😄 thank you..

https://vimeo.com/user73224458

Logo:
https://github.com/blockstack/designs/blob/master/logo/RGB/bug/blockstack-bug-squared-512x512.png

**Comment by GinaAbrams** [comment]
@guylepage3 done!

**Comment by guylepage3** [comment]
awesome! thank you @GinaAbrams 👍
