### ISSUE TITLE
Keynote/PDF design plan

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#537]
Keynote/PDF design plan

Design strategy
- Think of laying out the document as if it was InDesign but you're in Keynote. So it will be "page layout" looking but keep in mind all the keynote limitations so let's not design it to much like a "page layout" program or it will end up a mess.

Tasks
- [x] Guy will provide access to the "Identity, Storage, Tokens" code illustration that appears on the blocktack.org home page.
- [ ] Make icons as isomorphic as possible and more importantly as consistent in design as possible

**Comment by MechanicalHuman** [comment]
## Missing Assets

### Blockstack for Developers
- [ ] Location of the Sketch files for the "code sample"

### Blockstack by the Numbers
- [ ] Community Member charts (meetup, slack...etc)

### The Blockstack Token
- [ ] Original files of the current illustrations
- [ ] isometric vector stock images > ???
- [ ] Pie chart of ownership

### Who Makes Up Blockstack

- [ ] Location of the headshots of the core team
- [ ] Updated Investors Images

**Comment by guylepage3** [comment]
>Location of the Sketch files for the "code sample"

https://github.com/blockstack/designs/blob/master/blockstack.org/v4.0.0/blockstack.org-v4.sketch

**Comment by guylepage3** [comment]
>isometric vector stock images > ???

- https://github.com/blockstack/designs/blob/master/illustrations/isometric-portal-quick-illy.ai
- https://github.com/blockstack/designs/blob/master/illustrations/isometric-portal-quick-illy.sketch

**Comment by guylepage3** [comment]
>Original files of the current illustrations

All illustration files are here..
- https://github.com/blockstack/designs/tree/master/illustrations

**Comment by guylepage3** [comment]
>Location of the headshots of the core team

https://github.com/blockstack/designs/tree/master/blockstack.com/v2/assets/team-images

**Comment by guylepage3** [comment]
>Updated Investors Images

https://github.com/blockstack/designs/tree/master/blockstack.com/v2/assets/investor-images

**Comment by guylepage3** [comment]
@MechanicalHuman not sure what you're looking for with these two;
1. Community Member charts (meetup, slack...etc)
2. Pie chart of ownership

These may need to come from @shea256 or @jackzampolin

**Comment by guylepage3** [comment]
Pages to complete
- [ ] What is Blockstack
- [ ] The Internet has Big Problems
- [ ] Problem #2
- [ ] The Next Wave of Computing
- [ ] How Blockstack Works
- [ ] The History of Blockstack
- [ ] Blockstack Infrastructure
- [ ] The Blockstack Blockchain & P2P
- [ ] The Blockchain Name System
- [ ] The Blockstack API
- [ ] Blockstack for Developers
- [ ] Identity
- [ ] Storage
- [ ] Tokens
- [ ] Blockstack by the Numbers
- [ ] Application Developer Growth
- [ ] Community Member Growth
- [ ] The Blockstack Token
- [ ] Economics and Ownership
- [ ] Who Makes up Blockstack

**Comment by MechanicalHuman** [comment]
Pages to complete

- [x]  What is Blockstack
- [x]  The Internet has Big Problems
- [x]  Problem #2
- [x]  The Next Wave of Computing
- [x]  How Blockstack Works
- [ ]  The History of Blockstack
- [x]  Blockstack Infrastructure
- [x]  The Blockstack Blockchain & P2P
- [x]  The Blockchain Name System
- [x]  The Blockstack API
- [x]  Blockstack for Developers
    - [x]  Identity
    - [x]  Storage
    - [x]  Tokens
- [x]  Peer-Reviewed Research
- [x]  Blockstack by the Numbers
    - [x]  Application Developer Growth
    - [x]  Code Contributor Growth
    - [ ]  Community Member Growth
- [ ]  The Blockstack Token
- [ ]  Economics and Ownership
- [ ]  Who Makes up BlockstacK

**Comment by guylepage3** [comment]
closing issue.. v2 is being worked on here.. https://github.com/blockstack/designs/issues/545
