### ISSUE TITLE
Blog post image design

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#556]
Blog post image

Ryan [9 minutes ago] 
The registration process for the token sale is about to begin. You can verify and get ready to fund your account OR receive a voucher.

**Comment by guylepage3** [comment]
Ryan [8:38 AM] 
Title: Blockstack Token Sale Registration
Body: The registration process for the token sale is about to begin.

**Comment by shea256** [comment]
Title: Blockstack Token Sale Registration
Body: The registration process for the token sale is beginning.

**Comment by guylepage3** [comment]
![blog-registration](https://user-images.githubusercontent.com/1711854/32276040-ef6ebe70-bee3-11e7-807e-126b3d454dc2.png)

**Comment by guylepage3** [comment]
![blog-registration](https://user-images.githubusercontent.com/1711854/32276263-c67b9690-bee4-11e7-9247-9a90a2537584.png)

**Comment by shea256** [comment]
Nice!
