### ISSUE TITLE
$3,000+ update to hero on blockstack.com

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#559]
Update the hero section so that we can say "Looking to invest $3000+ in tokens? >> CoinList

https://github.com/blockstackinc/blockstack-dot-com/issues/325

**Comment by shea256** [comment]
Here's the copy:

"Investing over $3000?"

If yes
[ Register on CoinList ]
( modal pops up that says "Investments through CoinList over $3000 are for accredited investors only [ I am an accredited investor ] [ Get a voucher for up to $3000 ]" )

If no
[ Register on Blockstack ]

**Comment by guylepage3** [comment]
![blockstack-v3 8 1-hero-register2 2x](https://user-images.githubusercontent.com/1711854/32358124-9bbe6c9e-c019-11e7-8181-7043b274fd4e.png)
![blockstack-v3 8 1-hero-register2-pop 2x](https://user-images.githubusercontent.com/1711854/32358125-a096d486-c019-11e7-8255-f4dea9088e4e.png)

**Comment by shea256** [comment]
Oh wow @guylepage3 I'm thinking we actually just focus on the content in the modal and drop the first set.

**Comment by guylepage3** [comment]
ahhh. ok. let's go with the following then. Yeah?

![blockstack-v3 8 1-hero-register2-pop 2x](https://user-images.githubusercontent.com/1711854/32358176-2786ca3c-c01a-11e7-923a-bc1c2f91de48.png)

**Comment by shea256** [comment]
Yeah exactly

**Comment by shea256** [comment]
Let me tweak the content a bit though. But same format. And of course make it not a modal.

**Comment by shea256** [comment]
I also like the white background in there because it really catches your attention.

**Comment by guylepage3** [comment]
Wait. so no modal?

**Comment by guylepage3** [comment]
![blockstack-v3 8 1-hero-register2 2x](https://user-images.githubusercontent.com/1711854/32358342-87bfd014-c01b-11e7-84f4-0b0a44c08234.png)

**Comment by shea256** [comment]
@guylepage3 Ah wait no, just scrutinized the language and it doesn't follow.

Let's move forward with what you have here: https://github.com/blockstack/designs/issues/559#issuecomment-341607325.

**Comment by guylepage3** [comment]
![blockstack-v3 8 2-hero-register2 2x](https://user-images.githubusercontent.com/1711854/32358953-545cede2-c020-11e7-8b48-a9d929be08a7.png)
![blockstack-v3 8 2-hero-register2-pop 2x](https://user-images.githubusercontent.com/1711854/32358955-589354dc-c020-11e7-8253-d2b14104be6c.png)

**Comment by guylepage3** [comment]
@shea256 Updated.
