### ISSUE TITLE
New placeholder image for blockstack video

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#561]

**Comment by guylepage3** [comment]
![blockstack-video-placeholder-hover2 2x](https://user-images.githubusercontent.com/1711854/32392224-262246bc-c0ab-11e7-9aab-3ab254a4e2d2.jpg)
![blockstack-video-placeholder2 2x](https://user-images.githubusercontent.com/1711854/32392225-262e4836-c0ab-11e7-9f19-896fd081ebd9.jpg)

**Comment by guylepage3** [comment]
![blockstack-video-placeholder-hover2 2x](https://user-images.githubusercontent.com/1711854/32392280-57ac621c-c0ab-11e7-87f5-c54a4b1bd79e.jpg)
![blockstack-video-placeholder2 2x](https://user-images.githubusercontent.com/1711854/32392281-57ba1ee8-c0ab-11e7-8da0-5f3862357a7e.jpg)

**Comment by pstan26** [comment]
The bright one looks good!

**Comment by guylepage3** [comment]
yeah.. i think i didn’t see the visual without the text overtop of her. there’s a sweet spot between 2:09-2:12 where there isn’t text over top of her.

**Comment by guylepage3** [comment]
https://vimeo.com/239730057

**Comment by guylepage3** [comment]
@GinaAbrams can you update this image to appear on vimeo as well?

**Comment by guylepage3** [comment]
@GinaAbrams here's the image to replace the current placeholder image on vimeo.

<img width="1702" alt="screenshot 2017-11-03 18 45 54" src="https://user-images.githubusercontent.com/1711854/32398694-3e4a5510-c0c7-11e7-92aa-81f19ffdd836.png">
