### ISSUE TITLE
Update Arenaplay logo in next release

### ISSUE THREAD

**Issue by xanbots** [blockstack/designs#583]
@guylepage3 for the next browser release: 

![arenaplaylogo_512 2](https://user-images.githubusercontent.com/31934541/33146619-e5796eb4-cf92-11e7-89eb-cf6073c1f509.png)

**Comment by guylepage3** [comment]
![app-icon-arenaplay-256x256](https://user-images.githubusercontent.com/1711854/33150547-f2e05946-cfa1-11e7-86c1-ae490d492eb2.png)
![app-icon-arenaplay-512x512](https://user-images.githubusercontent.com/1711854/33150548-f2edd5e4-cfa1-11e7-9f61-d8454187eabe.png)

**Comment by guylepage3** [comment]
@xanbots it has been added and will be in the next build.
