### ISSUE TITLE
create 5 sizes of azure marketplace logos

### ISSUE THREAD

**Issue by guylepage3** [blockstack/designs#60]
Create 5 logo sizes for placement in the microsoft azure marketplace.

**Sizes**
- [x] 40px x 40px
- [x] 90px x 90px
- [x] 115px x 115px
- [x] 255px x 115px
- [x] 815px x 290px

For the Microsoft Azure 1-click release blog image see https://github.com/blockstack/designs/issues/78

![pasted image at 2016_11_18 06_58 pm](https://cloud.githubusercontent.com/assets/1711854/20450854/c0820f92-adc1-11e6-8aae-36393d0bc0a2.png)

**Placement**
https://azure.microsoft.com/en-us/marketplace/

**Comment by guylepage3** [comment]
Why it's important to view where a logo or brand image is placed before production of imagery begins.

First rule of thumb. Assume the company/person whom requested the image does not know what they are talking about until you see it for your own eyes. Some image sizes above are either stretched, shrunken, or cut off. See below..

<img width="1919" alt="screenshot 2016-11-19 11 49 48" src="https://cloud.githubusercontent.com/assets/1711854/20457007/5377a00e-ae4f-11e6-999d-03bd6594cbb5.png">
<img width="1919" alt="screenshot 2016-11-19 11 51 46" src="https://cloud.githubusercontent.com/assets/1711854/20457008/537ba8f2-ae4f-11e6-9fd0-86ef8f4f0c2f.png">

**Comment by guylepage3** [comment]
Here are images for the following sizes.

- 40px x 40px
- 90px x 90px
- 115px x 115px
- 255px x 115px

![blockstack-ms-marketplace-40x40](https://cloud.githubusercontent.com/assets/1711854/20457031/087e94bc-ae50-11e6-9b58-561991a83f34.png)
![blockstack-ms-marketplace-90x90](https://cloud.githubusercontent.com/assets/1711854/20457032/087e9d86-ae50-11e6-8add-d9851a7f0cbc.png)
![blockstack-ms-marketplace-115x115](https://cloud.githubusercontent.com/assets/1711854/20457034/0882064c-ae50-11e6-9afc-6aacad2df18a.png)
![blockstack-ms-marketplace-255x115](https://cloud.githubusercontent.com/assets/1711854/20457033/087ef9fc-ae50-11e6-9473-5d4872dc8ff4.png)

**Comment by guylepage3** [comment]
As for the "Optional" 815px x 290px size, it appears there is more information needed. This does not look like a logo placement as much as an opportunity to show a brand image to sell the product. ie. show the browser, diagram, version image, etc.

@muneeb please request further details for this image and screen shots as to where the image is appearing.

It appears as though most vm's in their marketplace do not opt in on this larger "Hero" image. I feel that if we can get the information needed we have an opportunity to sell blockstack to the MS Marketplace developers.

**Comment by muneeb-ali** [comment]
Thanks Guy for these! They worked great. I'll ask them for more info.

**Comment by guylepage3** [comment]
Thank you sir. I'll keep this issue open until we find out more info on the 5th hero image.

**Comment by guylepage3** [comment]
Sample of what I am assuming is the "hero image".

@muneeb-ali can we request confirmation that this is in fact the "hero image" that the MS marketplace was referring too?

<img width="1920" alt="screenshot 2016-11-28 11 18 28" src="https://cloud.githubusercontent.com/assets/1711854/20676407/ab78dad8-b55d-11e6-9a1a-ffc90f2db03e.png">

**Comment by guylepage3** [comment]
Will provide a new 40x40 icon.

<img width="1072" alt="screenshot 2016-11-28 11 24 59" src="https://cloud.githubusercontent.com/assets/1711854/20676528/028faf54-b55e-11e6-9b46-e228b0167626.png">

**Comment by guylepage3** [comment]
Update logos to have a 1px white border so there is separation between the logo and any background color

<img width="476" alt="screenshot 2016-11-28 11 36 53" src="https://cloud.githubusercontent.com/assets/1711854/20677275/8d5337d0-b560-11e6-952b-a4942ad0c654.png">

**Comment by guylepage3** [comment]
Created new task for 5th image here https://github.com/blockstack/designs/issues/78

**Comment by guylepage3** [comment]
Complete

**Comment by guylepage3** [comment]
Reopened as Issue https://github.com/blockstack/designs/issues/78 is not the Hero image.

**Comment by guylepage3** [comment]
@shea256 @muneeb-ali shall we go ahead and start using the new logo here? Thoughts?

**Comment by guylepage3** [comment]
There is a required whitespace area that is 455px wide as seen below

<img width="799" alt="screenshot 2016-12-22 16 00 46" src="https://cloud.githubusercontent.com/assets/1711854/21440433/fcf9ca46-c860-11e6-8b90-f767aa131abf.png">

![azure-marketplace-hero](https://cloud.githubusercontent.com/assets/1711854/21440448/1218d82c-c861-11e6-832f-5e9af901678a.png)

**Comment by guylepage3** [comment]
![azure-marketplace-hero](https://cloud.githubusercontent.com/assets/1711854/21440785/acfdc194-c862-11e6-9d73-843c5d6eabb3.png)

**Comment by shea256** [comment]
Nice! We should work on a better description to place in there. At least we should get rid of the "we're pleased to announce" in the beginning.

**Comment by guylepage3** [comment]
Yeah. I was just using that copy for filler text. How about this..

>Blockstack Core is a fully functioning node of Blockstack. These nodes process data from the blockchain and construct a global view of security and ownership mappings. Users don't need to trust any other service or infrastructure.

**Comment by guylepage3** [comment]
![azure-marketplace-hero](https://cloud.githubusercontent.com/assets/1711854/21440972/c4d54c00-c863-11e6-8a00-df09e6a528be.png)

**Comment by guylepage3** [comment]
![azure-marketplace-hero](https://cloud.githubusercontent.com/assets/1711854/21441002/e4b0bc6c-c863-11e6-98d3-72dec3ee5725.png)

**Comment by shea256** [comment]
Nice!

**Comment by guylepage3** [comment]
Final imagery for MS Marketplace. Closing issue.

![azure-marketplace-hero](https://cloud.githubusercontent.com/assets/1711854/21442050/7661f022-c869-11e6-803f-d2c0024066d7.png)
![blockstack-ms-marketplace-40x40](https://cloud.githubusercontent.com/assets/1711854/21442053/7666cbba-c869-11e6-8c9c-74f24644acc4.png)
![blockstack-ms-marketplace-90x90](https://cloud.githubusercontent.com/assets/1711854/21442051/76652152-c869-11e6-86b7-0be2e7eb83d1.png)
![blockstack-ms-marketplace-115x115](https://cloud.githubusercontent.com/assets/1711854/21442054/7669a3c6-c869-11e6-8fbe-639cf01d2476.png)
![blockstack-ms-marketplace-255x115](https://cloud.githubusercontent.com/assets/1711854/21442052/7665b964-c869-11e6-8f52-40f1515cc4eb.png)

**Comment by guylepage3** [comment]
Sent all imagery and copy above to Cale at MS
