### ISSUE TITLE
Bounty Graphic

### ISSUE THREAD

**Issue by vangelig** [blockstack/designs#607]
I was thinking that the bounty graphic for the creation of DAPPs using Blockstack should be updated in order to easily stand out in this massive sea of content inside social platforms. 

It should reflect more of a funding money style advert versus techie jargon - People see content and graphics all day and sometimes if you see a graphic with a sandwich versus me writing the word sandwich you can convey the message faster quicker and better. 

I think if we did the same with the $$ aspect you could possible increase the engagement within these bounties. 
![capture-28](https://user-images.githubusercontent.com/35114991/34583194-6b97ec42-f15c-11e7-9439-cf6f3a91aa35.gif)

**Comment by guylepage3** [comment]
Thanks for creating this @vangelig... I agree a nice graphical element would be awesome here.

Would love to find someone in the community to take a crack at this if they can.. 😄

**Comment by prestonattebery** [comment]
@guylepage3 Has a bounty been added for this design project?

**Comment by guylepage3** [comment]
Closing this issue.
