### ISSUE TITLE
Design @blockstackapps logo and twitter header image

### ISSUE THREAD

**Issue by pstan26** [blockstack/designs#611]
We could have a @blockstackapps twitter account that acts like Product Hunt for Blockstack apps…essentially just announcing them and linking to the app. Looking for logo and twitter background image. 

Branding guidebook: https://projects.invisionapp.com/boards/HE2VVROFSGB27

**Comment by guylepage3** [comment]
@prestonattebery here's the issue for creating the new BlockstackApps logo and twitter header image. I think for art direction we can let you roll with it. 😄

**Comment by prestonattebery** [comment]
Hey all! Working on a concept for the Blockstack Apps Twitter... this is what I envision for the icon. An obvious cue from the Blockstack logo with a subtle change to suggest "app" or "app store." I think the Blockstack design system is fairly abstract as of yet--not overly defined or detailed. Any thoughts on this?
![artboard 1 3x](https://user-images.githubusercontent.com/35507980/35301813-988dd42a-005a-11e8-9609-3df46d67261d.png)
![artboard 4 3x](https://user-images.githubusercontent.com/35507980/35301814-989e1c72-005a-11e8-957d-2b4591d94aa7.png)

**Comment by pstan26** [comment]
Love it, simple, not too busy and clearly a stack of apps :-)

**Comment by pstan26** [comment]
It has my vote. @prestonattebery would you be interested in designing the background for the twitter account?

**Comment by prestonattebery** [comment]
Definitely! Is there anyway I can get access to Blockstack's current pattern library? I'm thinking a color variation or slight edit to what you guys have been using could be a good fit!

**Comment by pstan26** [comment]
You mean aside from https://projects.invisionapp.com/boards/HE2VVROFSGB27/ ?

If not, i have no clue where that would live or if we have one. cc @guylepage3

**Comment by guylepage3** [comment]
@prestonattebery here are the sketch color palettes. https://github.com/blockstack/designs/tree/master/brand/v2.0.0/sketch-color-palettes

**Comment by guylepage3** [comment]
If you just want quick copy and paste of hex values, @pstan26 had the correct link. Just click on each of the colors to view the hex value. https://projects.invisionapp.com/boards/HE2VVROFSGB27/

**Comment by guylepage3** [comment]
@prestonattebery One thing about the purple with the the stereoscopy is that it only works with a light foreground and a dark background. the version with the white/light background above does not work very well. If the stereoscopy is not working, there is no reason for it to be there and then you'd be left with just a purple cube. Having said, that I prefer the dark background one over just a cube.

**Comment by prestonattebery** [comment]
Hm. I have the colors, looking for this pattern--the one used as the Twitter background and the Invision header 
<img width="1832" alt="screen shot 2018-01-24 at 10 50 49 am" src="https://user-images.githubusercontent.com/35507980/35341836-9e336440-00f4-11e8-834d-4310bd836331.png">

**Comment by guylepage3** [comment]
Sorry for the delay @prestonattebery. I was in the middle of writing something up for you yesterday and then my computer crashed. Then it was back to back to back meetings until lunch today.

Here's the Sketch file of the atlas illustration you are looking for.
https://github.com/blockstack/designs/blob/master/brand/v3.0.0/assets/blockstack-atlas-grid.ai

Having said that, the core team made a decision to deprecate the atlas illustration.

The latest illustration I've been using and have not received to much push back on is the one appearing in the background of this banner image.
![image](https://user-images.githubusercontent.com/1711854/35407947-721c7e36-01db-11e8-9e74-1620e081b7c6.png)
Here's the Sketch file for it – https://github.com/blockstack/designs/blob/master/brand/v3.1.0/assets/09-17-berlin-eventbrite.sketch

**Comment by pstan26** [comment]
Beautiful, looking forward to seeing what comes out of this.. can't wait to start promoting apps :-)

**Comment by prestonattebery** [comment]
Okay! Came up with a very simple solution here. Just went with the exact same pattern, flipped the background to white, and made one version blue and the other purple. 

We can push the boundaries further, but it seems like a strength of the Blockstack branding is it's visual conservatism. 

![blockstack-brand-banner-blue](https://user-images.githubusercontent.com/35507980/35456304-00475c9a-02a3-11e8-9cb9-1f7d2412755b.png)

![blockstack-brand-banner-purple](https://user-images.githubusercontent.com/35507980/35456306-00513aee-02a3-11e8-9ccc-a1385d7b68ef.png)

**Comment by guylepage3** [comment]
@prestonattebery this is great. 😄 

Do you want to try designing something that is a small step outside the brand? Add or remove a new element?

**Comment by prestonattebery** [comment]
Yeah!

If I can ask, what is a prevailing idea or benefit you want to convey with the Blockstack app store? How does the design and angle differ from the Apple App store? 

If you can provide a few ideas on symbols or ideas you want to convey, I can find something graphically that fits that!

**Comment by guylepage3** [comment]
@prestonattebery this is actually for our new "Product Hunt" type product. As for guidance, we are pretty open. cc: @pstan26

**Comment by pstan26** [comment]
I like the nice clean background. Also I agree with Guy, maybe we replace
"Blockstack" and the logo with  "Blockstack Apps" and the apps logo as a
brand that matches the logo you suggested, Preston. What do you think?

**Comment by prestonattebery** [comment]
On it!

**Comment by pstan26** [comment]
Cool, I'm so excited to launch this its crazy

**Comment by prestonattebery** [comment]
ALRIGHTY, thoughts on these? Simple, on-brand, as requested! 
![artboard 6](https://user-images.githubusercontent.com/35507980/35540411-bcb1f0c0-0523-11e8-92da-f2a7d0011937.png)
![artboard 8](https://user-images.githubusercontent.com/35507980/35540412-bcbff81e-0523-11e8-9c8b-4fcfa1b189c3.png)

**Comment by pstan26** [comment]
Sweet. This looks great! posting to https://twitter.com/BlockstackApps

@prestonattebery very much appreciate this -- what a great community contribution

**Comment by guylepage3** [comment]
Nice work @prestonattebery. Thank you.

**Comment by guylepage3** [comment]
Closing this issue out. :)
