### ISSUE TITLE
Brand re: Stacks token design idea

### ISSUE THREAD

**Issue by 20jsg17** [blockstack/designs#614]
My first thoughts on Stacks token design/logo... (see attached pencil sketch). 

Just some thoughts on the space Blockstack is occupying in connection with brands and/or logos for Stacks token -  Brand the Stacks token along with the four foundational pillars (internet, blockchain, distributed, decentralized...) but subsume those four foundational pillars within/under the architecture/ecosystem of Blockstack.  

See pencil sketch: 

1. Blockstack logo (along with the four dots (four foundational pillars reference) as one focus (centered) - with a focus hook to Stacks (token))( in larger font then "digital token" etc. - these can all be tiered layer of fonts size and type used, color etc.) (placed properly)

2. along with those four foundational pillars on the perimeter of the token (maybe smallest font size) that make up the new internet (e.g., internet, using distributed blockchain to achieve the ultimate goal a - decentralized internet using Stacks token(s) and/or Blockstack Stacks token(s)).  (Fonts, size, color (can (should) follow Blockstack schemes) etc.)

3. have the Blockstack logo (four dots in white and color) placed between the perimeter words (four foundational pillars)

4. date it 

![stacks token design_jsg_212018](https://user-images.githubusercontent.com/33142327/35703123-b608fdb0-0760-11e8-81b6-a8a39644d0a0.jpg)

See thoughts on Logo too - https://github.com/blockstack/designs/issues/615

**Comment by guylepage3** [comment]
Hey @20jsg17. This is great. This is a duplicate issue to https://github.com/blockstack/designs/issues/535

I'm going to close this issue. Can you move the content over to https://github.com/blockstack/designs/issues/535 please? Thank you sir.
