### ISSUE TITLE
Logo re: Blockstack and Stacks token logo idea(s)...

### ISSUE THREAD

**Issue by 20jsg17** [blockstack/designs#616]
Another thought on branding for Blockstack is to use a logo along with Blockstack, Blockstack Stacks token, Stacks token .... 

I came up with slogan(s)/logo(s) and having been using them on [The Stacks Cafe™](thestackcafe.com)(e.g., let's make a new internet The Decentralized Way™).  Perhaps we might find it a place in the Blockstack landscape (Blockstack, Stacks token,... etc.)(e.g., Blockstack - The Decentralized Way™, Stacks token - The Decentralized Way™ - The Blockstack Way™ shortened version, and other ways - e.g., here https://twitter.com/Grid_dles/status/959505658721849346 and https://thestackcafe.com/blockstack-signature-bounties-two-weeks-to-go/).

Thoughts?

see also Brand re: Stacks token design idea - https://github.com/blockstack/designs/issues/614

**Comment by guylepage3** [comment]
Hey @20jsg17. This is great. This is a duplicate issue to #535

I'm going to close this issue. Can you move the content over to #535 please? Thank you sir.
