### ISSUE TITLE
Blockstack "Decentralizing the World Tour" Logo Needed

### ISSUE THREAD

**Issue by shanvoight** [blockstack/designs#621]
Need to create a new logo for the "Decentralizing the World Tour - Powered by Blockstack" to include on Eventbrite ticketing page, community outreach and future signage. 

@aulneau / Thomas - are you available to help with this request this week? We can work with a similar color scheme as the new site. I can discuss further over slack. 

cc: @cuevasm

**Comment by rcasseus** [comment]
Hello @shanvoight is this still an open issue. On the eventbrite page there is a banner there. Whats the requirements for a logo?

https://www.eventbrite.com/e/decentralizing-the-world-tour-hong-kong-powered-by-blockstack-tickets-52017232944

**Comment by shanvoight** [comment]
We're all set - closing it out. Thanks for checking in @rcasseus. If you are interested in design work pls reach me on slack @shannon. We have a few items on the horizon.
